import type { Route } from "../../classes/Route";
import { dk64Colors, titleColors } from "../../utils/colors";

export const dk64NLEHelmEscapeAdvanced: Route = {
  title: "NLE Helm Escape (Advanced)",
  headerColor: titleColors.dk64,
  doc: "https://docs.google.com/document/d/1tScCIKt3NoKt8FBmNV3NpHeLLF4nIKlauXIUhM42VOE",
  steps: [
    `${dk64Colors.header} *MAIN MENU`,
    `${dk64Colors.header} ISG, Story Skip, Enter File`,
    `${dk64Colors.header} *TRAINING GROUNDS`,
    `${dk64Colors.dk} Cranky's Cancel [0:55], Barrel Barrel cancel [1:24.5], Barrel Barrel, Vine Barrel, Pause Quit`,
    `${dk64Colors.header} *MAIN MENU`,
    `${dk64Colors.header} Examine File, Castle Boss, Multiplayer, Aztec Boss, Multiplayer, Factory Boss`,
    `${dk64Colors.header} Galleon Boss, Multiplayer, Fungi Boss, Wait in Main Menu for Cutscene`,
    `${dk64Colors.header} *DK ISLES`,
    `${dk64Colors.dk} Dive Barrel, Orange Barrel, Wet Escape, Tag W4 & W1, K-Lumsy`,
    `${dk64Colors.dk} Tag Far W1, Rock GB [1], Enter Japes`,
    `${dk64Colors.header} *JUNGLE JAPES`,
    `${dk64Colors.dk} Bush Push, Cannon to GB [2], Tag W2, W2 Shot, Middle Switch, Cancel 'Help Me' CS`,
    `${dk64Colors.dk} Tag W1, STVW to Cage GB [3], BP {1}, Tag W3, Left Switch, Cancel CS, BBlast [4]`,
    `${dk64Colors.dk} W2, GB [5], Tag Diddy`,
    `${dk64Colors.diddy} Mountain GB [6], BP {1}, STVW to Cave GB [7], Enter T&S, Tag DK`,
    `${dk64Colors.dk} Key 1, Torch Push to Void, Exit Japes`,
    `${dk64Colors.header} *DK ISLES`,
    `${dk64Colors.dk} Exit Japes Lobby, Swim to K-Lumsy, Turn in Key 1, W1, Tag W2 & W3, Swim to BFI`,
    `${dk64Colors.dk} Grab Camera, Enter Aztec`,
    `${dk64Colors.header} *ANGRY AZTEC`,
    `${dk64Colors.dk} Shoot Switches to Door, BP {2}, Tag Diddy at Oasis`,
    `${dk64Colors.diddy} Rocketbarrel to BP {2}, Tiny Temple, Clip to GB [8], Free Tiny, STVW to Exit, Tag Tiny`,
    `${dk64Colors.tiny} Enter Tiny Temple, Klaptraps GB w/ Spawn Snag [9], Exit Temple, Tiny Guitar Skip`,
    `${dk64Colors.tiny} BP {1}, Face clip, Head to 5DT, Tag Diddy`,
    `${dk64Colors.diddy} Clip to 5DT, 5DT [10], Enter T&S, Tag DK`,
    `${dk64Colors.dk} Key 2, Roll Clip to 5DT, 5DT [11], Roll Out, Enter Llama Temple`,
    `${dk64Colors.dk} Tag W2, Gun Skew (Gun Dive), Free Lanky [12], Tag Lanky`,
    `${dk64Colors.lanky} Tag W1, Matching GB [13], Skew to Lava Room, BP {1}, W2, W1, Tag Tiny`,
    `${dk64Colors.tiny} Skew to Lava Room, Lava GB [14], Skew to Void, Exit Aztec`,
    `${dk64Colors.header} *DK ISLES`,
    `${dk64Colors.tiny} Exit Aztec Lobby, W2, W1, Turn in Key 2, Exit K-Lumsy, Monkeyport, Instrument GB [15]`,
    `${dk64Colors.tiny} Enter Factory Lobby, Tag Lanky`,
    `${dk64Colors.lanky} Enter Factory`,
    `${dk64Colors.header} *FRANTIC FACTORY`,
    `${dk64Colors.lanky} Hatch Skip, Open Gate from OoB, Production Room GB [16], Drop to Tag Diddy`,
    `${dk64Colors.diddy} Tag Upper W4, Drop, BP {3}, Slam Switch, Head to Storage Room, Tag Lanky`,
    `${dk64Colors.lanky} Free Chunky, Free Chunky GB [17], Tag Tiny`,
    `${dk64Colors.tiny} BP {2}, Vent GB [18], Enter T&S, Tag Chunky`,
    `${dk64Colors.chunky} Key 3, FTVW to Block Tower, BP {1}, To R&D, Tag Lanky`,
    `${dk64Colors.lanky} BP {2}, OStand TBS to Spawn Snag Piano GB [19], Tag DK`,
    `${dk64Colors.dk} F Key Push to R&D, Load DK Textures, Down Chute, Power Shed [20], Tag Chunky`,
    `${dk64Colors.chunky} Dark Room [21], Head to Production Room, Slam Switch, W4, Crusher GB [22], Tag Diddy`,
    `${dk64Colors.diddy} Production Room [23], Tag DK`,
    `${dk64Colors.dk} BP {3}, Crusher Room [24], Void, Exit Factory`,
    `${dk64Colors.header} *DK ISLES`,
    `${dk64Colors.dk} Instrument GB [25], Tag Chunky`,
    `${dk64Colors.chunky} Punch Box, Shoot Kasplat, Tag Tiny`,
    `${dk64Colors.tiny} BP {3}, Exit Factory Lobby, W4, Enter Japes Lobby, Enter Japes`,
    `${dk64Colors.header} *JUNGLE JAPES`,
    `${dk64Colors.tiny} W1, Gun Skew (Gun Dive), Cage GB [26], W3, BP {4}, Stump GB [27], Tag Diddy`,
    `${dk64Colors.diddy} Cage GB [28], Tag Chunky`,
    `${dk64Colors.chunky} Cage GB [29], Tag Lanky`,
    `${dk64Colors.lanky} Cage GB [30], Painting Room [31], Bonus GB [32], BP {3}, Head to Main Tag, Tag Chunky`,
    `${dk64Colors.chunky} STVW to Underground, FTVW to BP {2}, GB [33], Exit, Rock GB [34], W1, Exit Japes`,
    `${dk64Colors.header} *DK ISLES`,
    `${dk64Colors.chunky} Shift Rock, Tag Lanky`,
    `${dk64Colors.lanky} Instrument GB [35], Exit Lobby, Tag W5, Tag DK`,
    `${dk64Colors.dk} W4, Caged GB [36], Tag Chunky`,
    `${dk64Colors.chunky} BP {3}, Enter Galleon`,
    `${dk64Colors.header} *GLOOMY GALLEON`,
    `${dk64Colors.chunky} FTVW to Cannon GB [37], Chest GB [38], Enter T&S, Tag Tiny`,
    `${dk64Colors.tiny} Key 4, BP {5}, Tag Chunky`,
    `${dk64Colors.chunky} FTVW to Lighthouse side, Tag Lanky`,
    `${dk64Colors.lanky} Enguarde GB [39], Tag Diddy`,
    `${dk64Colors.diddy} BP {4}, Raise Water, Turn in 4 BPs [43], Tag Lanky`,
    `${dk64Colors.lanky} STVW to BP {4}, STVW to 2DS, 2DS [44], 5DS [45], Tag Tiny`,
    `${dk64Colors.tiny} 5DS [46], Swim to Cactus`,
    `${dk64Colors.chunky} BP {2}, Void, Exit Galleon`,
    `${dk64Colors.header} *DK ISLES`,
    `${dk64Colors.chunky} Tag Tiny`,
    `${dk64Colors.tiny} STVW to Lobby GB [47], Exit Galleon Lobby, Cage GB [48], W5, Tag Lanky`,
    `${dk64Colors.lanky} Swim to Cage GB [49], Enter K-Lumsy, K-Lumsy GB [50], Turn in Key 4, W1, Tag Chunky`,
    `${dk64Colors.chunky} W5, Hunky Chunky, Slam Big X, Cage GB [51], Big X GB [52], Enter Fungi Lobby, Tag Tiny`,
    `${dk64Colors.tiny} Enter Fungi`,
    `${dk64Colors.header} *FUNGI FOREST`,
    `${dk64Colors.tiny} Head to Giant Mushroom Area, Mushroom bounce to BP {6}, Tag Diddy at back`,
    `${dk64Colors.diddy} Rocketbarrel to enter mushroom at middle, BP {5}, Switch, Tag Lanky`,
    `${dk64Colors.header} Lanky/Tiny/Chunky Switches`,
    `${dk64Colors.dk} Switch, Grab GB [53], Exit Giant Mushroom, Head left to Tag Lanky`,
    `${dk64Colors.lanky} Slam Switch, Dark Room GB [54], Tag Chunky`,
    `${dk64Colors.chunky} BP {5}, Jump down to the left to the water, STVW and Gun Skew to Owl Area, Tag Lanky`,
    `${dk64Colors.lanky} BP {5}, Tag Tiny`,
    `${dk64Colors.tiny} Skew into Anthill [55], Deathwarp, Head to Snide's, Turn in 6 BPs [60], Enter T&S, Tag DK`,
    `${dk64Colors.dk} Key 5, Enter Mill, GB [62], Tag Diddy`,
    `${dk64Colors.diddy} Exit Mill, STVW to Cage GB [63], Damage Skew, Tag DK`,
    `${dk64Colors.dk} BP {4}, Exit Fungi`,
    `${dk64Colors.header} *DK ISLES`,
    `${dk64Colors.dk} Tag Diddy`,
    `${dk64Colors.diddy} Exit Fungi Lobby, Cage GB [64], Fall to W3, Tag Chunky`,
    `${dk64Colors.chunky} W1, Turn in Key 5, W1, W2, Instrument GB [65], Enter Caves Lobby, Punch Wall, Tag Lanky`,
    `${dk64Colors.lanky} BP {6}, Tag Diddy`,
    `${dk64Colors.diddy} Rocketbarrel to Instrument GB [66], Enter Caves`,
    `${dk64Colors.header} *CRYSTAL CAVES`,
    `${dk64Colors.diddy} Gun Skew, Tag W4, BP {6}, Rocketbarrel to tag W5, Rocketbarrel to Zinger Tag, Tag DK`,
    `${dk64Colors.dk} Rotating Room [67], 5DC [68], Tag Tiny`,
    `${dk64Colors.tiny} 5DC [69], Tag Lanky`,
    `${dk64Colors.lanky} W5, BP {7}, Drop to Tag Chunky`,
    `${dk64Colors.chunky} Gun Skew, Gorilla Gone GB [70], Headphones, Ice Shield GB [71], BP {6}, Tag Tiny`,
    `${dk64Colors.tiny} W4, Monkeyport GB [72], W4, STVW to Snide's, Headphones, Tag Lanky`,
    `${dk64Colors.lanky} Turn in 7 BPs [79], Tag Chunky`,
    `${dk64Colors.chunky} Turn in 6 BPs [85], Enter T&S, Tag DK`,
    `${dk64Colors.dk} Key 6, Ledge Kick to BP {5}, Exit Caves`,
    `${dk64Colors.header} *DK ISLES`,
    `${dk64Colors.dk} FTVW to Lava GB [86], Exit Caves Lobby, W1, Enter Cannon, Shoot Gate, Tag Diddy`,
    `${dk64Colors.diddy} BP {7}, Deathwarp, Tag DK`,
    `${dk64Colors.dk} Enter Castle`,
    `${dk64Colors.header} *CREEPY CASTLE`,
    `${dk64Colors.dk} O Clip to Enter Tree, BP {6}, Tree GB [87], Airswim to Crypt, Tag Diddy`,
    `${dk64Colors.diddy} BP {8}, Exit Crypt, Rocketbarrel to Top, Turn in 4 BPs [91] Tag DK`,
    `${dk64Colors.dk} Turn in 6 BPs [97], Library Clip, Library [98], Head to Ballroom Tag, Tag Chunky`,
    `${dk64Colors.chunky} Shed [99], Enter T&S, Enter Kut Out`,
    `${dk64Colors.tiny} Key 7, Trash Can [100], Void, Exit Castle`,
    `${dk64Colors.header} *DK ISLES`,
    `${dk64Colors.tiny} Deathwarp, Exit Castle Lobby, Turn in Keys 6 & 7, Monkeyport`,
    `${dk64Colors.tiny} Enter Helm Lobby, Tag Chunky`,
    `${dk64Colors.chunky} Gorilla Gone to Enter Helm`,
    `${dk64Colors.header} *HIDEOUT HELM`,
    `${dk64Colors.chunky} Tag Tiny`,
    `${dk64Colors.tiny} Slope Climb, Tag DK`,
    `${dk64Colors.dk} DK Helm, Tag W1, Key 8, OClip to void, Helm Escape`,
    `${dk64Colors.chunky} (Optional: Chunky Helm w/ Double Camera FTVW, Loses 15s over DK Helm & Double oclip)`,
    `${dk64Colors.header} *DK ISLES`,
    `${dk64Colors.dk} Deathwarp, Tag Chunky`,
    `${dk64Colors.chunky} Exit Helm Lobby, Turn in Key 8, Turn in Key 3 and Void to skip best Cutscene in the Game`,
    `${dk64Colors.chunky} W3`,
    `${dk64Colors.header} *K ROOL`
  ]
};
