import type { Route } from "../../classes/Route";
import { dk64Colors, titleColors } from "../../utils/colors";

export const dk64Any1Kong2014: Route = {
  title: "Any% 1-Kong (2014)",
  headerColor: titleColors.dk64,
  doc: "https://pastebin.com/mRM7qTEP",
  steps: [
    `${dk64Colors.header} Story skip on`,
    `${dk64Colors.header} Start from fresh file`,
    `${dk64Colors.header} *Start`,
    `${dk64Colors.dk} Wet Escape`,
    `${dk64Colors.dk} Tag W4, W1`,
    `${dk64Colors.dk} Tag high W4`,
    `${dk64Colors.dk} DKHE`,
    `${dk64Colors.dk} Key 8`,
    `${dk64Colors.header} Reset`,
    `${dk64Colors.header} *ISG`,
    `${dk64Colors.header} Set Boss to Factory`,
    `${dk64Colors.header} Set Multiplayer to map 2 (up)`,
    `${dk64Colors.header} Story skip on`,
    `${dk64Colors.header} Enter file`,
    `${dk64Colors.dk} Cranky (fadeout cancel 0:55 with text cancel when screen goes black)`,
    `${dk64Colors.dk} Orange Barrel (fadeout cancel, backflip at ~1:24.5)`,
    `${dk64Colors.dk} Barrel Barrel`,
    `${dk64Colors.dk} Tag far Warp 3`,
    `${dk64Colors.dk} Pause exit (cancel game over cutscene with start at 2:49.4)`,
    `${dk64Colors.header} Examine file`,
    `${dk64Colors.header} Multiplayer map 2 (20 oranges)`,
    `${dk64Colors.header} Factory Boss (for moves & cutscene skip)`,
    `${dk64Colors.tiny} Pause exit`,
    `${dk64Colors.header} Wait for fadeout on main menu`,
    `${dk64Colors.dk} Dry Escape`,
    `${dk64Colors.dk} Take W4`,
    `${dk64Colors.dk} FE`,
    `${dk64Colors.header} *Enter Factory`,
    `${dk64Colors.dk} Tag W1 (Important!!!)`,
    `${dk64Colors.dk} Factory clip`,
    `${dk64Colors.dk} Key 3`,
    `${dk64Colors.dk} Take W1`,
    `${dk64Colors.header} *Exit Factory`,
    `${dk64Colors.dk} Drop to K. Lumsy`,
    `${dk64Colors.dk} Watch Japes open`,
    `${dk64Colors.dk} Turn Key 8`,
    `${dk64Colors.dk} Turn Key 3`,
    `${dk64Colors.dk} Take W1 -> W3`,
    `${dk64Colors.header} *K. Rool`,
    `${dk64Colors.header} Finish`
  ]
};
