import type { Route } from "../../classes/Route";
import { dk64Colors, titleColors } from "../../utils/colors";

export const dk64101Expert: Route = {
  title: "101% Expert",
  headerColor: titleColors.dk64,
  doc: "https://docs.google.com/document/d/1ZCZRdYDDtHwMQmaCej44c1ckG322ydA1ErtLoz-pESY",
  steps: [
    `${dk64Colors.dk} Training Area, Banana Fairy, Tag W5 (3 Crystals), Caves Rainbow Coin, Caves Early`,
    `${dk64Colors.header} *Caves`,
    `${dk64Colors.dk} EXIT`,
    `${dk64Colors.header} Isles to Japes 1`,
    `${dk64Colors.dk} FTVW for Lobby GB [1], Leave Lobby.`,
    `${dk64Colors.dk} Aztec Roof Rainbow Coin, Tag W2, Kick into Japes Lobby. Enter Japes.`,
    `${dk64Colors.header} *Japes 1`,
    `${dk64Colors.dk} Bush push to River, STVW Caged GB [2], Get Blueprint (3 coins), tag W3 (5)`,
    `${dk64Colors.dk} Clear Crown Text, Buy Ammo Belt 1. Climb to Diddy, TAG W2 [3](21) other tree jump (26), rainbow coin.`,
    `${dk64Colors.dk} Shoot the right switch, use W3 (31). Shoot left switch and balloon (41)`,
    `${dk64Colors.dk} Battle Crown Cutscene Skip (46) cannon to GB [4]. Tag W4, Go to Cranky Tag (65).`,
    `${dk64Colors.diddy} [Right] Buy Simian Spring. Use W4. Underwater Bunches (10) 3 coins, Buy gun`,
    `${dk64Colors.diddy} Phasewalk into Caged GB [5] STVW to Cave GB [6](20)`,
    `${dk64Colors.dk} [Left] PAUSE EXIT ON KEY 1 GRAB OR RESET AFTER THE 2ND "DONK" `,
    `${dk64Colors.header} TURN ON STORY SKIP.`,
    `${dk64Colors.header} *Isles to Aztec 1`,
    `${dk64Colors.dk} Tag W1 in ring, Swim to K. Lumsy to Turn in Key 1. W1. W2. Enter Aztec.`,
    `${dk64Colors.header} *Aztec 1`,
    `${dk64Colors.dk} Blueprint & 3 Coins, Llama Cutscene skip to main area, Rainbow Coin`,
    `${dk64Colors.diddy} [Right] Hit W1, buy guitar. Rocketbarrel for BP, enter Tiny temple.`,
    `${dk64Colors.diddy} Climb (18) melt ice. Swim (23), Free Tiny [7], STVW out. Balloon & Hit W2 (38)`,
    `${dk64Colors.dk} Phasewalk to Cranky's area, Buy Super Simian Slam, Shoot Balloons (20)`,
    `${dk64Colors.tiny} [Left] Buy Monkeyport, Hit W3, Get BP, Hit W2 (10)  Buy Gun from Funky, Enter T&S`,
    `${dk64Colors.dk} [Right] Key 5, Banana push into tunnel for GB [8], rollout (40) to 5DT with 2 Coins [9]`,
    `${dk64Colors.dk} BBlast, Balloon (54). Enter Llama Temple. Free Lanky GB [10]. Exit/Enter`,
    `${dk64Colors.dk} W1, Climb Trees for 10 (64), Llama cage GB & 1 Coin [11](67)`,
    `${dk64Colors.tiny} [Left] 1 Coin, Klaptrap GB [12](15) W2, W3`,
    `${dk64Colors.lanky} [Left] 1 SINGLE, Bunch, 2 Coins at most (6) Buy Orangstand Sprint`,
    `${dk64Colors.diddy} W3, Enter Rocketbarrel (40) Through Star (45) Hit 4 gongs, Vulture Course (50)`,
    `${dk64Colors.diddy} Fly to 3 Trees and Tower GB [13](65)  Fly to Totem GB [14]`,
    `${dk64Colors.diddy} Fly to 5DT,  Balloon (75) and GB [15]. EXIT`,
    `${dk64Colors.header} *Isles to Factory`,
    `${dk64Colors.diddy} Ram gongs`,
    `${dk64Colors.tiny} [Right] Bonus GB [16]. W2, W1, Turn in Key 5, Monkeyport to Fairy, Fall to Factory Lobby`,
    `${dk64Colors.lanky} [Left] Enter Factory`,
    `${dk64Colors.header} *Factory`,
    `${dk64Colors.lanky} Activate W2 (5) Clip out to open the cage from out of bounds.`,
    `${dk64Colors.lanky} Navigate to Pipe GB [17] Down Pipe and tag W4 (30) To Storage Room`,
    `${dk64Colors.lanky} Free Chunky GB [18](35), Avoid Coins on Boxes, Buy Trombone (40)`,
    `${dk64Colors.tiny} Buy Instrument`,
    `${dk64Colors.chunky} Cranky then Candy`,
    `${dk64Colors.dk} Buy Bongos, Balloon (10) Power Shed Kick [19](25) BBlast with 4 Bundles (45)`,
    `${dk64Colors.chunky} Dark room GB w/ Rainbow Coin [20](15)`,
    `${dk64Colors.chunky} W1 bunch and at least 1 coin (20), Climb to Bonus Barrel [21]`,
    `${dk64Colors.chunky} FTVW to Funky's, Buy Homing Ammo (Optional: Tag W5 for safety)`,
    `${dk64Colors.lanky} Buy Ammo Belt 2, Orangstand TBS`,
    `${dk64Colors.dk} Arcade Skip for GB and Nintendo Coin [22] Enter T&S, Clear Mad Jack Cutscene`,
    `${dk64Colors.tiny} Key 3, Bunch and caged GB [23](5), Blueprint. Exit/Enter`,
    `${dk64Colors.tiny} Phasewalk to Snide's, Balloon (15)`,
    `${dk64Colors.chunky} Bunch (25) Climb Pole, Balloon (35) Blueprint`,
    `${dk64Colors.tiny} Phasewalk to To Spinning Wheel & both bunches [24](25)`,
    `${dk64Colors.tiny} Funky's balloon and Fairy (35)`,
    `${dk64Colors.diddy} Block Tower [25](28) Jump left to tag`,
    `${dk64Colors.dk} Numbers GB [26](60) Fairy`,
    `${dk64Colors.lanky} Bonus GB [27]. Go to R&D, OStand TBS for Piano GB (41)[28] Balloon (51)`,
    `${dk64Colors.lanky} Store position to escape, clockwise for all bananas (65) and Blueprint, tag`,
    `${dk64Colors.chunky} FTVW for Crown, FTVW to Toy Monster with Balloon [29](55) Exit to Lobby, Break Box`,
    `${dk64Colors.tiny} Blueprint & Fairy, Enter Factory, W2, Car Race [30] Phasewalk out`,
    `${dk64Colors.diddy} R&D room & 2 Balloons [31](48) {3124, 4231, 1342}`,
    `${dk64Colors.diddy} Fall to beaver bother [32] to production room, pound switch, blueprint (60), W4`,
    `${dk64Colors.chunky} Jump for 5 (60) Pound Switch for GB [33], Get (75)                                                                                                              `,
    `${dk64Colors.tiny} Balloon (55). Bonus GB and bunches [34](75)`,
    `${dk64Colors.lanky} Balloon (75)`,
    `${dk64Colors.diddy} Simian Spring to GB [35](75)`,
    `${dk64Colors.dk} Blueprint, Drop to Crusher Room [36](75) EXIT`,
    `${dk64Colors.header} *Isles to Galleon`,
    `${dk64Colors.dk} Music pad GB [37]`,
    `${dk64Colors.diddy} Drop to Bonus GB [38]`,
    `${dk64Colors.chunky} Battle Crown, Fall to Galleon lobby, Blueprint, Enter Galleon`,
    `${dk64Colors.header} *Galleon`,
    `${dk64Colors.chunky} Hit W3 & singles (5) Treasure GB [38] & Fairy (10) Exit/Enter`,
    `${dk64Colors.chunky} Cannon game [39](20), STVW to raise water, to Tag by Snides`,
    `${dk64Colors.dk} [Right] Balloon (10) and BBlast with all Bundles (25)`,
    `${dk64Colors.dk} Hit W5, Enter Lighthouse for bananas & GB [40](55)`,
    `${dk64Colors.tiny} [Left] Balloon (10). Turn in Blueprints. [43] Use W3, Blueprint (20) to T&S`,
    `${dk64Colors.lanky} Key 4, Phasewalk to Battle Crown & Balloons (20) Phasewalk to Cactus Tag`,
    `${dk64Colors.diddy} [Left] Balloon (10)`,
    `${dk64Colors.chunky} [Left] Blueprint and Balloon (30)`,
    `${dk64Colors.tiny} [Left] Submarine GB. [44] Exit/Enter`,
    `${dk64Colors.tiny} Cannon Room Bunches (35) STVW to Hit W2, 2DS [45](45) 5DS with Fairy [46](60)`,
    `${dk64Colors.chunky} [Right] Use W5, Seasick Ship [47](55) Exit/Enter. Use W2 for noclip to Tunnel (75) 5DS [48]`,
    `${dk64Colors.diddy} [Right] 5DS [49](20) Use W5, Rocketbarrel to Balloon (30)`,
    `${dk64Colors.diddy} Ship Switch, Blueprint, Rocket to top for GB [50](40)`,
    `${dk64Colors.diddy} W5 to Mech fish 4 bundles [51](60). Gold Tower [52](75)`,
    `${dk64Colors.tiny} [Right] Bunch and Balloon (75)`,
    `${dk64Colors.lanky} [Left] Gold Tower [53](25), Pearls, Exit/Enter`,
    `${dk64Colors.lanky} Use W2 for No Clip (30) 2DS [54](40) Balloon (50) 5DS [55](65) Enguarde Bunch (70)`,
    `${dk64Colors.dk} [Left] Tunnel Bunches (70) 5DS [56](75)`,
    `${dk64Colors.dk} W4 to Blueprint, Seal GB [57]`,
    `${dk64Colors.lanky} [Right] Seal Race Skip. [58] Exit/Enter Blueprint, STVW to Lighthouse`,
    `${dk64Colors.lanky} Chest bundle (75), Enguarde GB [59]`,
    `${dk64Colors.tiny} [Right] Mermaid GB [60] EXIT`,
    `${dk64Colors.header} *Isles to Helm`,
    `${dk64Colors.tiny} STVW Lobby GB [62], exit lobby & Monkeyport to Sax Pad [63] Helm Early`,
    `${dk64Colors.chunky} [Right] 10 HOMING, Bonus GB [64] Deathwarp`,
    `${dk64Colors.tiny} [Left] 10 more homing, enter helm`,
    `${dk64Colors.header} *Helm`,
    `${dk64Colors.tiny} Climb slopes`,
    `${dk64Colors.dk} [Right] Orange clip or Phasewalk to DK's Room, Pull Lever`,
    `${dk64Colors.diddy} [Right] Rocketbarrel through Stars`,
    `${dk64Colors.header} DOWN BLAST O MATIC`,
    `${dk64Colors.diddy} Battle crown`,
    `${dk64Colors.dk} [Left] Key 8, Exit on Fairies`,
    `${dk64Colors.header} *Isles to Castle`,
    `${dk64Colors.dk} Damage boost or Lag Kick to Blueprint, deathwarp, Drop to Caged GB [65]`,
    `${dk64Colors.dk} Enter Castle Lobby, Shoot Diddy Blueprint Switch`,
    `${dk64Colors.diddy} [Right] Blueprint, deathwarp`,
    `${dk64Colors.dk} [Left] Enter Castle`,
    `${dk64Colors.header} *Creepy Castle`,
    `${dk64Colors.dk} Enter tree (5) Blueprint balloon (15), Fairy & GB [66](20)`,
    `${dk64Colors.dk} Activate W4, climb to W2 (40) (Make sure to have 7 Coins)`,
    `${dk64Colors.diddy} [Right] Use W2, Rocket to cloud (5) Bonus GB [67]`,
    `${dk64Colors.dk} [Left] Activate W5, Drop to library. Get 5 and GB [68](45). Rareware coin and SDSS`,
    `${dk64Colors.dk} Drop behind, Enter Candy's Tunnel (55) (Tag W1 for safety if you die from the bats)`,
    `${dk64Colors.tiny} [Left] Bonus Barrel [69]`,
    `${dk64Colors.chunky} [Right] 20 Bananas and Blueprint (20) Enter Dungeon, 2 Balloons (40) Diddy Gates`,
    `${dk64Colors.dk} [Right] Face Puzzle [70]`,
    `${dk64Colors.lanky} [Right] Bonus Barrel and 2 Balloons (20)[71]`,
    `${dk64Colors.diddy} [Left] 2 Bunches (15) Balloon (25) GB [72] Exit/Enter`,
    `${dk64Colors.diddy} W5, Ballroom [73](50)`,
    `${dk64Colors.header} Switch 6, Stay`,
    `${dk64Colors.header} Switch 2, Stay`,
    `${dk64Colors.header} Switch 5, Stay 5`,
    `${dk64Colors.header} Switch, Stay 2`,
    `${dk64Colors.header} Switch 2, Stay, Brake`,
    `${dk64Colors.tiny} [Right] 2 Bananas before entering, Ballroom car race, Fairy [74](32) Exit/Enter`,
    `${dk64Colors.tiny} Airswim to Blueprint, climb to use W5. Down ramp to (51) Back to trash can (55)`,
    `${dk64Colors.tiny} Trash GB [75](60) and 10 HOMING AMMO. Enter Kut Out`,
    `${dk64Colors.lanky} Key 7. Use W4, W5. Tower GB [76]`,
    `${dk64Colors.lanky} Drop to greenhouse GB [77](50) and Battle Crown.`,
    `${dk64Colors.lanky} Leave, drop to Blueprint, drop to Crypt.`,
    `${dk64Colors.lanky} Get (55) enter room, GB and balloon [78](65) deathwarp (75)`,
    `${dk64Colors.tiny} [Right] Enter room, GB [79](65) deathwarp, Balloon by Funky (75)`,
    `${dk64Colors.diddy} [Left] Blueprint, Balloon (60), enter room, hit W1, GB and Balloon [80](75) leave`,
    `${dk64Colors.dk} [Left] Tag W2, Enter room, balloon (75) Minecart GB [81].`,
    `${dk64Colors.chunky} [Right] Enter room, GB [82]. Exit/Enter`,
    `${dk64Colors.chunky} STVW into Tree, Balloon, Beaver Bother [83](55) Exit/Enter`,
    `${dk64Colors.chunky} W4. Enter shed, GB, Balloon, and 20 HOMING AMMO [84](65)`,
    `${dk64Colors.chunky} FTVW to Museum GB & Balloon [85](75). EXIT`,
    `${dk64Colors.header} *Isles to Aztec 2`,
    `${dk64Colors.chunky} Lift Rock`,
    `${dk64Colors.lanky} [Left] Bonus GB [86] Leave Castle Lobby`,
    `${dk64Colors.lanky} STVW to Caged GB [87] Enter K. Lumsy, Turn in Keys 8,3,4 first`,
    `${dk64Colors.lanky} Phasewalk to Orangstand GB [88] Void`,
    `${dk64Colors.lanky} Activate W3, Use W2, Enter Aztec 2`,
    `${dk64Colors.header} *Aztec 2`,
    `${dk64Colors.lanky} Enter Tiny Temple, Vulture GB [89](19), Crown. Exit/Enter W1`,
    `${dk64Colors.chunky} [Right] FTVW to Hunky Chunky GB [90], Bananas by Snide's Tag (6)`,
    `${dk64Colors.tiny} [Left] Beetle Race [91](20)`,
    `${dk64Colors.dk} [Right] Enter Llama Temple (70), Hit W2, Climb to Activate W1 (75)`,
    `${dk64Colors.lanky} [Right] Fairy, Music Pad, Bonus Barrel [92] Gun Skew to Balloons (39)`,
    `${dk64Colors.lanky} Stairs Bananas (42) Use Warp 1 (47)`,
    `${dk64Colors.tiny} [Right] Lava room GB [93](35), use W2, Balloon (45) Use W1`,
    `${dk64Colors.lanky} [Left] Matching game [94] Skew to Blueprint, Use W2, Leave (50)`,
    `${dk64Colors.lanky} 3 bunches on trees (65), 5DTemple [95](75)`,
    `${dk64Colors.tiny} [Right] Path and 3 trees (65) 5DTemple [96] Leave and 2 Trees (75). T&S in back`,
    `${dk64Colors.chunky} [Right] Key 2, 5DTemple [97](26) & Blueprint. EXIT/Enter`,
    `${dk64Colors.chunky} Vase Room [98](47) Use W1(48).`,
    `${dk64Colors.chunky} Enter Tiny Temple, Bunches(75) and NO BALLOON,  STVW for GB [99]. Exit`,
    `${dk64Colors.header} *Isles to Caves`,
    `${dk64Colors.chunky} Leave Lobby, Remove both boulders, Music Pad GB [100]. Drop to warps tag`,
    `${dk64Colors.lanky} W2. Music Pad, Meme Jump to Caves Lobby. Phasewalk to Blueprint.`,
    `${dk64Colors.diddy} Instrument GB [101], Enter Caves`,
    `${dk64Colors.header} *Crystal Caves`,
    `${dk64Colors.diddy} Tag W2, Bananas by Funky (5), Rocketbarrel to Activate W5`,
    `${dk64Colors.diddy} Rocketbarrel to Bonus Barrel [102](10) Enter Lanky Cabin T&S`,
    `${dk64Colors.lanky} Key 6, Cabin [103](10) Balloon (20)`,
    `${dk64Colors.lanky} (Shoot Lanky's balloon before entering cabin if you can't make it to Warp 2 before the cutscene)`,
    `${dk64Colors.tiny} Balloon & Blueprint (10) Use Warp 2 to skip Kosha cutscene`,
    `${dk64Colors.tiny} 3 River Bananas (13) Hit W4, Swim (15) to 5DI[104](30) Activate W1, W3`,
    `${dk64Colors.tiny} Ice Shield Clip [105](35) Monkeyport for Balloon (45) Use W4`,
    `${dk64Colors.tiny} Mini Monkey to Bonus Barrel [106](50) Use W3 (55)`,
    `${dk64Colors.lanky} 5DI [107](35) Exit/Enter 5 on way to tag (40)`,
    `${dk64Colors.chunky} Walk to Snide's, 2 bananas & Balloon (12) STVW to Gorilla Gone GB [108](20) Use W2`,
    `${dk64Colors.dk} Rotating Room and Crown [109](5) Roll clip into 5DC [110](15)`,
    `${dk64Colors.chunky} PW into 5DC [111](50)`,
    `${dk64Colors.tiny} PW into 5DC (75)[112]`,
    `${dk64Colors.diddy} Balloon (20) PW into Upper 5DC [113](35) PW into Lower 5DC [114](43)`,
    `${dk64Colors.lanky} W5 for Blueprint (60) Ice Tomato [115](70) Beetle Race [116](75)`,
    `${dk64Colors.dk} Blueprint, Use W1 (25) 5DI [117](50) Baboon Blast [118](75)`,
    `${dk64Colors.diddy} W4 for Blueprint, Balloon (65) 5DI [119](75)`,
    `${dk64Colors.chunky} W3 for Balloon (60), W3 Back, 5DI [120](70), Blueprint, Ice Shield GB [121](75) EXIT`,
    `${dk64Colors.header} *Isles to Japes 2`,
    `${dk64Colors.chunky} Leave lobby, Fairy, pound X, Caged GB [122] and Rock GB [123]`,
    `${dk64Colors.chunky} Enter Japes Lobby, Move boulder for Lanky`,
    `${dk64Colors.lanky} [Left] Music Pad GB [124] Enter Japes`,
    `${dk64Colors.header} *Jungle Japes 2`,
    `${dk64Colors.lanky} Bush Push`,
    `${dk64Colors.dk} BBlast [125](75)`,
    `${dk64Colors.chunky} [Left] STVW to underground, Blueprint, GB [126](15) deathwarp.`,
    `${dk64Colors.chunky} Boulder GB [127] Gun Skew with Cutscene. Activate W1, W2 to Snide's Tag`,
    `${dk64Colors.chunky} BUNCHES ON FUNKY, Skew for cage GB [128](25)`,
    `${dk64Colors.lanky} [Right] BUNCH BY SNIDE (5) Fall for cage GB [129], Through wall & W4, Balloon (15)`,
    `${dk64Colors.tiny} [Right] Skew through hut (5) Balloon (15) W4 for Cage GB [130]`,
    `${dk64Colors.tiny} W3, BP, ACTIVATE W5 Logs (45), Stump GB [131], Shell GB [132](67) Exit/Enter`,
    `${dk64Colors.tiny} W1 to Splish Splash Salvage [133](75) Enter T&S`,
    `${dk64Colors.lanky} [Left] Mad Maze Maul [134](20) Walk back to tag`,
    `${dk64Colors.diddy} [Left] Use W2, Enter Mountain (24), Switch, Go to Minecart GB [135](49).`,
    `${dk64Colors.diddy} Open Lanky's Cave, Blueprint (52). Trees (62) Use W2, Mountain GB [136](75) W5`,
    `${dk64Colors.chunky} [Left] Hunky Chunky (45) and Bonus GB [137] Shell clip to fairy, balloons (75)`,
    `${dk64Colors.lanky} [Left] Cave for BP and GB [138](42) Painting Room GB [139] Balloon (75) Fairy, EXIT`,
    `${dk64Colors.header} *Isles to Fungi`,
    `${dk64Colors.dk} Leave Japes Lobby [140] Cannon to Fungi Lobby`,
    `${dk64Colors.chunky} [Left] FTVW to Battle Crown, Enter Fungi`,
    `${dk64Colors.header} *Fungi Forest`,
    `${dk64Colors.chunky} W2 Bananas (5) Activate W4, enter well [141](10)`,
    `${dk64Colors.chunky} Enter shed backdoor, Music Pad (15) Defeat Spider, Clip to main room`,
    `${dk64Colors.chunky} OoB to DK GB [142] Get 2 Kegs, Leave and come back for 3rd Keg [143]`,
    `${dk64Colors.tiny} Leave, Hit W1, Get 7 bananas in river (7) STVW behind Chunky gate`,
    `${dk64Colors.tiny} 2 bunches, Clip to back room (17) and Spider GB [144](22). Exit to Lobby, Fairy`,
    `${dk64Colors.dk} Enter Fungi, Purple tunnel to activate W3, W5 bunch(10)`,
    `${dk64Colors.lanky} TBS, Rabbit Race GB [145] Blueprint (8) W4, W3, clockwise to tag (18)`,
    `${dk64Colors.diddy} Gun Skew, Rocketbarrel (10) Tag Tiny`,
    `${dk64Colors.tiny} Beanstalk GB [146] 2 Trees (32)`,
    `${dk64Colors.chunky} W2 bunch (20), Carry Apple [147](29) Back through wall`,
    `${dk64Colors.tiny} Balloon (42)`,
    `${dk64Colors.dk} Blueprint, get 5 (15), enter shed. Break box (20), Bonus barrel [148], Fairy. Exit/Enter`,
    `${dk64Colors.header} Switch 3, Stay 2`,
    `${dk64Colors.header} Switch, Stay`,
    `${dk64Colors.header} Switch 4, Stay 2`,
    `${dk64Colors.header} Switch 3, Stay 5`,
    `${dk64Colors.header} Switch/Brake`,
    `${dk64Colors.diddy} Turn to Night (20)`,
    `${dk64Colors.diddy} Use W4 (30) Clockwise to (39) owl GB [149](44)`,
    `${dk64Colors.tiny} Enter stump (50) GB [150]. Deathwarp`,
    `${dk64Colors.tiny} W3 (60) Mushroom to Blueprint & Balloon (70) Drop to inner tag`,
    `${dk64Colors.diddy} Rocket up to Bonus Barrel [151] Hit W5, Fall to Blueprint(45) Back out to Baboon Blast (47)`,
    `${dk64Colors.dk} BBlast [152](30) jump down ladder, roll around clockwise (45)`,
    `${dk64Colors.dk} Use W5 (50) Crown`,
    `${dk64Colors.chunky} Face room [153](44), Blueprint (54), Enter Mushroom, fall for bananas (75) Switch`,
    `${dk64Colors.tiny} Shoot switch, pound switch (75) get Bonus GB [154]`,
    `${dk64Colors.lanky} Shoot switch & Balloon (28)`,
    `${dk64Colors.diddy} shoot switch`,
    `${dk64Colors.dk} Pound switch, Cannon [155](65)`,
    `${dk64Colors.lanky} Balloon (38) Go Outside, Phasewalk into Light Room(43)[156]`,
    `${dk64Colors.lanky} Hit Switch for Dark Room (48) 1 bunch and GB [157](53) Exit/Enter`,
    `${dk64Colors.lanky} Use W1 (58) Enter Attic (68) GB and bunch [158](73) get (75) on roof`,
    `${dk64Colors.diddy} STVW to Caged GB [159] Across to Attic GB [160] Bunches (65) and Fairy`,
    `${dk64Colors.dk} Balloon (75) Moonkick to Snide's and turn in Blueprints [168]`,
    `${dk64Colors.chunky} OH BANANA [176]`,
    `${dk64Colors.tiny} OH BANANA [181]`,
    `${dk64Colors.lanky} OH BANANA [189]`,
    `${dk64Colors.diddy} Balloon (75) OH BANANA [197] EXIT`,
    `${dk64Colors.header} *Isles to K. Rool`,
    `${dk64Colors.diddy} Rocketbarrel to Bonus Barrel [198] Waterfall GB [199] Drop and use W3`,
    `${dk64Colors.tiny} [Right] W5 to Fairy Isle caged GB [200], Fairy's GB [201] W5 W3`,
    `${dk64Colors.header} *K ROOL`
  ]
};
