import type { Route } from "../../classes/Route";
import { dk64Colors, titleColors } from "../../utils/colors";

export const dk64NLEAdvanced40BP: Route = {
  title: "NLE Advanced 40BP",
  headerColor: titleColors.dk64,
  doc: "https://docs.google.com/document/d/1v1mxEoyEM_mStvPhxRWyhETX8QW1FsOiD1fkOHiEMEQ",
  steps: [
    `${dk64Colors.header} Have the "10 fairies" option unlocked in the Mystery Menu. Have a 2nd controller connected.`,
    `${dk64Colors.header} *ISG`,
    `${dk64Colors.header} 1. Start a timer as you start Intro Story, activate ISG`,
    `${dk64Colors.header} 2. Turn on Story Skip, delete file 1`,
    `${dk64Colors.header} 3. Enter file 1`,
    `${dk64Colors.dk} 4. Go to Cranky. Press B to cancel Cranky text at 55s, Spawn training barrels`,
    `${dk64Colors.dk} 5. Head to Barrel Barrel, Press A to backflip in ~1:24.5 to cancel the 1:25.1 fadeout`,
    `${dk64Colors.dk} 6. Barrel Barrel & Vine Barrel`,
    `${dk64Colors.dk} 7. Pause Exit ASAP`,
    `${dk64Colors.header} 8. Get back to the main menu ASAP. Hold A after cancelling DKTV`,
    `${dk64Colors.header} 9. View file 1`,
    `${dk64Colors.header} 10. Go to Castle Boss. (ISG will fade you out almost immediately)`,
    `${dk64Colors.header} 11. After fadeout, go to Monkey Smash. You will be kicked out`,
    `${dk64Colors.header} 12. Go to Aztec Boss. (ISG will fade you out almost immediately)`,
    `${dk64Colors.header} 13. Repeat step 11`,
    `${dk64Colors.header} 14. Go to Factory Boss. Pause exit ASAP.`,
    `${dk64Colors.header} 15. Go to Galleon Boss. (ISG will fade you out at 3:23)`,
    `${dk64Colors.header} 16. Repeat step 11`,
    `${dk64Colors.header} 17. Go to Fungi Boss. Pause exit ASAP and Exit back to main menu.`,
    `${dk64Colors.header} 18. Pray for good RNG so you can get pulled into the intro story (at 4:23.8)`,
    `${dk64Colors.dk} Dive Barrel & Orange Barrel, STW to DK Island, Tag Near W4 & W1, K Lumsy`,
    `${dk64Colors.dk} Swim to GB[1] to Japes Lobby.`,
    `${dk64Colors.header} *Japes 1`,
    `${dk64Colors.dk} Bush push, Lag Kick to Cannon, Cannon to GB [2], Tag W2, Shoot Right Switch, Kick down`,
    `${dk64Colors.dk} Shoot Middle Switch, Tag W1, Cancel 'Help Me' Cutscene with Switch Cutscene`,
    `${dk64Colors.dk} STW to Cage GB [3], Jump back inbounds behind gate for BP{1}.`,
    `${dk64Colors.dk} Tag W3. Shoot Left Switch, Enter Baboon Blast to cancel Cutscene, Baboon Blast GB[4].`,
    `${dk64Colors.dk} W2 to GB[5], Grab more ammo boxes while heading to Snide's.`,
    `${dk64Colors.diddy} [Right] Enter hill and get GB[6] on top of it.`,
    `${dk64Colors.diddy} Get BP{1}.`,
    `${dk64Colors.diddy} STVW to cave for GB[7]. Enter T&S.`,
    `${dk64Colors.dk} [Left] Key 1. Torch Clip to Void. Exit level.`,
    `${dk64Colors.header} *Isles to Aztec`,
    `${dk64Colors.dk} Swim to K-Lumsy, Hand in Key 1. W1. Tag W2, W3. Head to Aztec.`,
    `${dk64Colors.header} *Aztec`,
    `${dk64Colors.dk} Get BP{2}, grab 3 crystals. Head to main area. Tag W1.`,
    `${dk64Colors.diddy} [Right] Guitar gazump to open the big door.`,
    `${dk64Colors.diddy} Get BP{2}. Enter Tiny temple.`,
    `${dk64Colors.diddy} Ledge clip and go straight to Tiny GB[8].`,
    `${dk64Colors.diddy} Free Tiny by spelling OKONG. STVW to temple entrance.`,
    `${dk64Colors.tiny} [Right] BP{1}. Head to 5DT.`,
    `${dk64Colors.diddy} [Left] Clip in 5DT for GB [9].`,
    `${dk64Colors.diddy} Head to back of 5DT and enter T&S.`,
    `${dk64Colors.dk} [Left] Key 2. Clip in 5DT for GB[10]. (you can clip in through the front if you want)`,
    `${dk64Colors.dk} Head to Funky's and Banana Push for Bonus GB [11]. Roll out.`,
    `${dk64Colors.dk} Skip Baboon Blast via moonkick or rolling in the back to enter Llama Temple.`,
    `${dk64Colors.dk} Tag W2. Gun skew. Free Lanky AND get GB[12]. Skew back to main area to tag barrel.`,
    `${dk64Colors.lanky} [Right] Tag W1. Skew to matching game GB[13]. Skew to BP{1}. W2, W1.`,
    `${dk64Colors.tiny} [Right] W1, W2 for lava GB[14]. Skew to void out.`,
    `${dk64Colors.header} *Isles to Factory`,
    `${dk64Colors.tiny} W2. W1. Turn in Key 2. Head to Monkeyport pad.`,
    `${dk64Colors.tiny} Use it, instrument GB[15]. Enter Factory lobby.`,
    `${dk64Colors.lanky} [Left] Enter Factory.`,
    `${dk64Colors.header} *Factory`,
    `${dk64Colors.lanky} Hatch Skip/Robot Push, Production room GB[16], Crouch slide to tag`,
    `${dk64Colors.diddy} [Left] Tag W4. Production room for BP{3}. Hit switch. Go to Chunky's area.`,
    `${dk64Colors.lanky} [Right] Free Chunky and get GB[17], Enter T&S`,
    `${dk64Colors.tiny} [Right] Key 3. BP{2}. Mini Monkey to cage GB[18], Clip through Tunnel to Block Tower`,
    `${dk64Colors.tiny} Tag near Dartboard`,
    `${dk64Colors.chunky} [Right] BP {1}, Head to R&D`,
    `${dk64Colors.lanky} [Left] BP {2}`,
    `${dk64Colors.dk} [Left] Drop down Chute to Power Shed, Turn on Production Room, GB [19]`,
    `${dk64Colors.chunky} [Left] Dark Room GB[20]. Production Room to Hit switch. W4 for Crusher GB [21].`,
    `${dk64Colors.diddy} [Right] Cross rotating cylinders and Simian Spring for GB[22].`,
    `${dk64Colors.dk} [Left] Cross rotating cylinders. Shoot kasplat for BP{3}.`,
    `${dk64Colors.dk} Drop down to crusher room. Clip out to get GB [23]. Clip out again to void out. Exit Factory`,
    `${dk64Colors.header} *Isles to Japes 2`,
    `${dk64Colors.dk} Instrument GB[24]`,
    `${dk64Colors.chunky} [Left] Primate Punch crate.`,
    `${dk64Colors.tiny} [Left] BP{3}, Exit Lobby, Take W4 and Enter Japes`,
    `${dk64Colors.header} *Japes 2`,
    `${dk64Colors.tiny} STVW and Gun skew. Caged GB[25]. W3`,
    `${dk64Colors.tiny} Enter tunnel to shell area. BP{4}. Stump GB[26].`,
    `${dk64Colors.diddy} [Left] Skew through wall for Caged GB[27]`,
    `${dk64Colors.chunky} [Left] Caged GB[28]`,
    `${dk64Colors.lanky} [Left] Drop to caged GB[29]. Skew to Painting Room. Clip for GB [30]`,
    `${dk64Colors.lanky} Walk to cave area for BP{3}, Bonus barrel GB[31].`,
    `${dk64Colors.chunky} [Right] STW to enter underground cave for BP{2} and GB[32]. Deathwarp`,
    `${dk64Colors.chunky} Exit and throw rock. Beaver hit into GB[33], W1 and Exit Level`,
    `${dk64Colors.header} *Isles to Galleon`,
    `${dk64Colors.chunky} Remove instrument pad rock.`,
    `${dk64Colors.lanky} [Left] Play instrument for GB[34]. Exit Lobby, Tag W5`,
    `${dk64Colors.dk} [Left] W4, Drop to cage GB[35]. Galleon lobby`,
    `${dk64Colors.chunky} [Left] BP{3}, Enter Galleon`,
    `${dk64Colors.header} *Galleon`,
    `${dk64Colors.chunky} Chests GB [36], Tag W3, Cannon Skew Spawn Snag Cannon Game GB [37].`,
    `${dk64Colors.diddy} [Left] BP {4}, Raise water, Turn in 4 BPs [41], Tag by Snide's`,
    `${dk64Colors.tiny} [Right] Turn in 4 BPs [45] W3, BP {5}`,
    `${dk64Colors.chunky} Key 4.`,
    `${dk64Colors.header} Pufftoss Star Patterns`,
    `${dk64Colors.header} Start all phases going counter clockwise. Each hyphen signifies a turn. End all phases going clockwise except phase 4.`,
    `${dk64Colors.header} Phase 1: 1-3-1`,
    `${dk64Colors.header} Phase 2: 5`,
    `${dk64Colors.header} Phase 3: 1-2-2`,
    `${dk64Colors.header} Phase 4: 1-2-1-1 end CCW`,
    `${dk64Colors.header} Phase 5: 2-2-1`,
    `${dk64Colors.chunky} BP {3}.`,
    `${dk64Colors.tiny} [Left] Swim to 5DS, 5DS [46].`,
    `${dk64Colors.lanky} [Left] 5DS [47], STW to Gold Tower`,
    `${dk64Colors.dk} [Left] Moonkick to BP {4}`,
    `${dk64Colors.lanky} [Right] STVW to Void, STVW to BP {4} Swim to Lighthouse`,
    `${dk64Colors.lanky} Transform into Enguarde, Enguarde GB [48], Head to Mermaid Tag.`,
    `${dk64Colors.tiny} STVW to Void.`,
    `${dk64Colors.header} *Isles to Fungi`,
    `${dk64Colors.tiny} STW for lobby GB[49]. STW to void out.`,
    `${dk64Colors.tiny} Exit lobby and head to Fairy Island. STS for GB[50], W5.`,
    `${dk64Colors.lanky} [Left] Swim for Cage GB behind K Lumsy's cage[51].`,
    `${dk64Colors.lanky} K Lumsy for Orangsprint GB[52]. Turn in Key 4. W1.`,
    `${dk64Colors.chunky} [Right] W5, Hunky Chunky and slam X. STS for cage GB[53].`,
    `${dk64Colors.chunky} Giant rock GB[54]. Enter Cannon`,
    `${dk64Colors.dk} [Right] Enter Fungi.`,
    `${dk64Colors.header} *Fungi`,
    `${dk64Colors.dk} TAG W4 2DOS YOU DINGUS. Pink tunnel to giant mushroom area.`,
    `${dk64Colors.tiny} [Left] Bounce on the mushroom and Ponytail Twirl to BP {6}, Drop to Tag`,
    `${dk64Colors.diddy} [Left] Rocketbarrel to top of giant mushroom. Pick up a homing ammo chest.`,
    `${dk64Colors.lanky} [Right] Hit switch for dark side room GB[55].`,
    `${dk64Colors.chunky} [Right] Jump down to BP{5}. Jump down to Baboon Blast tag barrel.`,
    `${dk64Colors.diddy} [Right] Climb ladder into giant mushroom for BP{5}. Drop down middle and exit mushroom`,
    `${dk64Colors.diddy} STW and Inbounds to giant tree area`,
    `${dk64Colors.lanky} [Right] BP{5}. W4 and head to Snide's area. Oh Banana[60]`,
    `${dk64Colors.chunky} [Right] Oh Banana[65].`,
    `${dk64Colors.dk} [Right] Key 5. Oh Banana [69], Enter Mill. Clip through wall to Conveyer Belt GB[70]`,
    `${dk64Colors.diddy} [Right] STVW by barn for underwater cage GB[71].Skew on thorns.`,
    `${dk64Colors.dk} [Left] BP{5}. Void out and exit level.`,
    `${dk64Colors.header} *Isles to Caves`,
    `${dk64Colors.diddy} [Right] Leave lobby and jump to cage GB[72].`,
    `${dk64Colors.diddy} Fall down waterfall to W3 and use it.`,
    `${dk64Colors.chunky} [Left] W1. Hand in Key 5, W1, W2, move rock for instrument GB[73].`,
    `${dk64Colors.chunky} Enter Caves Lobby. Primate Punch Both Ice walls`,
    `${dk64Colors.lanky} [Left] Get BP{6}.`,
    `${dk64Colors.diddy} [Left] Instrument GB[74]. Enter level.`,
    `${dk64Colors.header} *Caves`,
    `${dk64Colors.diddy} Gun Skew. Cross the river. Get Diddy's BP {6} and Tag W4.`,
    `${dk64Colors.diddy} Rocketbarrel to W5. Rocketbarrel to DK 1DC T&S.`,
    `${dk64Colors.dk} [Left] Key 6, Rotating room GB[75].`,
    `${dk64Colors.tiny} [Left] BP{7}. 5DC [76]`,
    `${dk64Colors.dk} [Right] 5DC [77].`,
    `${dk64Colors.lanky} [Right] W5. Lanky BP {7}. Head to Ice Castle Tag.`,
    `${dk64Colors.dk} [Left] BP {6}. Kick down to Warp Area and Tag W1`,
    `${dk64Colors.chunky} [Left] Gun Skew, Gorilla Gone GB [78], Ice Shield GB [79], BP{6} on top of 5DI`,
    `${dk64Colors.tiny} [Left] W4 to Monkeyport GB [80].W4, STVW to Void, Exit Caves`,
    `${dk64Colors.header} *Isles to Castle`,
    `${dk64Colors.dk} [Right] Damage boost to lava GB[81].`,
    `${dk64Colors.dk} Exit lobby, head to main warps area. W1. Giant cannon to Castle Lobby. Shoot kasplat gate.`,
    `${dk64Colors.diddy} [Right] BP{7}. Enter Castle.`,
    `${dk64Colors.header} *Castle`,
    `${dk64Colors.diddy} Climb to warps area and enter tunnel.`,
    `${dk64Colors.chunky} [Left] BP{7}. Back to tag barrel.`,
    `${dk64Colors.dk} [Right] Leave tunnel on the same side you came in. Clip into tree for BP{7}.`,
    `${dk64Colors.dk} Clip through wall for sniper GB [82]. Back to warps tag barrel and ledge kick to T&S.`,
    `${dk64Colors.lanky} Get Key 7 as Lanky. Clockwise to BP{8}. Jump down to crypt and enter.`,
    `${dk64Colors.diddy} [Left] BP{8}. Back to tag barrel.`,
    `${dk64Colors.tiny} [Right] BP{8}. Deathwarp and exit level.`,
    `${dk64Colors.header} *Isles to Aztec 2`,
    `${dk64Colors.tiny} Leave lobby, K Lumsy and turn in Key 6 and 7. Leave.`,
    `${dk64Colors.tiny} K Rool Island and Monkeyport, Enter Helm Lobby.`,
    `${dk64Colors.dk} [Right] Damage boost to kasplat for BP{8}. Exit lobby and kick down to warps area. W2 to Aztec.`,
    `${dk64Colors.header} *Aztec 2`,
    `${dk64Colors.dk} W1.`,
    `${dk64Colors.chunky} [Left] Hunky Chunky and clip OOB on wall light by bonus barrel. Head to 5DT.`,
    `${dk64Colors.chunky} Clip on back to enter 5DT for BP{8}, Leave 5DT. Head to Snide's.`,
    `${dk64Colors.chunky} Oh Banana[85].`,
    `${dk64Colors.dk} Oh Banana[89].`,
    `${dk64Colors.diddy} Oh Banana[93].`,
    `${dk64Colors.lanky} Oh Banana[96].`,
    `${dk64Colors.tiny} Oh Banana[100].`,
    `${dk64Colors.tiny} Play and lose Beaver Bother to enable pausing. Pause and exit level.`,
    `${dk64Colors.header} *Isles to Helm`,
    `${dk64Colors.tiny} W2. Monkeyport and enter Helm lobby.`,
    `${dk64Colors.chunky} [Right] Gorilla Gone for vines. Enter level.`,
    `${dk64Colors.header} *Helm`,
    `${dk64Colors.tiny} [Left] Kickslide up slope.`,
    `${dk64Colors.chunky} [Right] Shoot switch. Cross vines and clip OOB with terminal.`,
    `${dk64Colors.chunky} Navigate past blast-o-matic door and inbounds. Clip OOB again with terminal to Key 8. Reset.`,
    `${dk64Colors.header} *Isles to K Rool`,
    `${dk64Colors.dk} K Lumsy and turn in Key 8 and 3. Reset on start of K Rool ship cutscene.`,
    `${dk64Colors.dk} W3`,
    `${dk64Colors.header} *Fight K Rool.`
  ]
};
