import type { Route } from "../../classes/Route";
import { dk64Colors, titleColors } from "../../utils/colors";

export const dk64Any5Kong: Route = {
  title: "Any% 5-Kong",
  headerColor: titleColors.dk64,
  doc: "https://pastebin.com/SAQJiWez",
  steps: [
    `${dk64Colors.header} Story skip on`,
    `${dk64Colors.header} *Start`,
    `${dk64Colors.header} ISG`,
    `${dk64Colors.header} Enter File`,
    `${dk64Colors.dk} Exit ASAP`,
    `${dk64Colors.header} Jungle Boss`,
    `${dk64Colors.header} Enter Multiplayer`,
    `${dk64Colors.header} Cancel ISG`,
    `${dk64Colors.dk} Cranky`,
    `${dk64Colors.dk} Training Barrels`,
    `${dk64Colors.dk} Wet Escape`,
    `${dk64Colors.dk} Tag W5 & W1`,
    `${dk64Colors.dk} Swim to K-Lumsy`,
    `${dk64Colors.dk} Tag W1`,
    `${dk64Colors.dk} Open Japes`,
    `${dk64Colors.dk} Moonkick to High W4`,
    `${dk64Colors.dk} STS into BFI`,
    `${dk64Colors.dk} 2 Crystals, W5`,
    `${dk64Colors.header} *Enter Japes`,
    `${dk64Colors.dk} Bush Push`,
    `${dk64Colors.dk} Plant Kick`,
    `${dk64Colors.dk} Rainbow Coin`,
    `${dk64Colors.dk} Tree Kick to Cannon`,
    `${dk64Colors.dk} Pick up GB`,
    `${dk64Colors.dk} Right Switch`,
    `${dk64Colors.dk} Middle & Left Switches`,
    `${dk64Colors.dk} Pause Exit`,
    `${dk64Colors.header} *Exit Japes`,
    `${dk64Colors.dk} Tag Waterfall W3`,
    `${dk64Colors.dk} Hill Rainbow Coin`,
    `${dk64Colors.dk} Enter Caves`,
    `${dk64Colors.dk} Pause Exit`,
    `${dk64Colors.dk} Exit Caves Lobby`,
    `${dk64Colors.header} Enter Aztec`,
    `${dk64Colors.dk} Llama CS Skip / Guitar Skip`,
    `${dk64Colors.diddy} Buy Rocketbarrel`,
    `${dk64Colors.dk} Enter Llama Temple`,
    `${dk64Colors.dk} 1 Crystal`,
    `${dk64Colors.dk} Free Lanky & Deathwarp`,
    `${dk64Colors.dk} Llama CS Skip`,
    `${dk64Colors.dk} Rainbow Coin`,
    `${dk64Colors.diddy} Enter Tiny Temple`,
    `${dk64Colors.diddy} Free Tiny`,
    `${dk64Colors.dk} Reset`,
    `${dk64Colors.header} *Exit Aztec`,
    `${dk64Colors.header} Story Skip`,
    `${dk64Colors.header} Enter File`,
    `${dk64Colors.lanky} W4 & Enter Factory`,
    `${dk64Colors.header} *Enter Factory`,
    `${dk64Colors.lanky} Hatch Skip`,
    `${dk64Colors.lanky} Free Chunky`,
    `${dk64Colors.lanky} Buy Trombone`,
    `${dk64Colors.chunky} Buy Super Simian Slam`,
    `${dk64Colors.tiny} Buy Monkeyport`,
    `${dk64Colors.tiny} Enter T&S`,
    `${dk64Colors.tiny} Key 3`,
    `${dk64Colors.tiny} Pause Exit`,
    `${dk64Colors.header} *Exit Factory`,
    `${dk64Colors.tiny} Monkeyport`,
    `${dk64Colors.tiny} Helm Lobby Early`,
    `${dk64Colors.header} *Enter Helm`,
    `${dk64Colors.tiny} Tiny Slope Climb`,
    `${dk64Colors.chunky} DK / Chunky Helm`,
    `${dk64Colors.chunky} Key 8`,
    `${dk64Colors.header} Reset`,
    `${dk64Colors.header} Enter File`,
    `${dk64Colors.dk} W1 & K-Lumsy`,
    `${dk64Colors.dk} W1, W3`,
    `${dk64Colors.header} *K. Rool`,
    `${dk64Colors.header} End`
  ]
};
