import type { Route } from "../../classes/Route";
import { dk64Colors, titleColors } from "../../utils/colors";

export const dk64101CastleKongs: Route = {
  title: "101% Castle Kongs",
  headerColor: titleColors.dk64,
  doc: "https://docs.google.com/document/d/1kk7klVwxqKUR4YkwWWuKUPV6qcVxCEoS1f8cEyTIab0",
  steps: [
    `${dk64Colors.header} *Isles to Aztec 1`,
    `${dk64Colors.dk} Training Area, Swim to BFI, tag W5, get 3 crystals`,
    `${dk64Colors.dk} Rainbow Coin below Caves {5}, Rainbow Coin on Aztec Lobby {10}`,
    `${dk64Colors.dk} Tag W2, Aztec Early.`,
    `${dk64Colors.header} *Aztec 1`,
    `${dk64Colors.dk} Phasewalk to DK's BP. Llama Cutscene Skip. Rainbow Coin. Tag W1. Buy instrument {2}`,
    `${dk64Colors.dk} Enter T&S, Enter Tag barrel, Key 5, Key 2, reset. Turn on Story Skip.`,
    `${dk64Colors.header} *Isles to Castle 1`,
    `${dk64Colors.dk} Swim to K. Lumsy, turn in Key 5`,
    `${dk64Colors.dk} Castle Lobby, boulder kick to Rainbow Coin {17}, Enter Castle`,
    `${dk64Colors.header} *Castle 1`,
    `${dk64Colors.dk} Climb to warps (5). Activate W4, climb to W2 and tag W2 (25). Enter T&S.`,
    `${dk64Colors.tiny} Free Tiny. Grab invisible bananas up to Cranky (10). Buy up to Monkeyport {0}.`,
    `${dk64Colors.tiny} Drop down to blueprint. Head to crypt, 3 coins, enter crypt.`,
    `${dk64Colors.tiny} Phasewalk into Crypt, Goo hands skip for GB [1](15). Deathwarp, back to tag.`,
    `${dk64Colors.tiny} Enter Tag barrel. Buy gun {0}. Shoot balloon (25). Enter T&S.`,
    `${dk64Colors.chunky} Free Chunky`,
    `${dk64Colors.dk} Leave T&S. Buy Gun and Buy Ammo belt 1. Enter T&S. {11}`,
    `${dk64Colors.lanky} Free Lanky.`,
    `${dk64Colors.diddy} Key 7 with Diddy, do NOT void out. Buy gun and Homing Ammo. Decline Ammo Belt 2 {12}`,
    `${dk64Colors.dk} Crypt bunch & balloon (40) phasewalk to minecart [2], reset. Turn on Story Skip.`,
    `${dk64Colors.header} *Isles to Japes`,
    `${dk64Colors.dk} GB [3] and enter Japes.`,
    `${dk64Colors.header} *Japes`,
    `${dk64Colors.dk} Bush push, get Rainbow Coin {16}. Tag W3 (5).`,
    `${dk64Colors.dk} Climb tree, moonkick to cannon tree, moonkick to Diddy's tree (15), get free Diddy GBs.[4][5]`,
    `${dk64Colors.dk} Get single bananas and tag W2. Rest of single bananas and balloon (31) by Snide's.`,
    `${dk64Colors.chunky} Buy gun. Decline Ammo Belt 2. {22} 2 bunches on Funky's (10).`,
    `${dk64Colors.lanky} 2 bunches w/ 2 coins max (10), buy gun, decline Ammo Belt 2. {24}`,
    `${dk64Colors.lanky} Crown, lag clip or phasewalk and drop to bonus barrel [6]`,
    `${dk64Colors.lanky} Balloon + BP and 4 singles (24), Cranky area balloon (34). Buy moves + SDSS. {2}`,
    `${dk64Colors.tiny} Balloon (10)`,
    `${dk64Colors.chunky} Buy moves.`,
    `${dk64Colors.dk} Roll to take other W4 (40), Balloon (50), buy moves, moonkick to beehive area`,
    `${dk64Colors.chunky} Hunky Chunky for GB [7] and bunches (30), shell clip to balloons (60). Tag in T&S`,
    `${dk64Colors.tiny} 4 singles, balloon and fairy (24), swim to Caged GB [8]`,
    `${dk64Colors.tiny} Swim to Splish Splash GB [9] (29) Enter T&S.`,
    `${dk64Colors.lanky} Key 1. Mad Maze Maul [10] (39) and avoid coins, torch push back to W2`,
    `${dk64Colors.lanky} Cannon skew, caged GB [11], painting room [12] (72) and fairy, 3 singles in water (75)`,
    `${dk64Colors.chunky} Underground, GB [13] (75), blueprint, death exit, Boulder GB [14]`,
    `${dk64Colors.dk} STVW for caged GB [15], Get blueprint, hit W3 & balloon (65) Baboon Blast [16] (75).`,
    `${dk64Colors.diddy} W2. Enter top hill (4), Pound Switch + 1 coin {18}, Minecart GB [17] (29)`,
    `${dk64Colors.diddy} Get BP (32) Climb trees (42). Gun dive to underwater bunches (52)`,
    `${dk64Colors.diddy} Gun skew to cave GB [18] (62) (have 18+ coins)`,
    `${dk64Colors.diddy} Use W2 to Mountain GB [19] (75), skew for caged GB. [20]`,
    `${dk64Colors.chunky} Skew for cage GB [21]`,
    `${dk64Colors.tiny} BP, logs (59), stump GB [22], shell GB [23] (75) Exit.`,
    `${dk64Colors.header} *Isles to Factory`,
    `${dk64Colors.tiny} Monkeyport to fairy, enter Factory lobby`,
    `${dk64Colors.lanky} Enter Factory`,
    `${dk64Colors.header} *Factory`,
    `${dk64Colors.lanky} Bunch on W2 (5) Robot Push OPEN GATE to prod room GB`,
    `${dk64Colors.lanky} Production Room GB, Down Pipe (30), Tag W4`,
    `${dk64Colors.diddy} Drop to BP and pound switch to storage room (2)Moontail to beaver bother`,
    `${dk64Colors.lanky} Climb pipe for singles (35), Free Chunky GB and climb to Candy (40)`,
    `${dk64Colors.tiny} Candy`,
    `${dk64Colors.chunky} Candy`,
    `${dk64Colors.diddy} Cranky and Candy`,
    `${dk64Colors.dk} Balloon (10), Moonkick to Power Shed, BBlast with 4 Bunches (45)`,
    `${dk64Colors.chunky} Dark room with bunches (15), bunch on W1 (20), Climb to Stash Snatch, to arcade T&S`,
    `${dk64Colors.tiny} Key 3, Mini Monkey Cage GB and Bunch (65) to Tiny BP`,
    `${dk64Colors.chunky} Head to Production Room, Pound Switch for GB`,
    `${dk64Colors.chunky} Get GB and ALL BUNCHES (40)`,
    `${dk64Colors.tiny} Balloon (10). Bonus GB and bunches (30)`,
    `${dk64Colors.lanky} Balloon (50)`,
    `${dk64Colors.diddy} Simian Spring to GB (17)`,
    `${dk64Colors.dk} Blueprint, drop to Crusher Room (60) EXIT`,
    `${dk64Colors.dk} Music Pad GB.`,
    `${dk64Colors.chunky} Box`,
    `${dk64Colors.tiny} BP & Fairy, reenter Factory`,
    `${dk64Colors.tiny} Phasewalk to Snides balloon (40)`,
    `${dk64Colors.chunky} Bunch on W3 (45), climb for Balloon (55), Climb to BP`,
    `${dk64Colors.chunky} Avoid loading arcade room`,
    `${dk64Colors.lanky} If above failed, Bonus GB to re-load arcade`,
    `${dk64Colors.dk} (Optional) Spawn snag 16 numbers GB, get balloon, fairy, and singles, back to tag`,
    `${dk64Colors.tiny} Spinning wheel (spawn fairy) to Funky's for balloon. (60). Tag W5.`,
    `${dk64Colors.dk} Arcade R1 Skip, Nintendo Coin. Take W5 back to Funky's tag`,
    `${dk64Colors.diddy} Bananas toward Block Tower (25) climb for GB and 4 bunches (45) Jump to tag`,
    `${dk64Colors.lanky} Bonus GB, up to R&D Orangstand TBS to Piano GB, Balloon (60)`,
    `${dk64Colors.lanky} Blueprint and bananas (75)`,
    `${dk64Colors.diddy} R&D room with 3 balloons (75) {3124, 4231, 1342} back to tag`,
    `${dk64Colors.tiny} Car race (75) phasewalk to tag`,
    `${dk64Colors.chunky} CROWN, Toy Monster (75) EXIT`,
    `${dk64Colors.header} *Isles to Galleon`,
    `${dk64Colors.chunky} Exit lobby, drop to Snide's Crown`,
    `${dk64Colors.diddy} Bonus GB [45]`,
    `${dk64Colors.dk} Kick to Caged GB [46]`,
    `${dk64Colors.chunky} Galleon lobby Blueprint`,
    `${dk64Colors.header} *Galleon`,
    `${dk64Colors.chunky} Tag W3, get single bananas (5), punch gate, treasure GB [47] & fairy (10) Exit/Enter`,
    `${dk64Colors.chunky} Cannon game [48](20), STVW to lighthouse tag underwater`,
    `${dk64Colors.dk} Raise water Balloon (10), BBlast with all Bunches (25) Cutscene Skip 4.3 from last shot`,
    `${dk64Colors.dk} Hit W5, Lighthouse GB with balloon [49](55)`,
    `${dk64Colors.tiny} Balloon (10) Turn in 4 blueprints [53], use W3, blueprint (23)`,
    `${dk64Colors.lanky} Key 4, Crown & balloons (20), phasewalk to cactus tag.`,
    `${dk64Colors.diddy} Balloon (10)`,
    `${dk64Colors.chunky} Blueprint and balloon (30)`,
    `${dk64Colors.tiny} Submarine GB. [54] Exit/Enter`,
    `${dk64Colors.tiny} Cannon room bunches (35), STVW to tag W2, 2DS [55](45) 5DS with fairy [56](60)`,
    `${dk64Colors.chunky} Use W5, seasick GB [57](55) Exit/Enter. Use W2 for noclip to tunnel (75), 5DS [58]`,
    `${dk64Colors.diddy} 5DS [59] 1 bunch and singles (19), W5, rocketbarrel to balloon (29)`,
    `${dk64Colors.diddy} Pound ship switch, Blueprint, rocket to GB [60](39), W5 to Mech fish 4 bunches [61](59). All singles to (65) Gold Tower [62](75)`,
    `${dk64Colors.tiny} Bunch and Balloon (75)`,
    `${dk64Colors.lanky} Gold Tower [63](25), Pearls, Exit/Enter`,
    `${dk64Colors.lanky} Use W2 for noclip (30), 2DS [64](40), balloon (50), 5DS [65](65), Enguarde bunch (70)`,
    `${dk64Colors.dk} Tunnel bunches (70), 5DS [66](75), W4 to blueprint, W4 to Seal GB [67]`,
    `${dk64Colors.lanky} Seal race skip. [68] DOUBLE Exit/Enter`,
    `${dk64Colors.lanky} Blueprint, STVW to Lighthouse, chest bunch (75), Enguarde GB [69]`,
    `${dk64Colors.tiny} Mermaid GB [70] Exit`,
    `${dk64Colors.header} *Isles to Helm`,
    `${dk64Colors.tiny} Lobby GB [71], exit lobby, Monkeyport to sax pad [72] enter Helm lobby`,
    `${dk64Colors.chunky} 10 homing, Bonus GB [73] Deathwarp`,
    `${dk64Colors.tiny} 10 homing (20), enter Helm`,
    `${dk64Colors.header} *Helm`,
    `${dk64Colors.tiny} Climb slopes`,
    `${dk64Colors.dk} OoB to DK Room, Pull Lever`,
    `${dk64Colors.diddy} Rocketbarrel through Stars`,
    `${dk64Colors.header} Shut down Blast-o-Matic`,
    `${dk64Colors.diddy} Battle crown`,
    `${dk64Colors.dk} Key 8, Exit on fairies`,
    `${dk64Colors.header} *Isles to Castle 2`,
    `${dk64Colors.dk} Damage boost to Blueprint deathwarp to leave lobby, enter Castle lobby`,
    `${dk64Colors.dk} Shoot Switch`,
    `${dk64Colors.diddy} Blueprint`,
    `${dk64Colors.dk} Enter Castle`,
    `${dk64Colors.header} *Castle 2`,
    `${dk64Colors.dk} Enter tree, Blueprint balloon (50), Fairy & GB (55)`,
    `${dk64Colors.dk} Clockwise on bottom to Dungeon (70)`,
    `${dk64Colors.tiny} Bonus Barrel`,
    `${dk64Colors.chunky} Bananas to BP, Enter dungeon (20) 2 balloons (40), Open diddy gates.`,
    `${dk64Colors.dk} Face puzzle (75)`,
    `${dk64Colors.lanky} Float to GB, 2 balloons (20) deathwarp`,
    `${dk64Colors.diddy} Bananas (10), chain room, balloon (20) and GB Exit/Enter`,
    `${dk64Colors.diddy} Use W2, Rocket to cloud (25) Bonus GB`,
    `${dk64Colors.dk} Activate W5, Drop to library GB only. Kick to Ballroom area`,
    `${dk64Colors.diddy} Ballroom (50)`,
    `${dk64Colors.header} Switch 6, Stay`,
    `${dk64Colors.header} Switch 2, Stay`,
    `${dk64Colors.header} Switch 5, Stay 5`,
    `${dk64Colors.header} Switch, Stay 2`,
    `${dk64Colors.header} Switch 2, Stay, Brake`,
    `${dk64Colors.tiny} Ballroom car race (35) Fairy & Monkeyport for balloon (55), Exit/Enter to take W5`,
    `${dk64Colors.tiny} Down ramp, jump to trash can (70) Trash GB (75) HOMING AMMO W4, W5`,
    `${dk64Colors.lanky} Enter Tower GB Greenhouse GB (50), Battle Crown`,
    `${dk64Colors.lanky} Crouch slide to blueprint, enter Crypt`,
    `${dk64Colors.lanky} Enter room (65), GB and balloon (75) deathwarp`,
    `${dk64Colors.diddy} Blueprint, Balloon (60), enter room for GB, Balloon (75)`,
    `${dk64Colors.chunky} Enter room, bonus GB Exit/Enter. Phasewalk or swim into tree. Get (55) and GB Exit/Enter`,
    `${dk64Colors.chunky} Climb to use W4, Enter shed w/ 20 HOMING AMMO, GB & balloon (65)`,
    `${dk64Colors.chunky} Enter Museum, balloon (75) and phase fall to GB Exit.`,
    `${dk64Colors.header} *Isles to Aztec`,
    `${dk64Colors.dk} Lift Rock`,
    `${dk64Colors.lanky} Bonus GB`,
    `${dk64Colors.lanky} Fall to K. Lumsy, STVW Caged GB.`,
    `${dk64Colors.lanky} Turn in Keys 8, 1, 7, 4, 3. Phasewalk for Orangstand Sprint GB, void`,
    `${dk64Colors.diddy} Take W2 to Aztec lobby, ram gongs`,
    `${dk64Colors.tiny} Bonus GB [95]`,
    `${dk64Colors.diddy} Enter Aztec`,
    `${dk64Colors.header} *Aztec 2`,
    `${dk64Colors.diddy} W1. Rocketbarrel for BP & balloon (10)`,
    `${dk64Colors.diddy} Tiny Temple (melt ice) (can skip 3 singles) [96](32) Bunch on W2 (37)`,
    `${dk64Colors.lanky} Tiny temple [97], Battle Crown(13) Exit/Enter`,
    `${dk64Colors.tiny} Tiny temple [98](5), balloons in caged area (25), Guitar skip to BP, to Cranky`,
    `${dk64Colors.lanky} Grab bunch and 1 single, tag W3 (19)`,
    `${dk64Colors.chunky} Hunky Chunky GB [99] use far W3 to Cranky`,
    `${dk64Colors.dk} Balloons (20), Rareware coin.`,
    `${dk64Colors.diddy} W3, activate Sun ring (45) + Gong Tower GB (softlock warning!)`,
    `${dk64Colors.diddy} Try again for Vulture GB (50), fly for 3 treetop bunches around Tower (65)`,
    `${dk64Colors.tiny} Beetle Race [102](30)`,
    `${dk64Colors.chunky} Get bananas (6)`,
    `${dk64Colors.dk} Banana Push to GB [103](23), 5DT [104](43), BBlast, balloon(57), enter Llama temple`,
    `${dk64Colors.dk} Tag W2, skew to Lanky cage GB [105] Tag high W1. (57)`,
    `${dk64Colors.tiny} Ignore fairy, skew in lava room, 1 bunch, GB [106](40), use W2, balloon (50), use W1`,
    `${dk64Colors.lanky} Skew into matching game [107], no vine bunch`,
    `${dk64Colors.lanky} W1 (24), Skew to shoot Balloons (44) Leave right side to W2 (47)`,
    `${dk64Colors.lanky} W2 for Blueprint, skew oob for Fairy, Bonus GB [108] Leave temple (50)`,
    `${dk64Colors.lanky} 3 bunches on trees (65), Phasewalk into 5DT [109](75)`,
    `${dk64Colors.diddy} Clip into 5DT [110](75)`,
    `${dk64Colors.tiny} Path & 2 trees (65) Phasewalk into 5DT, phasewalk to fairy [111], 2 trees (75), enter T&S`,
    `${dk64Colors.chunky} Exit T&S, Phase into 5DT [112](26) blueprint & GB Exit/Enter`,
    `${dk64Colors.chunky} Vase Room [113](47), Use W1`,
    `${dk64Colors.dk} Llama cage GB [114](60), Moonkick to trees for bunches (75)`,
    `${dk64Colors.chunky} Tiny Temple [115](75)`,
    `${dk64Colors.header} *Isles to Caves`,
    `${dk64Colors.chunky} Remove Lanky's boulder, Music pad GB [116]. Drop to tag`,
    `${dk64Colors.lanky} W2 to Music pad. Meme jump to Caves lobby.`,
    `${dk64Colors.lanky} Phase to Lobby BP`,
    `${dk64Colors.dk} Phase to Lava GB`,
    `${dk64Colors.diddy} Instrument GB, Enter Caves`,
    `${dk64Colors.header} *Crystal Caves`,
    `${dk64Colors.diddy} Tag W2 Bananas by Funky (5), rocket to tag W5, rocket to Bonus (10), to Lanky T&S`,
    `${dk64Colors.lanky} Key 6, bunch on top (5), enter cabin (10) balloon after (20)`,
    `${dk64Colors.tiny} Blueprint, balloon (10), Take W2 skipping kosha`,
    `${dk64Colors.tiny} River bananas (13), twirl to tag W4, swim for more (15), tag W1, W3, 5DI (30)`,
    `${dk64Colors.tiny} Ice shield clip (35), Monkeyport to balloon (45), W4 Mini Monkey to Bonus Barrel, W3 (55)`,
    `${dk64Colors.lanky} 5DI (35), Exit/Enter Get 5 singles (40)`,
    `${dk64Colors.chunky} Punch wall to Snide balloon, 2CBs (12)`,
    `${dk64Colors.chunky} Phase swim to Gorilla Gone GB (20), to take W2 (30)`,
    `${dk64Colors.dk} Rotating room (5), Battle Crown. Roll clip to 5DC (15)`,
    `${dk64Colors.chunky} 5DC (50)`,
    `${dk64Colors.tiny} 5DC (75)`,
    `${dk64Colors.diddy} High balloon (20) Upper 5DC (35), lower 5DC (43)`,
    `${dk64Colors.lanky} W5 for blueprint (60), Ice tomato (70), Beetle race (75)`,
    `${dk64Colors.dk} Blueprint, drop to take W1 (25)`,
    `${dk64Colors.dk} 2 around 5DI (27), 5DI (47), around for (50) to BBlast w/ 4 bunches (75)`,
    `${dk64Colors.diddy} W4 (53), Blueprint (55), W4, Balloon (65), 5DI (75)`,
    `${dk64Colors.chunky} W3 for Balloon (60), 5DI (70) Blueprint, Ice shield GB (75) Exit`,
    `${dk64Colors.header} *Isles to Fungi`,
    `${dk64Colors.chunky} Leave lobby, Fairy, pound X, Caged GB [139] and Rock GB [140], phase fall or Ceiling Mushroom.`,
    `${dk64Colors.chunky} [Right] Battle Crown, Enter Fungi`,
    `${dk64Colors.header} *Fungi`,
    `${dk64Colors.chunky} W2 Bananas (5), tag W4 enter well [141](10)`,
    `${dk64Colors.chunky} Enter shed backdoor, Music Pad (15), defeat spider, clip to front room`,
    `${dk64Colors.chunky} OoB to Mill GB [142] 2 kegs, leave & reenter mill to reuse keg for GB [143]`,
    `${dk64Colors.tiny} Exit door, swim for 7 singles (7) STVW to back room (17) and Spider GB [144](22)`,
    `${dk64Colors.tiny} Exit get Fairy`,
    `${dk64Colors.dk} Re-enter. Purple tunnel to tag W3, to tag at W5`,
    `${dk64Colors.lanky} Ostand TBS to rabbit race (8)`,
    `${dk64Colors.lanky} Right until splash, 2.5DL, 4L, 11DL, 6.5L, 11.5D`,
    `${dk64Colors.lanky} BP. W4, W3. Bunch and 5 singles to back tag barrel. (18)`,
    `${dk64Colors.diddy} Gun Skew to Rocketbarrel (10). Tag Tiny in midair.`,
    `${dk64Colors.tiny} Beanstalk GB, 2 left-side mushroom bunches. (32).`,
    `${dk64Colors.chunky} Hit W2 (20), Carry Apple (29) Back through wall Balloon by T&S (42)`,
    `${dk64Colors.dk} Blueprint, get 5 (10), enter shed. Break box (15), Bonus barrel, Fairy. Exit/Enter`,
    `${dk64Colors.header} Switch 3, Stay 2`,
    `${dk64Colors.header} Switch, Stay`,
    `${dk64Colors.header} Switch 4, Stay 2`,
    `${dk64Colors.header} Switch 3, Stay 5`,
    `${dk64Colors.header} Switch/Brake`,
    `${dk64Colors.diddy} Jetpack to Night switch (20), Use W4 (30) Clockwise, owl GB (45).`,
    `${dk64Colors.tiny} Enter stump (55) Get GB. Deathwarp, take W3 (60)`,
    `${dk64Colors.tiny} Mushroom bounce to BP, balloon (70) Drop to back tag`,
    `${dk64Colors.diddy} Rocket up to Bonus Barrel Drop to tag W5, jump down to BP mid door`,
    `${dk64Colors.diddy} Get Blueprint (47). Exit out mid door to BBlast.`,
    `${dk64Colors.dk} BBlast (25) jump down ladder, roll around clockwise (40) Take W5 up (50)`,
    `${dk64Colors.dk} Counterclockwise to Battle Crown, climb ladder to tag`,
    `${dk64Colors.chunky} Face room (44), Blueprint (54). Enter Giant Mushroom (59) Descending bananas (75)`,
    `${dk64Colors.chunky} Hit switch.`,
    `${dk64Colors.tiny} Shoot switch, pound switch (75) get Bonus GB`,
    `${dk64Colors.lanky} Shoot switch & Balloon (28)`,
    `${dk64Colors.diddy} Shoot switch`,
    `${dk64Colors.dk} Pound switch, Cannon GB (65).`,
    `${dk64Colors.lanky} Shoot balloon (38), exit top door, phasewalk into Light Room (43)`,
    `${dk64Colors.lanky} Climb to top (48) Dark Room (53) Exit/Enter take W1 (58)`,
    `${dk64Colors.lanky} Enter Attic (68) GB and bunch (73) get (75) on roof`,
    `${dk64Colors.diddy} STVW to Caged GB, Attic GB (65) and Fairy`,
    `${dk64Colors.dk} Go to Diddy's attic balloon (75). Moonkick to Snide's. OH BANANA [168]`,
    `${dk64Colors.chunky} OH BANANA [176]`,
    `${dk64Colors.tiny} OH BANANA [180]`,
    `${dk64Colors.lanky} OH BANANA [188]`,
    `${dk64Colors.diddy} Balloon (75) OH BANANA [196]`,
    `${dk64Colors.header} *Isles to END`,
    `${dk64Colors.diddy} Waterfall GB [197], summit GB [198], drop to Isles tag.`,
    `${dk64Colors.dk} W5, caged GB [199], Fairy's GB [200], void to japes lobby`,
    `${dk64Colors.chunky} Move boulder`,
    `${dk64Colors.lanky} Lobby GB [201], exit lobby, enter K. Rool`,
    `${dk64Colors.header} *K ROOL`
  ]
};
