import type { Route } from "../../classes/Route";
import { dk64Colors, titleColors } from "../../utils/colors";

export const dk64NLE801IQ: Route = {
  title: "NLE 801 IQ Route",
  headerColor: titleColors.dk64,
  doc: "https://docs.google.com/document/d/1oM3ozUh-Sa1GGbNys7cPWLYdeFvhlK9GE9hbs7UT_-E",
  steps: [
    `${dk64Colors.header} *MAIN MENU`,
    `${dk64Colors.header} ISG, Story Skip, Enter File`,
    `${dk64Colors.header} *TRAINING GROUNDS`,
    `${dk64Colors.dk} Cranky's Cancel [0:55], Barrel Barrel cancel [1:24.5], Barrel Barrel, Vine Barrel, Pause Quit`,
    `${dk64Colors.header} *MAIN MENU`,
    `${dk64Colors.header} Examine File, Castle Boss, Multiplayer, Aztec Boss, Multiplayer, Factory Boss`,
    `${dk64Colors.header} Galleon Boss, Multiplayer, Fungi Boss, Wait in Main Menu for Cutscene`,
    `${dk64Colors.header} *DK ISLES`,
    `${dk64Colors.dk} Dive Barrel, Orange Barrel, Wet Escape, Tag W4 & W1, K-Lumsy`,
    `${dk64Colors.dk} Tag Far W1, Rock GB [1], Enter Japes`,
    `${dk64Colors.header} *JUNGLE JAPES`,
    `${dk64Colors.dk} Bush Push, Cannon to GB [2], Tag W2, W2 Shot, Middle Switch, Cancel 'Help Me' CS`,
    `${dk64Colors.dk} Tag W1, STVW to Cage GB [3], BP {1}, Tag W3, Left Switch, Cancel CS, BBlast [4]`,
    `${dk64Colors.dk} W2, GB [5], Enter T&S, Tag Diddy`,
    `${dk64Colors.diddy} Key 1, BP {1}, STVW to Cave GB [6], Phasewalk to Void on Torch, Exit Japes`,
    `${dk64Colors.header} *DK ISLES`,
    `${dk64Colors.diddy} Tag DK in Japes Lobby`,
    `${dk64Colors.dk} Exit Japes Lobby, Swim to K-Lumsy, Turn in Key 1, W1, Tag W2 & W3, Swim to BFI`,
    `${dk64Colors.dk} Grab Camera, Enter Aztec`,
    `${dk64Colors.header} *ANGRY AZTEC`,
    `${dk64Colors.dk} Phasewalk to BP {2}, Tag Diddy at Oasis`,
    `${dk64Colors.diddy} Rocketbarrel to BP {2}, Tiny Temple, Clip to Free Tiny GB [7], Free Tiny, STVW to Exit, Tag Tiny`,
    `${dk64Colors.tiny} Enter Tiny Temple, Klaptraps GB Spawn Snag [8], Exit Temple, Guitar Skip`,
    `${dk64Colors.tiny} BP {1}, Face clip, Head to 5DT, Tag Diddy`,
    `${dk64Colors.diddy} Clip to 5DT, 5DT [9], Enter T&S, Tag DK`,
    `${dk64Colors.dk} Key 2, Phasewalk to 5DT in Crystal Coconut Cove, 5DT [10], Roll Out, Enter Llama Temple`,
    `${dk64Colors.dk} Tag W2, Gun Skew (Gun Dive), Free Lanky [11], Tag Lanky`,
    `${dk64Colors.lanky} Tag W1, Matching GB [12], Skew to Lava Room, BP {1}, W2, W1, Tag Tiny`,
    `${dk64Colors.tiny} Skew to Lava Room, Lava GB [13], Skew to Void, Exit Aztec`,
    `${dk64Colors.header} *DK ISLES`,
    `${dk64Colors.tiny} Exit Aztec Lobby, W2, W1, Turn in Key 2, Exit K-Lumsy, Monkeyport, Instrument GB [14]`,
    `${dk64Colors.tiny} Enter Factory Lobby, Tag DK`,
    `${dk64Colors.dk} Moonkick to Instrument GB [15], Tag Lanky`,
    `${dk64Colors.lanky} Enter Factory`,
    `${dk64Colors.header} *FRANTIC FACTORY`,
    `${dk64Colors.lanky} Hatch Skip, Open Gate from OoB, Production Room GB [16], Drop to Tag Diddy`,
    `${dk64Colors.diddy} Tag Upper W4, Drop, BP {3}, Slam Switch, Head to Storage Room, Tag Lanky`,
    `${dk64Colors.lanky} Free Chunky, Free Chunky GB [17], Enter T&S,Tag Tiny`,
    `${dk64Colors.tiny} Key 3, Headphones, BP {2}, Vent GB [18], Phasewalk to Block Tower area, Phasewalk through Dartboard wall, Dartboard GB [19]`,
    `${dk64Colors.chunky} BP {1}, To R&D, Tag Lanky`,
    `${dk64Colors.lanky} BP {2}, Spawn Snag Piano GB [20], Tag DK`,
    `${dk64Colors.dk} F Key Push to R&D, Load DK Textures or don't, Down Chute, Power Shed [21], Tag Chunky`,
    `${dk64Colors.chunky} Dark Room [22], Head to Production Room, Slam Switch, W4, Crusher GB [23], Tag Diddy`,
    `${dk64Colors.diddy} Production Room [24], Tag DK`,
    `${dk64Colors.dk} BP {3}, Crusher Room [25], Void, Exit Factory`,
    `${dk64Colors.header} *DK ISLES`,
    `${dk64Colors.dk} Tag Chunky`,
    `${dk64Colors.chunky} Punch Box, Shoot Kasplat, Tag Tiny`,
    `${dk64Colors.tiny} BP {3}, Exit Factory Lobby, W4, Enter Japes Lobby, Enter Japes`,
    `${dk64Colors.header} *JUNGLE JAPES`,
    `${dk64Colors.tiny} W1, Gun Skew (Gun Dive), Cage GB [26], W3, BP {4}, Stump GB [27], Tag Diddy`,
    `${dk64Colors.diddy} Cage GB [28], Tag Chunky`,
    `${dk64Colors.chunky} Cage GB [29], Tag Lanky`,
    `${dk64Colors.lanky} Cage GB [30], Painting Room [31], Speedy Swing Sortie GB [32], BP {3}, Head to Main Tag, Tag Chunky`,
    `${dk64Colors.chunky} STVW to Underground, FTVW to BP {2}, GB [33], Exit, Rock GB [34], W1, Exit Japes`,
    `${dk64Colors.header} *DK ISLES`,
    `${dk64Colors.chunky} Shift Rock, Tag Lanky`,
    `${dk64Colors.lanky} Instrument GB [35], Exit Lobby, Tag W5, Tag DK`,
    `${dk64Colors.dk} W4, Caged GB [36], Enter Galleon`,
    `${dk64Colors.header} *GLOOMY GALLEON`,
    `${dk64Colors.dk} Tag Chunky at main Tag`,
    `${dk64Colors.chunky} Chest GB [37], Enter T&S, Tag Tiny`,
    `${dk64Colors.tiny} Key 4, BP {5}, Tag Lanky`,
    `${dk64Colors.lanky} Phasewalk to Lighthouse area, Enguarde GB [38], Tag Diddy`,
    `${dk64Colors.diddy} BP {4}, Raise Water, Turn in 4 BPs [42], Tag Lanky`,
    `${dk64Colors.lanky} STVW to BP {4}, STVW to 2DS, 2DS [43], 5DS [44], Tag Tiny`,
    `${dk64Colors.tiny} 5DS [45], Swim to Cactus`,
    `${dk64Colors.chunky} BP {2}, Void, FTVW to Cannon GB [46] Void Exit Galleon`,
    `${dk64Colors.header} *DK ISLES`,
    `${dk64Colors.chunky} BP {3}, Tag Tiny`,
    `${dk64Colors.tiny} STVW to Lobby GB [47], Exit Galleon Lobby, Cage GB [48], W5, Tag Lanky`,
    `${dk64Colors.lanky} Swim to Cage GB [49], Enter K-Lumsy, Turn in Key 4, Phasewalk oob to K-Lumsy GB [50], VOID, Tag Chunky`,
    `${dk64Colors.chunky} W5, Hunky Chunky, Slam Big X, Cage GB [51], Big X GB [52], Enter Fungi Lobby, Tag Tiny`,
    `${dk64Colors.tiny} Enter Fungi`,
    `${dk64Colors.header} *FUNGI FOREST`,
    `${dk64Colors.tiny} Head to Giant Mushroom Area, Mushroom bounce to BP {6}, Tag Diddy at back`,
    `${dk64Colors.diddy} Rocketbarrel to Top Mushroom Tag, Tag Lanky`,
    `${dk64Colors.lanky} Slam Switch, Dark Room GB [53], Tag Chunky`,
    `${dk64Colors.chunky} BP {5}, Jump to BBlast Tag, Tag Diddy`,
    `${dk64Colors.diddy} Climb ladder and enter Mushroom, BP {5}, Exit Lower Mushroom, Skew to Owl Area, Tag Lanky`,
    `${dk64Colors.lanky} BP {5}, Tag Tiny`,
    `${dk64Colors.tiny} Skew into Anthill [54], Deathwarp, Head to Snide's, Turn in 6 BPs [60], Enter T&S, Tag DK`,
    `${dk64Colors.dk} Key 5, Enter Mill, GB [61], Tag Diddy`,
    `${dk64Colors.diddy} Exit Mill, STVW to Cage GB [62], Damage Skew, Tag DK`,
    `${dk64Colors.dk} BP {4}, Exit Fungi`,
    `${dk64Colors.header} *DK ISLES`,
    `${dk64Colors.dk} Tag Diddy`,
    `${dk64Colors.diddy} Exit Fungi Lobby, Cage GB [63], Fall to W3, Tag Chunky`,
    `${dk64Colors.chunky} W1, Turn in Key 5, W1, W2, Instrument GB [64], Enter Caves Lobby, Punch Wall, Tag Lanky`,
    `${dk64Colors.lanky} BP {6}, Tag Diddy`,
    `${dk64Colors.diddy} Rocketbarrel to Instrument GB [65], Enter Caves`,
    `${dk64Colors.header} *CRYSTAL CAVES`,
    `${dk64Colors.diddy} Gun Skew, BP {6}, Rocketbarrel to tag W5, Rocketbarrel to Zinger Tag, Tag DK`,
    `${dk64Colors.dk} Rotating Room [66], 5DC [67], Tag Tiny`,
    `${dk64Colors.tiny} 5DC [68], Tag Lanky`,
    `${dk64Colors.lanky} W5, BP {7}, Drop to Tag Chunky`,
    `${dk64Colors.chunky} Gun Skew, Gorilla Gone GB [69], Ice Shield GB [70], BP {6}, Tag Tiny`,
    `${dk64Colors.tiny} Tiny 5DI [71], Ice shield clip to Monkeyport GB [72], Phasewalk to 5DI Tag, Tag Lanky`,
    `${dk64Colors.lanky} Lanky 5DI [73], STVW near Chunky Ice Shield to Snide's, Turn in 7 BPs [80], Tag Chunky`,
    `${dk64Colors.chunky} Turn in 6 BPs [86], Enter T&S, Tag DK`,
    `${dk64Colors.dk} Key 6, Ledge Kick to BP {5}, Exit Caves`,
    `${dk64Colors.header} *DK ISLES`,
    `${dk64Colors.dk} FTVW to Lava GB [87], Exit Caves Lobby, W1, Enter Cannon, Shoot Gate, Tag Diddy`,
    `${dk64Colors.diddy} BP {7}, Deathwarp, Tag DK`,
    `${dk64Colors.dk} Enter Castle`,
    `${dk64Colors.header} *CREEPY CASTLE`,
    `${dk64Colors.dk} O Clip to Enter Tree, BP {6}, Tree GB [88], Airswim to Crypt, Tag Diddy`,
    `${dk64Colors.diddy} BP {8}, Exit Crypt, Rocketbarrel to Top, Turn in 4 BPs [92] Tag DK`,
    `${dk64Colors.dk} Turn in 6 BPs [98], Library Clip, Library [99], Kick to Enter W4 T&S, Enter Kut Out.`,
    `${dk64Colors.tiny} Key 7, Trash Can [100], Trash Can Phasewalk Void, Exit Castle`,
    `${dk64Colors.header} *DK ISLES`,
    `${dk64Colors.tiny} Deathwarp, Exit Castle Lobby, Turn in Keys 6 & 7, Monkeyport`,
    `${dk64Colors.tiny} Enter Helm Lobby, Tag Chunky`,
    `${dk64Colors.chunky} Gorilla Gone to Enter Helm`,
    `${dk64Colors.header} *HIDEOUT HELM`,
    `${dk64Colors.chunky} Tag Tiny`,
    `${dk64Colors.tiny} Slope Climb, Tag DK`,
    `${dk64Colors.dk} DK Helm, Tag W1, Key 8, Double Phasewalk Helm Escape`,
    `${dk64Colors.chunky} (Optional: Chunky Helm w/ Double Camera FTVW, Loses 15s over DK Helm & Double oclip)`,
    `${dk64Colors.header} *DK ISLES`,
    `${dk64Colors.dk} Deathwarp, Tag Lanky`,
    `${dk64Colors.lanky} Exit Helm Lobby, Turn in Key 8, Turn in Key 3 and Void to skip best Cutscene in the Game`,
    `${dk64Colors.lanky} W3`,
    `${dk64Colors.header} *K ROOL`,
    `${dk64Colors.header} *ALTERNATE ROUTES:`,
    `${dk64Colors.header} *FRANTIC FACTORY`,
    `${dk64Colors.lanky} Hatch Skip, Open Gate from OoB, Production Room GB [16], Drop to Tag Diddy`,
    `${dk64Colors.diddy} Tag Upper W4, Drop, BP {3}, Slam Switch, Head to Storage Room, Tag Lanky`,
    `${dk64Colors.lanky} Free Chunky, Free Chunky GB [17],Tag Tiny`,
    `${dk64Colors.tiny} Headphones, BP {2}, Vent GB [18], Phasewalk to Block Tower area, Phasewalk through Dartboard wall, Dartboard GB [19]`,
    `${dk64Colors.lanky} BP {2}, Spawn Snag Piano GB [20], Tag Tiny`,
    `${dk64Colors.tiny} Enter TnS, Key 3, Tag Chunky`,
    `${dk64Colors.chunky} BP {1},Tag DK by Funky`,
    `${dk64Colors.dk} Arcade GB [21], Tag Chunky in Storage Room`,
    `${dk64Colors.chunky} Dark Room [22], Head to Production Room, Slam Switch, W4, Crusher GB [23], SJBF to upper Tag, Tag Diddy`,
    `${dk64Colors.diddy} Production Room [24], Tag DK`,
    `${dk64Colors.dk} BP {3}, Crusher Room [25], Void, Exit Factory`
  ]
};
