import type { Route } from "../../classes/Route";
import { dkbColors, titleColors } from "../../utils/colors";

export const dkb100: Route = {
  title: "100%",
  headerColor: titleColors.dkb,
  doc: "",
  steps: [
    `${dkbColors.header} Bananas are [ ], fossils are { }, rare fossils are < >`,
    `${dkbColors.header} *Ingot Isle 1`,
    `${dkbColors.banana} The First Banandium Gem [1]`,
    `${dkbColors.banana} Through the Banana-Mining Belt [2]`,
    `${dkbColors.banana} Digging Up a Snack [3]`,
    `${dkbColors.header} Any% until Lagoon`,
    `${dkbColors.header} *Lagoon 1`,
    `${dkbColors.triple} First Crockoid Cracked! [6]`,
    `${dkbColors.fossil} Fossil above red mushroom on left {1}`,
    `${dkbColors.fossil} Fossil in small pool near reservoir checkpoint {2}`,
    `${dkbColors.header} Grab boom rock, throw at croc`,
    `${dkbColors.triple} Landed in Salvager's Landing! [9]`,
    `${dkbColors.header} Jump to elder`,
    `${dkbColors.banana} Crossed to the Kong Elder's Court! [10] GET Punch Power 1`,
    `${dkbColors.fossil} Grab record, fossil in concrete near record {3}`,
    `${dkbColors.header} Get Kong`,
    `${dkbColors.fossil} Fossil through concrete near back of cargo ship {4}`,
    `${dkbColors.header} Dive to SL102`,
    `${dkbColors.fossil} Fossil on broken ship to right {5}`,
    `${dkbColors.triple} Dipped into Chimpy Channel! [13]`,
    `${dkbColors.header} Challenge stage: Kong Bananza: Pop Party`,
    `${dkbColors.banana} - Atop the Concrete Roof [14]`,
    `${dkbColors.banana} - Hung from the Ceiling [15] GET Drumbeat 1`,
    `${dkbColors.banana} - Pop and Destroy [16]`,
    `${dkbColors.banana} Shipwrecked Treasure [17]`,
    `${dkbColors.fossil} On left pillar towards boss {6}`,
    `${dkbColors.rareFossil} On ledge below (throw chunk from other side) <1>`,
    `${dkbColors.header} Peekabruiser`,
    `${dkbColors.header} Sinkhole Checkpoint`,
    `${dkbColors.header} Dive to Hilltop`,
    `${dkbColors.header} *Hilltop 1`,
    `${dkbColors.quintuple} Bruised Peekabruiser! [22] GET Bananergy 1`,
    `${dkbColors.fossil} Near top of stone banana ahead {1}`,
    `${dkbColors.fossil} On wall of ledge to right (grab stone) {2}`,
    `${dkbColors.header} Surf to concrete circle, use stone to break concrete`,
    `${dkbColors.banana} Gold-Dipped Banana [23]`,
    `${dkbColors.header} Gold in room (damage boost to 1 heart), barrel out (gold: approx 2900)`,
    `${dkbColors.header} Grab dirt on exit, surf to quiztone`,
    `${dkbColors.banana} Hilltop Quiz Master 1-2-3 [24]`,
    `${dkbColors.header} Throw dirt at Cranky while dropping from banana`,
    `${dkbColors.fossil} In mound past stone banana x3 {5}`,
    `${dkbColors.banana} Cranky's Hilltop Rant [25]`,
    `${dkbColors.fossil} In rotating ice pillar {6}`,
    `${dkbColors.fossil} On tip of right banana {7}`,
    `${dkbColors.fossil} Inside right banana x3 {10}`,
    `${dkbColors.banana} Break terravoider, Peeled from Peel Peak [26]`,
    `${dkbColors.header} Challenge stage: Spike-Tide Slope`,
    `${dkbColors.banana} - Against the Oncoming Tide [27]`,
    `${dkbColors.banana} - Against the Winding Tide [28]`,
    `${dkbColors.banana} - Against the Hidden Tide [29]`,
    `${dkbColors.header} Challenge stage: Thorny-Hill Speed Surf`,
    `${dkbColors.banana} - Thorny-Hill Finish Line [30] GET Drumbeat 2`,
    `${dkbColors.banana} - Thorny-Hill Buzzer Beater [31]`,
    `${dkbColors.banana} - Thorny-Hill Hideaway [32]`,
    `${dkbColors.header} Gold from roots/boxes, safety balloons (gold: approx 3300)`,
    `${dkbColors.header} Pay Constructone`,
    `${dkbColors.fossil} On ledge in pit {11}`,
    `${dkbColors.banana} Tunneling through the Pit [33]`,
    `${dkbColors.header} Challenge stage: Nostalgia Country`,
    `${dkbColors.banana} - Treasured Memories [34]`,
    `${dkbColors.banana} - Over the Valley (safety balloons) [35]`,
    `${dkbColors.banana} - Hijinxs in the Jungle [36]`,
    `${dkbColors.header} Dive to Canyon`,
    `${dkbColors.header} *Canyon 1`,
    `${dkbColors.triple} Tumbled into the Canyon Layer! [39]`,
    `${dkbColors.fossil} On outside wall on left side {1}`,
    `${dkbColors.banana} Hanging in the Cliffs [40] GET Bananergy 2`,
    `${dkbColors.banana} Behind Tallfall Cliffs [41]`,
    `${dkbColors.fossil} Behind wall above {2}`,
    `${dkbColors.banana} Scenic Smokestack View [42]`,
    `${dkbColors.fossil} In crystal below {3}`,
    `${dkbColors.fossil} Above concrete wall below {4}`,
    `${dkbColors.banana} Buried in Tallfall Cliffs [43]`,
    `${dkbColors.header} Barrel out`,
    `${dkbColors.banana} Shifty Smash: Cliff Valley [44]`,
    `${dkbColors.banana} Growing from the Stone Wall [45]`,
    `${dkbColors.header} Surf on rail`,
    `${dkbColors.fossil} On/next to house to right x2 {6}`,
    `${dkbColors.banana} Unpilfered Potassium [46]`,
    `${dkbColors.fossil} On rotating pillar {7}`,
    `${dkbColors.fossil} On ledge near side cave banana {8}`,
    `${dkbColors.banana} Stuck in a Side Cave [47]`,
    `${dkbColors.banana} Pay Dirt under the Plateau [48]`,
    `${dkbColors.rareFossil} Inside wall (dig near top of pipe on other side) <1>`,
    `${dkbColors.fossil} Inside wall (dig from corner) {9}`,
    `${dkbColors.banana} Spinning in the Stone Pillar {49}`,
    `${dkbColors.header} Buy Traction Britches`,
    `${dkbColors.banana} Moseyed into the Village! [50]`,
    `${dkbColors.banana} Canyon Chip Exchange [51]`,
    `${dkbColors.header} Terravoider in house, jump to Mechaneck Isle`,
    `${dkbColors.banana} Battle: Explosive Laps [52]`,
    `${dkbColors.banana} Cranky's Canyon Rant [53]`,
    `${dkbColors.fossil} On wall in gap to left {10}`,
    `${dkbColors.fossil} On giraffe near jumping point {11}`,
    `${dkbColors.header} Jump from tree up to stone block`,
    `${dkbColors.banana} Hanging from the Crane [54]`,
    `${dkbColors.banana} Slip into the Secret Room [55] GET Drumbeat 3`,
    `${dkbColors.fossil} On small dirt block above {12}`,
    `${dkbColors.banana} The Crane's Precious Cargo [56]`,
    `${dkbColors.header} Click-Clack Smokestack Roof Checkpoint`,
    `${dkbColors.banana} Battle: Knotted-Thorn Knockout [57]`,
    `${dkbColors.fossil} In concrete in rotating part of smokestack <2>`,
    `${dkbColors.header} Dive to SL301`,
    `${dkbColors.triple} Dropped into the Refinery Depths! [60] GET Health 1`,
    `${dkbColors.header} Dive to SL302, Stompenclomper`,
    `${dkbColors.header} Sinkhole Checkpoint`,
    `${dkbColors.header} Dive to Divide`,
    `${dkbColors.header} *Divide 1`,
    `${dkbColors.quintuple} Stomped Stompenclomper! [65]`,
    `${dkbColors.banana} Divide Quiz Master 3-1-1 [66]`,
    `${dkbColors.banana} Cranky's Divide Rant [67]`,
    `${dkbColors.header} Dive to Forest`,
    `${dkbColors.header} *Forest 1`,
    `${dkbColors.triple} Branched into the Forest Layer! [70]`,
    `${dkbColors.banana} Under Featherfall Isle [71]`,
    `${dkbColors.banana} The Ostrich's Back Snack [72]`,
    `${dkbColors.banana} Battle: Seed to Succeed [73]`,
    `${dkbColors.fossil} Under battle x2 {2}`,
    `${dkbColors.fossil} On stone near battle {3}`,
    `${dkbColors.fossil} On island towards hotel {4}`,
    `${dkbColors.header} Surf across thorns to basement`,
    `${dkbColors.fossil} In wall of basement {5}`,
    `${dkbColors.rareFossil} In sand of basement <1>`,
    `${dkbColors.banana} Egg-Bottom Basement [74]`,
    `${dkbColors.banana} Egg-Bottom Break-In [75]`,
    `${dkbColors.header} Take barrel up; terravoider`,
    `${dkbColors.fossil} On wall opposite x3 (munchoid gets lowest one) {8}`,
    `${dkbColors.fossil} Buried in ground amongst hedges x2 {10}`,
    `${dkbColors.fossil} Behind record barrel {11}`,
    `${dkbColors.header} Take record piece back`,
    `${dkbColors.banana} Checked in at the Eggshell Hotel [76]`,
    `${dkbColors.header} Eggshell Hotel Checkpoint`,
    `${dkbColors.banana} Hangin' in the Lounge [77]`,
    `${dkbColors.banana} Lounge Loft and Found [78]`,
    `${dkbColors.header} Take second record piece back get Ostrich`,
    `${dkbColors.header} Surf to key, dive to SL601`,
    `${dkbColors.banana} Plummeted into Mossplume Marsh! [81] GET Glide 1, Better Flutter, Egg Bomb 1`,
    `${dkbColors.rareFossil} On top of getaway stump to left <2>`,
    `${dkbColors.banana} Stuck in the Stump [82]`,
    `${dkbColors.header} Fly to the third bulb, break it, jump back, dig halfway down stone`,
    `${dkbColors.banana} Secret in the Marsh [83]`,
    `${dkbColors.fossil} Dig under stump with thorns x2 {13}`,
    `${dkbColors.fossil} Jump on Ostrich head x3 {16}`,
    `${dkbColors.fossil} Near challenge {17}`,
    `${dkbColors.header} Challenge stage: Ostrich Bananza: Flighty Feast`,
    `${dkbColors.banana} - Flying through the Sky [84]`,
    `${dkbColors.banana} - Soaring through Space [85]`,
    `${dkbColors.banana} - Gliding through the Heavens [86]`,
    `${dkbColors.header} Start shifty smash`,
    `${dkbColors.banana} Beneath the Moving Platform [87]`,
    `${dkbColors.header} Complete shifty smash`,
    `${dkbColors.fossil} On wall near shift stone {18}`,
    `${dkbColors.header} Break first bulb`,
    `${dkbColors.rareFossil} In dirt below <3>`,
    `${dkbColors.banana} Shifty Smash: Thwart the Thorns [88]`,
    `${dkbColors.fossil} On wall towards Rubbery Roost (dig through terrain) {19}`,
    `${dkbColors.header} Rubbery Roost Checkpoint`,
    `${dkbColors.banana} Bounced into Rubbery Roost! [89]`,
    `${dkbColors.banana} Battle: Bouncing Bites [90]`,
    `${dkbColors.header} Break second bulb`,
    `${dkbColors.header} Throw seed at trunk, lure first Fragmentone piece`,
    `${dkbColors.header} Throw seed at croc, jump across while growing, lure rest`,
    `${dkbColors.banana} Forest Fragmentone Recovery/Restoration [92]`,
    `${dkbColors.fossil} On wall near void stake {20}`,
    `${dkbColors.header} Dive to SL602`,
    `${dkbColors.triple} Waded into Bramblenest Bog! [95] GET Punch Power 2`,
    `${dkbColors.header} Fly towards boss island`,
    `${dkbColors.rareFossil} On arch on right side <4>`,
    `${dkbColors.fossil} On thorny croc {21}`,
    `${dkbColors.header} Hit button for thorn stats`,
    `${dkbColors.fossil} On arch behind button {22}`,
    `${dkbColors.fossil} On stump below {23}`,
    `${dkbColors.header} Trigger boss fight`,
    `${dkbColors.fossil} On island to left x2 {25}`,
    `${dkbColors.header} Hit Abracajabya twice`,
    `${dkbColors.fossil} On sand towards boss {26}`,
    `${dkbColors.fossil} On grass ahead {27}`,
    `${dkbColors.header} Finish boss fight`,
    `${dkbColors.banana} Roosted in a Thorny Nest [96]`,
    `${dkbColors.fossil} On stump back towards sinkhole {28}`,
    `${dkbColors.header} Dive to Junction`,
    `${dkbColors.header} *Junction 1`,
    `${dkbColors.quintuple} Uprooted Abracajabya! [101]`,
    `${dkbColors.header} Forest side terravoider`,
    `${dkbColors.header} Challenge stage: Crossing through Crosshairs`,
    `${dkbColors.banana} - Target on the Run [102]`,
    `${dkbColors.banana} - Out-of-Range Perch [103]`,
    `${dkbColors.banana} - Target Escaped [104]`,
    `${dkbColors.header} Bridge skip, warp to gong, go to Hilltop`,
    `${dkbColors.header} *Hilltop 2`,
    `${dkbColors.header} Defeat Void`,
    `${dkbColors.fossil} Behind starting point x3 {14}`,
    `${dkbColors.banana} Cave-Dwelling Treasure [105]`,
    `${dkbColors.header} Warp to gong, go to Lagoon`,
    `${dkbColors.header} *Lagoon 2`,
    `${dkbColors.header} Defeat Void`,
    `${dkbColors.header} Warp to gong, go to Junction`,
    `${dkbColors.header} *Junction 2`,
    `${dkbColors.header} Defeat Void, Dive to Resort`,
    `${dkbColors.header} *Resort 1`,
    `${dkbColors.quintuple} Drove Off Void Kong! [110]`,
    `${dkbColors.fossil} In grass mound to left x2 {2}`,
    `${dkbColors.banana} Buried in the Beach [111]`,
    `${dkbColors.header} Rainbow road to watermelon`,
    `${dkbColors.header} Watermelon Memorial Checkpoint`,
    `${dkbColors.header} Dive to Tempest`,
    `${dkbColors.header} *Tempest 1`,
    `${dkbColors.triple} Stormed into the Tempest! [114]`,
    `${dkbColors.fossil} On stone to left {1}`,
    `${dkbColors.fossil} Terravoider near lava, fossil in corrider behind {2}`,
    `${dkbColors.banana} Cavernous Corridors [115]`,
    `${dkbColors.fossil} Behind dirt ahead {3}`,
    `${dkbColors.banana} Tour through the Tunnels [116]`,
    `${dkbColors.fossil} Near lava lake checkpoint (dig around unbreakable wall) {4}`,
    `${dkbColors.header} Blusterwing 1, dive to SL901`,
    `${dkbColors.triple} Beat Sinister Blusterwing! [119]`,
    `${dkbColors.rareFossil} Fly to stalactite near first record piece <1>`,
    `${dkbColors.fossil} On stalagmite near first record piece {5}`,
    `${dkbColors.header} Juggle record pieces, get Elephant`,
    `${dkbColors.fossil} In lava elephant x2 {7}`,
    `${dkbColors.header} Dive to SL901 from village`,
    `${dkbColors.banana} Battle: Revolving-Ring Rumble [120] GET Better Inhaling 1 & 2`,
    `${dkbColors.fossil} Near zipline to second record piece (elephant from above) {8}`,
    `${dkbColors.fossil} In lava towards next banana {9}`,
    `${dkbColors.banana} Lava Bath in the Hot Shower [121]`,
    `${dkbColors.fossil} Near barrel behind wall {10}`,
    `${dkbColors.fossil} On leg of large elephant below {11}`,
    `${dkbColors.header} Get key, surf to stake`,
    `${dkbColors.fossil} Throw balls in lava past lake x2 {13}`,
    `${dkbColors.header} Blusterwing 2, dive to SL902`,
    `${dkbColors.triple} Beat Sinister Blusterwing! Again! [124]`,
    `${dkbColors.header} Challenge stage: Zip-Line Valley`,
    `${dkbColors.banana} - A View of Zip-Line Valley [125] GET Better Collecting 1`,
    `${dkbColors.banana} - Zipping through the Valley [126]`,
    `${dkbColors.banana} - Zips, Hops and Swaps [127]`,
    `${dkbColors.fossil} In mud in small pool near exit to Cranky {14}`,
    `${dkbColors.banana} Cranky's Tempest Rant [128]`,
    `${dkbColors.fossil} AFAT to top of large elephant {15}`,
    `${dkbColors.fossil} Climb ladder, in lava to right {16} (Lava stats)`,
    `${dkbColors.banana} Shifty Smash: Scorching Sauna [129] (Lava stats)`,
    `${dkbColors.banana} Taking in the Stormy Scenery [130]`,
    `${dkbColors.fossil} Under elephant to right {17}`,
    `${dkbColors.fossil} In large elephant's eyes x2 {19}`,
    `${dkbColors.banana} Battle: Elevator Encounter [131]`,
    `${dkbColors.banana} Stuck in the Elephant Snout [132]`,
    `${dkbColors.header} Jump to next island`,
    `${dkbColors.fossil} In small elephant {20}`,
    `${dkbColors.fossil} In corner of lava {21}`,
    `${dkbColors.banana} Inhaling Hot Lava [133] (Lava stats)`,
    `${dkbColors.banana} Shifty Smash: Stairs in the Storm [134]`,
    `${dkbColors.fossil} In small elephant from below x2 {23}`,
    `${dkbColors.header} Jump to next island`,
    `${dkbColors.rareFossil} In lava on left <2>`,
    `${dkbColors.fossil} Behind elephant getaway {24}`,
    `${dkbColors.header} Challenge stage: Hot-Lava Hotfoot`,
    `${dkbColors.banana} - End of the Lava Road [135] GET Health 2`,
    `${dkbColors.banana} - Atop the Lava Road [136]`,
    `${dkbColors.banana} - Crossing the Lava Road [137]`,
    `${dkbColors.banana} Scorching, Shocking Scaffolds [138] (Lava stats)`,
    `${dkbColors.header} Gold room under elephant (gold: approx 5600)`,
    `${dkbColors.banana} Safe Under Shelter [139]`,
    `${dkbColors.banana} Banana in the Mud Bath [140]`,
    `${dkbColors.fossil} In mud to left (elephant from banana) {25}`,
    `${dkbColors.fossil} Take barrel up, in tusk of large elephant {26}`,
    `${dkbColors.banana} Among the Rocky Elephants [141]`,
    `${dkbColors.fossil} Behind large elephant {27}`,
    `${dkbColors.fossil} Clear lava for Fragmentones, fossil in lava {28}`,
    `${dkbColors.header} Fragmentone Recovery/Restoration [143]`,
    `${dkbColors.fossil} Near battle {29}`,
    `${dkbColors.banana} Battle: Ground-Gulping Glory [144]`,
    `${dkbColors.banana} Secret by the Shelter [145] GET Quick Storage`,
    `${dkbColors.banana} Battle: Strike like Lightning [146]`,
    `${dkbColors.fossil} In corner of mud platform below large elephant {30}`,
    `${dkbColors.fossil} In mud to left {31}`,
    `${dkbColors.fossil} Liftoff ore up, fossil behind large elephant {32}`,
    `${dkbColors.banana} Halfway to the Station [147]`,
    `${dkbColors.header} Fly to small mud island to left`,
    `${dkbColors.banana} Concealed in the Sky [148]`,
    `${dkbColors.header} Fly to higher island on right`,
    `${dkbColors.banana} Battle: Zip-Line Zones [149]`,
    `${dkbColors.rareFossil} AFAT/dig in large elephant above <3>`,
    `${dkbColors.fossil} On stone in water {33}`,
    `${dkbColors.fossil} In lava blocking zipline {34}`,
    `${dkbColors.header} Jump to next island`,
    `${dkbColors.fossil} In crystals on elephant x2 {36}`,
    `${dkbColors.header} Challenge stage: Sharpshooter Scramble`,
    `${dkbColors.banana} - Slip by the Snipers [150]`,
    `${dkbColors.banana} - Sniper-Free Safe Spot [151]`,
    `${dkbColors.banana} - Scramble through the Snipers [152]`,
    `${dkbColors.banana} Sunk in the Pool [153]`,
    `${dkbColors.fossil} On island in water {37}`,
    `${dkbColors.banana} Shifty Smash: Stormy Skies [154]`,
    `${dkbColors.rareFossil} Under small elephant <4>`,
    `${dkbColors.header} Zipline to next island, break terravoider`,
    `${dkbColors.fossil} In ground/croc below x2 {39}`,
    `${dkbColors.header} Suck liftoff ore, use one`,
    `${dkbColors.banana} In a Floating Puddle [155]`,
    `${dkbColors.banana} Atop Stormy Station [156]`,
    `${dkbColors.fossil} Outside of dome to left {40}`,
    `${dkbColors.fossil} Inside dome on right {41}`,
    `${dkbColors.header} Blusterwing, dive to Landfill`,
    `${dkbColors.header} *Landfill 1`,
    `${dkbColors.quintuple} Freed the Blusterwing! [161] GET Bananergy 3`,
    `${dkbColors.banana} Top of the Heap [162]`,
    `${dkbColors.header} Landfill clip`,
    `${dkbColors.banana} Battle: Explosive Excavation [163]`,
    `${dkbColors.fossil} In dirt near void stake x2 {2}`,
    `${dkbColors.header} Peekabruiser, dive to Racing`,
    `${dkbColors.header} *Racing 1`,
    `${dkbColors.quintuple} Bruised Peekabruiser! Again! [168]`,
    `${dkbColors.banana} Battle: Jumping Jukes [169]`,
    `${dkbColors.banana} Battle: Turf Surf Trampling [170] GET Trunk Room`,
    `${dkbColors.banana} Racing Quiz Master 3-1-3 [171]`,
    `${dkbColors.banana} Cranky's Racing Rant [172]`,
    `${dkbColors.header} Race skip, gold on trophy up to 100k stats (gold: approx 8100)`,
    `${dkbColors.header} Dive to Radiance`,
    `${dkbColors.header} *Radiance 1`,
    `${dkbColors.fossil} Behind start {1}`,
    `${dkbColors.banana} Beneath the White-Sand Landing [173]`,
    `${dkbColors.triple} Alighted in the Radiance Layer! [176]`,
    `${dkbColors.fossil} On wall to left {2}`,
    `${dkbColors.fossil} ON wall behind you while waiting for key {3}`,
    `${dkbColors.header} Kill key croc`,
    `${dkbColors.fossil} In wall/floor towards dead end banana x2 {5}`,
    `${dkbColors.banana} Deep Down in Shedlight Cave [177]`,
    `${dkbColors.header} Dive to SL1201`,
    `${dkbColors.triple} Ssslithered Past Shedlight Cave! [180]`,
    `${dkbColors.banana} Revealed by the Light [181]`,
    `${dkbColors.fossil} On/behind wall at end of glowing vein x2 {7}`,
    `${dkbColors.fossil} In sand near challenge below {8}`,
    `${dkbColors.header} Challenge stage: Dim Lights in the Darkness`,
    `${dkbColors.banana} - Glowing Fruit in the Darkness [182]`,
    `${dkbColors.banana} - Sharp Eye for a Banana [183]`,
    `${dkbColors.banana} - Guided by Glowing Fruit [184]`,
    `${dkbColors.banana} Adrift in Glowboa Grotto [185]`,
    `${dkbColors.fossil} In wall towards elder {9}`,
    `${dkbColors.fossil} In crystal in corner {10}`,
    `${dkbColors.rareFossil} In sand near spider back towards start <1>`,
    `${dkbColors.banana} Battle: Some Light Smashing [186]`,
    `${dkbColors.fossil} On other end of tunnel {11}`,
    `${dkbColors.fossil} Under bridge on the left side of the elder {12}`,
    `${dkbColors.fossil} Throw ball above dark room {13}`,
    `${dkbColors.fossil} In dark room near record piece {14}`,
    `${dkbColors.header} Deliver dark room record piece`,
    `${dkbColors.banana} Bathing in the Essence of the Sun [187]`,
    `${dkbColors.header} Deliver lava record piece`,
    `${dkbColors.fossil} In hill below getaway {15}`,
    `${dkbColors.fossil} In stone behind pi {16}`,
    `${dkbColors.header} Deliver pit record piece, get large chunk behind elder`,
    `${dkbColors.fossil} On top of getaway {17}`,
    `${dkbColors.header} Ride zipline, get record piece`,
    `${dkbColors.banana} Atop an Unlit Landing [188]`,
    `${dkbColors.fossil} In sand below (barrel up after) {18}`,
    `${dkbColors.rareFossil} In sand dune near start of zipline <2>`,
    `${dkbColors.banana} Over the Elder's Head [189]`,
    `${dkbColors.rareFossil} Behind elder's head <3>`,
    `${dkbColors.header} Deliver last record piece, get Snake`,
    `${dkbColors.banana} Sitting on a Snake Head [190] GET Better Charge Jump`,
    `${dkbColors.fossil} On crystal floor {19}`,
    `${dkbColors.fossil} Above challenge {20}`,
    `${dkbColors.header} Challenge stage: Snake Bananza: Charged Climb`,
    `${dkbColors.banana} - Sneaky Room Under Sand [191]`,
    `${dkbColors.banana} - Springing off Sandy Steps [192]`,
    `${dkbColors.banana} - Swift and Shocking Ascent [193]`,
    `${dkbColors.header} Dive to SL1202`,
    `${dkbColors.triple} Unveiled in the Sculptors' Studio! [196]`,
    `${dkbColors.banana} Battle: Shining Through [197]`,
    `${dkbColors.fossil} In crystal towards tower {21}`,
    `${dkbColors.fossil} On right side of ramp {22}`,
    `${dkbColors.fossil} Drop to tower base, fossil in crystal at bottom {23}`,
    `${dkbColors.fossil} In corner of tower {24}`,
    `${dkbColors.banana} Soaking in the Essence of the Sun [198]`,
    `${dkbColors.banana} Warmed by Flaming Barrels [199]`,
    `${dkbColors.banana} Safe in the Barrel-Free Zone [200]`,
    `${dkbColors.fossil} Hit sun switch, fossil behind sun door on left {25}`,
    `${dkbColors.banana} Summited the Solar Control Tower! [201]`,
    `${dkbColors.header} Challenge stage: Arcade Country`,
    `${dkbColors.banana} - Hidden in the Girders [202]`,
    `${dkbColors.banana} - Jumpin' Like Jumpman [203]`,
    `${dkbColors.banana} - Climbing to a High Score [204]`,
    `${dkbColors.banana} Wishing on a Synthetic Sun [205] GET Punch Power 3`,
    `${dkbColors.fossil} Drop towards Poppy door, fossil in sand near door {26}`,
    `${dkbColors.fossil} In croc near door {27}`,
    `${dkbColors.header} Dive to Poppy Kong, dive to SL1203`,
    `${dkbColors.triple} Settled upon Serpent Sands! [208]`,
    `${dkbColors.fossil} On edge of dune {28}`,
    `${dkbColors.fossil} Near terravoider {29}`,
    `${dkbColors.fossil} Break terravoider, fossil on snake behind {30}`,
    `${dkbColors.fossil} In small dune near Bloomintone {31}`,
    `${dkbColors.banana} Bloomed in the Radiance Layer [209]`,
    `${dkbColors.fossil} In Void Kong statue's eyes x2 {33}`,
    `${dkbColors.banana} Battle: Shadow and Sunlight [210]`,
    `${dkbColors.banana} Shifty Smash: Timing is Everything [211]`,
    `${dkbColors.rareFossil} In small dune towards outskirts getaway <4>`,
    `${dkbColors.header} Extra rare fossil in concrete pit`,
    `${dkbColors.fossil} Jump up to crystal snake on edge {34}`,
    `${dkbColors.header} Snake jump/fly to crystal viper`,
    `${dkbColors.banana} Under the Viper's Chinny-Chin-Chin [212]`,
    `${dkbColors.fossil} In crystal wall in viper {35}`,
    `${dkbColors.fossil} In display case in viper {36}`,
    `${dkbColors.banana} Battle: Open the Window [213]`,
    `${dkbColors.rareFossil} In wall under battle <5>`,
    `${dkbColors.header} Jump to set switch to blue`,
    `${dkbColors.fossil} In croc in hall {37}`,
    `${dkbColors.fossil} On concrete wall outside {38}`,
    `${dkbColors.banana} Head in the Shade Clouds [214]`,
    `${dkbColors.rareFossil} In cloud below <6>`,
    `${dkbColors.fossil} Behind getaway {39}`,
    `${dkbColors.banana} Walkin' on Shade Clouds [215]`,
    `${dkbColors.header} Break stone on pillar`,
    `${dkbColors.banana} Pillaged from a Shade-Cloud Pillar [216]`,
    `${dkbColors.fossil} In clouds above x2 {41}`,
    `${dkbColors.header} Dive to SL1204`,
    `${dkbColors.triple} Crashed the Crystal-Cobra Den! [219]`,
    `${dkbColors.header} Get/finish crystal smashin' stats`,
    `${dkbColors.header} Challenge stage: Strong, Shady Clouds`,
    `${dkbColors.banana} - Hidden in the Moving Wall [220] GET Health 3`,
    `${dkbColors.banana} - Sticking to the Shadows [221]`,
    `${dkbColors.banana} - Through Shadows and Thorns [222]`,
    `${dkbColors.fossil} In crystal x2 {43}`,
    `${dkbColors.banana} Swallowed by the Snake [223]`,
    `${dkbColors.header} Grumpy Kong`,
    `${dkbColors.header} *Groove 1`,
    `${dkbColors.header} First Groove clip`,
    `${dkbColors.banana} Deep under Detention [224]`,
    `${dkbColors.fossil} In bomb tunnel on right {1}`,
    `${dkbColors.fossil} After bomb tunnel, before barrel {2}`,
    `${dkbColors.header} Barrel up, second Groove clip`,
    `${dkbColors.fossil} In gold wallopoid {3}`,
    `${dkbColors.fossil} In wallopoids on right x2 {5}`,
    `${dkbColors.banana} Lofty Melody [225]`,
    `${dkbColors.fossil} Harp, fossil in gold wallopoid on left {6}`,
    `${dkbColors.header} Harp behind gold wallopoid, break terravoider`,
    `${dkbColors.fossil} In concrete in terravoider room x2 {8}`,
    `${dkbColors.fossil} Gold in water below melody source {9}`,
    `${dkbColors.fossil} Gold in right side of tunnel before rubber wall {10}`,
    `${dkbColors.header} Harp on other side of rubber wall`,
    `${dkbColors.banana} A Gift from a Fan [226]`,
    `${dkbColors.banana} The Catchy Melody is Back [227]`,
    `${dkbColors.fossil} In gold floor {11}`,
    `${dkbColors.header} Break gold door leading to puzzle room on right`,
    `${dkbColors.header} Harmoneel to Feast`,
    `${dkbColors.header} *Feast 1`,
    
  ]
};
