import type { Route } from "../../classes/Route";
import { dkbColors, titleColors } from "../../utils/colors";

export const dkbAny: Route = {
  title: "Bananza Any% (Snakeless)",
  headerColor: titleColors.dkb,
  doc: "https://www.youtube.com/watch?v=6nn5E3orTPI",
  steps: [
    `${dkbColors.header} Note: Need 2,999 gold before Hilltop Constructone`,
    `${dkbColors.header} Note: Skip all cutscenes by holding - and mashing +`,
    `${dkbColors.header} Note: This route assumes AFAT and AAC knowledge. Mashing makes your life easier but isn't necessary.`,
    `${dkbColors.header} *Ingot Isle`,
    `${dkbColors.header} Punch through/down walls`,
    `${dkbColors.header} Dive punch first switch (skip cs for smashin' stats)`,
    `${dkbColors.header} Grab rock, swing at gold geyser to left, continue`,
    `${dkbColors.header} Dive punch second switch (skip cs for smashin' stats)`,
    `${dkbColors.header} Break gold up hill`,
    `${dkbColors.header} Through collapsed tunnel`,
    `${dkbColors.header} Grab chunk, surf left over thorns`,
    `${dkbColors.header} AFAT up ledge to hit checkpoint`,
    `${dkbColors.header} Surf right, drop to odd rock`,
    `${dkbColors.header} Through tunnel to make music`,
    `${dkbColors.header} Make friends, - to warp to checkpoint "Baboomtown Entrance"`,
    `${dkbColors.header} Surf forward/right, climb to barrels (get gold)`,
    `${dkbColors.header} Note: Should have 100,000 Stone smashin' stats by now. If not, can break some stone at top`,
    `${dkbColors.header} Roll punch croc, break stake, dive`,
    `${dkbColors.header} *Lagoon Layer`,
    `${dkbColors.header} Surf following right side, drop right to break stake`,
    `${dkbColors.header} Dive, surf back/right through town`,
    `${dkbColors.header} Cross bridge`,
    `${dkbColors.header} Left to record, deliver record, get Kong`,
    `${dkbColors.header} Surf through door, break gold geysers and concrete wall`,
    `${dkbColors.header} Climb left wall, punch through, break stake`,
    `${dkbColors.header} Optional: get balloon barrel by 3x banana for safety`,
    `${dkbColors.header} Break gold, cross gap`,
    `${dkbColors.header} Peekabruiser: Kong, surf right, throw boom rock, throw chunk`,
    `${dkbColors.header} Dive (break rocks for gold between layers, but only this time)`,
    `${dkbColors.header} *Hilltop Layer`,
    `${dkbColors.five} Optional: Get 5x banana for more bananergy or health if desired [5]`,
    `${dkbColors.header} Open Smashin' Stats menu upon landing (can frame perfect skip zoom when landing. Ideally 900 gold)`,
    `${dkbColors.header} Surf straight ahead to Peel Peak, climb, break terravoider`,
    `${dkbColors.header} Surf down banana to Constructone and pay it`,
    `${dkbColors.header} Dive, surf w/concrete, break stake, dive`,
    `${dkbColors.header} *Canyon Layer`,
    `${dkbColors.header} Surf through tunnel, run into Squeeloids to break concrete`,
    `${dkbColors.header} Minecart to town, surf left to skip everything`,
    `${dkbColors.header} Optional: hit town checkpoint for safety`,
    `${dkbColors.header} Throw gold chunk at top of town smokestack`,
    `${dkbColors.header} Slap sand and immediately grab chunk`,
    `${dkbColors.header} Canyon clip`,
    `${dkbColors.header} Grab chunk and rail AFAT to far right smokestack, dive in`,
    `${dkbColors.header} Stompenclomper: Kong, chunk jump/roll punch, phase 2 grab hair gold/throw`,
    `${dkbColors.header} Dive`,
    `${dkbColors.header} *Divide Layer`,
    `${dkbColors.header} Surf right to break Forest stake, dive`,
    `${dkbColors.header} *Forest Layer`,
    `${dkbColors.header} Surf right over poison, fall and surf directly across to ostrich head near egg hotel`,
    `${dkbColors.header} Jump in egg hotel window, break terravoider`,
    `${dkbColors.header} AFAT up with first record piece, throw to top, grab second record piece, cannon to top`,
    `${dkbColors.header} (Alternative: Cannon up to deliver first piece, then drop to second piece)`,
    `${dkbColors.header} Deliver record pieces, get Ostrich`,
    `${dkbColors.header} Surf right, drop to key, break stake, dive`,
    `${dkbColors.header} Surf forward to first poison plant`,
    `${dkbColors.header} Surf back right/flutter stall to second poison plant`,
    `${dkbColors.header} Flutter stall past annex to third poison plant`,
    `${dkbColors.header} Drop to break stake, dive`,
    `${dkbColors.header} Surf forward, get appy juice left of root`,
    `${dkbColors.header} Get on stump, punch down 3 times, charge punch forward through egg/thorns`,
    `${dkbColors.header} Abracajabya: Surf/flutter stall forward, then right, then back across to the left`,
    `${dkbColors.header} Dive`,
    `${dkbColors.header} *Junction Layer`,
    `${dkbColors.five} Get 5x bananas, unlock glide 1 [10]`,
    `${dkbColors.header} Flutter stall to center island, AFAT/flutter stall across gap`,
    `${dkbColors.header} (Alternative: drop to break Forest terravoider to make gap cross easier)`,
    `${dkbColors.header} - to warp gong, to Hilltop`,
    `${dkbColors.header} Void 1: Throw chunk before fight cutscene, throw chunks ahead before he moves, surf up + throw`,
    `${dkbColors.header} - to warp gong, to Lagoon`,
    `${dkbColors.header} Void 2: Punch wagon, surf left, throw chunk, surf over thorns, punch`,
    `${dkbColors.header} - to warp gong, to Junction`,
    `${dkbColors.header} Void 3: Surf ahead (hit x3 before shield), break terravoiders, smash`,
    `${dkbColors.header} AFAT (or flutter stall, or cannon) to dive`,
    `${dkbColors.header} *Resort Layer`,
    `${dkbColors.header} Surf to 2nd trailfinoid, punch it towards melon tower`,
    `${dkbColors.header} Rise with liftoff ore, flutter stall to melon`,
    `${dkbColors.header} Punch through, break stake, dive`,
    `${dkbColors.header} *Tempest Layer`,
    `${dkbColors.header} Surf forward, drop to lava, surf forward, break terravoider`,
    `${dkbColors.header} Blusterwing 1: Kong, throw chunks`,
    `${dkbColors.header} Dive, flutter stall left to record piece, flutter stall back to center, throw piece to cannon`,
    `${dkbColors.header} Drop right to 2nd record piece, cannon up`,
    `${dkbColors.header} Juggle record pieces up the layer to deliver them, get Elephant`,
    `${dkbColors.header} (Alternative: deliver record pieces individually)`,
    `${dkbColors.header} - to warp to Hot-Shower Cave`,
    `${dkbColors.header} Surf back left, suck lava to tornado, suck key`,
    `${dkbColors.header} Surf to break stake, dive`,
    `${dkbColors.header} Blusterwing 2: Have chunks ahead of time or suck chunks to throw`,
    `${dkbColors.header} Dive, surf forward through tunnel, cross gap`,
    `${dkbColors.header} AFAT/flutter stall straight ahead, following right islands`,
    `${dkbColors.header} Suck through mud to get some liftoff ore`,
    `${dkbColors.header} Flutter stall forward until long zipline, grab rock to follow zipline`,
    `${dkbColors.header} Rise with liftoff ore, dive`,
    `${dkbColors.header} (Optional: if liftoff ore is still needed, use zipline rock to jump right to break terravoider)`,
    `${dkbColors.header} Blusterwing 3: Have chunks ahead of time (or have a bad time)`,
    `${dkbColors.header} Dive`,
    `${dkbColors.header} *Landfill Layer`,
    `${dkbColors.header} Surf forward/right, chunk jump to outcropping`,
    `${dkbColors.header} Climb to Landfill clip point, drop down to floor`,
    `${dkbColors.header} Drop below for ~5 seconds or until you see the Constructone room`,
    `${dkbColors.header} Smash straight forward/right to break stake, dive`,
    `${dkbColors.header} Peekabruiser: Suck w/Elephant`,
    `${dkbColors.header} Dive`,
    `${dkbColors.header} *Racing Layer`,
    `${dkbColors.header} Surf forward, flutter stall to raceway, cross to far raceway`,
    `${dkbColors.header} Suck liftoff ore x2, rise to trophy top`,
    `${dkbColors.header} Break stake, dive`,
    `${dkbColors.header} *Radiance Layer`,
    `${dkbColors.header} Surf around corner, lure croc to stake, break croc and stake, dive`,
    `${dkbColors.header} AFAT/flutter stall left to stake, AFAT to key, break stake, dive`,
    `${dkbColors.header} Surf ahead, drop to tower entrance`,
    `${dkbColors.header} Climb tower (AFATs/Elefats or chunk jump like crazy)`,
    `${dkbColors.header} Break terravoider, cannon up, suck liftoff ore, break croc, hit switch`,
    `${dkbColors.header} Surf out and down/right, drop through light gate`,
    `${dkbColors.header} Poppy: Kong, throw chunks at reticle/purple mist`,
    `${dkbColors.header} Dive, surf forward, flutter stall left at gold root`,
    `${dkbColors.header} Cross gap to square, use liftoff ore to turn it into clouds`,
    `${dkbColors.header} Break stake, dive, break crystal, dive`,
    `${dkbColors.header} Grumpy: Kong, jump on top, break ceiling, avoid pickaxe`,
    `${dkbColors.header} *Groove Layer`,
    `${dkbColors.header} Punch down, through tunnel, first clip`,
    `${dkbColors.header} Straight ahead, climb up (use gold to surf), back left toward melody hall`,
    `${dkbColors.header} Second clip, surf to end, chunk jump to break terravoider`,
    `${dkbColors.header} Secret tunnel (2nd option for 2nd dialogue)`,
    `${dkbColors.header} Drop down, Z-shape (hit harp halfway)`,
    `${dkbColors.header} Talk to Poppy, barrel inside Harmoneel`,
    `${dkbColors.header} Dive punch to free Pauline`,
    `${dkbColors.header} *Feast Layer`,
    `${dkbColors.header} Elephant, suck sand, flutter stall right over gap to slime tower`,
    `${dkbColors.header} Flutter stall/jump forward/right to oil cruise`,
    `${dkbColors.header} Smack ground/grab chunk at dirt, burger skip, flutter stall ahead`,
    `${dkbColors.header} (Can land in-bounds at boss or above boss, whichever feels safer)`,
    `${dkbColors.header} Muck: Use Elephant sand/Kong punches to skip phases`,
    `${dkbColors.header} Dive`,
    `${dkbColors.header} *Forbidden Layer`,
    `${dkbColors.header} Surf forward, Kong, drop left to punch wall, continue to edge`,
    `${dkbColors.header} Flutter stall forward across gaps`,
    `${dkbColors.header} Punch gold/use concrete chunks to break concrete walls`,
    `${dkbColors.header} Flutter stall across to Void`,
    `${dkbColors.header} Void 4: Surf forward, throw chunk left, throw chunk right, surf past Void`,
    `${dkbColors.header} Break terravoiders, smash, dive after K. Rool (gasp!)`,
    `${dkbColors.header} *Planet Core`,
    `${dkbColors.header} 1: Surf forward (tilt in direction minecart is going)`,
    `${dkbColors.header} 2: Surf forward`,
    `${dkbColors.header} 3: Surf forward, flutter stall across`,
    `${dkbColors.header} 4: AFAT to skip switcheroo goo`,
    `${dkbColors.header} 5: Flutter stall between thorns, drop down right after`,
    `${dkbColors.header} 6: Surf forward over gaps, cannon to boss`,
    `${dkbColors.header} K. Stompenclomper: Same tactics as last time, just avoid lava`,
    `${dkbColors.header} 7: Surf forward (throw boom rock at last batteroid)`,
    `${dkbColors.header} 8: SURF. Swing to break gold`,
    `${dkbColors.header} 9: Suck some gold, fight everything`,
    `${dkbColors.header} 10: Flutter stall across over ball`,
    `${dkbColors.header} K. Rool 1: Mash if you can. Hit ball back, surf to catch up after jumps`,
    `${dkbColors.header} Make wish, throw bananas at K. Rool`,
    `${dkbColors.header} *Surface`,
    `${dkbColors.header} Suck banana goo, flutter stall across`,
    `${dkbColors.header} Climb, flutter stall over everything`,
    `${dkbColors.header} Flutter stall left, climb to Murder Bridges TM`,
    `${dkbColors.header} Flutter stall, land/regrab, cannon`,
    `${dkbColors.header} Throw gold at goo snakes, grab gold, re-flutter`,
    `${dkbColors.header} K. Rool 2: Same stuff as K. Rool 1 but more`,
    `${dkbColors.header} *GG!`
  ]
};
