import type { Route } from "../../classes/Route";
import { dkbColors, titleColors } from "../../utils/colors";

export const dkbTrueEnding: Route = {
  title: "True Ending (Snakeless)",
  headerColor: titleColors.dkb,
  doc: "https://docs.google.com/document/d/124SsIzn3BrDvcCP82NsLqjuJ1hZcTnCchBMIbsFEabA",
  steps: [
    `${dkbColors.header} Note: This route is snakeless but can very easily be modified to include snake. Just get snake when you reach it in Radiance 1.`,
    `${dkbColors.header} *Ingot Isle 1`,
    `${dkbColors.banana} The First Banandium Gem [1]`,
    `${dkbColors.banana} Through the Banana-Mining Belt [2]`,
    `${dkbColors.banana} The big pile of dirt before breaking the wall is Digging Up a Snack [3]`,
    `${dkbColors.header} *Lagoon 1`,
    `${dkbColors.triple} First Crockoid Cracked! [6]`,
    `${dkbColors.banana} Dig down a few steps ahead for Cave by the Cape [7], Exit forward`,
    `${dkbColors.banana} Continue forward to the entryway to Bathing Banana [8]`,
    `${dkbColors.banana} Leave and go over hill for Shifty Smash: Beyond the Wall [9]`,
    `${dkbColors.banana} Grab an explosive for Blasting for the Banana [10]`,
    `${dkbColors.header} Turn around and go to the Main Reservoir to open the Void Lock.`,
    `${dkbColors.banana} Chunk Jump up above the new hole to A Real Mouthful [11]`,
    `${dkbColors.banana} Dig straight through and slightly left down for A Nook Behind Concrete [12]`,
    `${dkbColors.banana} Walk out the same way you went in, go up a level for Smash through the Floor [13]`,
    `${dkbColors.banana} Leave and jump up left path to Hangin on Roof Road [16]`,
    `${dkbColors.banana} Fall down the left side to open Lakeside Low Road [17]`,
    `${dkbColors.banana} Up top of this mountain and AFAT jump over to Cranky's Lagoon Rant [18]`,
    `${dkbColors.banana} Across to the pipe inside for Placed in a Pipe [19]`,
    `${dkbColors.banana} Fall straight down the pipe to Rise and Rinse [20]`,
    `${dkbColors.banana} Jump to the right across the gap to Beyond the Cloudy Platforms [21]`,
    `${dkbColors.banana} Jump down right to opening, take right path through to Fishing for Bananas [22]`,
    `${dkbColors.header} Exit the cave and go up the wall, up to the Void Lock.`,
    `${dkbColors.header} *SL 101`,
    `${dkbColors.triple} Hangin on Orangu-Hang Highway [25]`,
    `${dkbColors.banana} Right side of the wall towards the hanging Concrete Wall on the Moving Floor [26]`,
    `${dkbColors.header} Go back where the Triple was, continue down to get the Disk. Get Kong Bananza.`,
    `${dkbColors.header} Proceed to SL102`,
    `${dkbColors.header} *SL102`,
    `${dkbColors.triple} Dipped into Chimpy Channel [29]`,
    `${dkbColors.banana} In first open room, smash through right wall to Shipwrecked Treasure [30]`,
    `${dkbColors.banana} Back to the Challenge Room for 2 Bananas Kong Bananza: Pop Party [32]`,
    `${dkbColors.header} Beat Peekabruiser.`,
    `${dkbColors.header} *Hilltop`,
    `${dkbColors.quintuple} Bruised Peekabruiser! [37]`,
    `${dkbColors.banana} Ahead on the pathway a little bit, dig straight down for Cave-Dwelling Treasure [38]`,
    `${dkbColors.banana} Back up and to the town, go behind it for the Challenge Room Shifty Platform Road [41]`,
    `${dkbColors.banana} Fall to under the town for The Shifty Path Under the Village [42]`,
    `${dkbColors.banana} Take a right from the village to Hilltop Hide-and-Seek [43]`,
    `${dkbColors.banana} Surf past the right side of the town to the concrete hole for Gold-Dipped Banana [44]`,
    `${dkbColors.banana} Leave via Barrel Cannon, straight ahead hanging The Flying Banana [45]`,
    `${dkbColors.banana} Peel Peak middle Banana concrete entranceway for Bananas All the Way Down [46]`,
    `${dkbColors.banana} Roll Punch Straight through and up to break the Void Terrain. Go up top for The Skies over Peel Peak [47]`,
    `${dkbColors.banana} Fall down to the newly unlocked Peeled from Peel Peak [48]`,
    `${dkbColors.banana} Down the the Challenge Room at the 1st tip of Peel Peak Banana, Spiked-Tide Slope [51]`,
    `${dkbColors.banana} Head to the Paywall, bloom the flower first Bloomed in the Hilltop Layer [52]`,
    `${dkbColors.banana} Get reward for Smashin Hilltop Smashin' Stats [53]`,
    `${dkbColors.banana} Paywall 3000g, Right side of the hole on the way down, Tunneling through the Pit [54]`,
    `${dkbColors.banana} Challenge Room Nostalgia Country [57]`,
    `${dkbColors.header} *Canyon 1`,
    `${dkbColors.triple} Tumbled into the Canyon Layer! [60]`,
    `${dkbColors.banana} Behind, dig at the edge of the room, continue outside for Behind Tallfall Cliffs [61]`,
    `${dkbColors.banana} Go back inside, ahead is Hanging in the Cliffs [62]`,
    `${dkbColors.header} Barrel Cannon up, go ahead to Minecart room, but dig a floor below.`,
    `${dkbColors.banana} Behind the Pillar here is Buried in the Cliffs [63]`,
    `${dkbColors.banana} Going up, top of the cliff right on the edge before the Cart Track Growing from the Stone Wall [64]`,
    `${dkbColors.header} Grab a large chunk, surf down rail and first building on the right`,
    `${dkbColors.banana} Floor below for Unfiltered Potassium [65]`,
    `${dkbColors.banana} Towards town, first cliffside after a gap, dig and down for Pay Dirt Under the Plateau [66]`,
    `${dkbColors.banana} Exit out the right wall to Stuck in a Side Cave [67]`,
    `${dkbColors.header} Continue to the other side of the cliff, forward over a gap`,
    `${dkbColors.banana} Into next cliffside for Challenge Room Thorny Blast Cave [70]`,
    `${dkbColors.banana} Straight across from the Challenge, dig to find the horizontal pipe, follow it in for An Underground Guide [71]`,
    `${dkbColors.banana} Forward through the pipe till Traversing the Cliff [72]`,
    `${dkbColors.banana} Take barrel cannon up, to the right inside Spinning in the Stone Pillar [73]`,
    `${dkbColors.banana} Left out to middle of village for the freestanding Moseyed into the Village [74]`,
    `${dkbColors.banana} Stuff Shop House, AFAT up to top of pillar and go down for Surveying the Staff Dorms [75]`,
    `${dkbColors.banana} Back up the pillar, behind to round platform with a bump. Dig down for Unplundered Produce [76]`,
    `${dkbColors.banana} Left of the Exit of this room to in between pipes in Under Town area, in the water first Sunken and Soaking [77]`,
    `${dkbColors.banana} Top ledge right above is High Shelf Down Below [78]`,
    `${dkbColors.banana} Across to get all Fragmentones Recovered into Puzzle Guy Canyon Fragmentone Recovery Restoration [80]`,
    `${dkbColors.banana} Dig in wall right behind grating to Sparkling in the Secret Storeroom [81]`,
    `${dkbColors.header} Barrel Cannon up into the house, get on top floor to break Void Terrain`,
    `${dkbColors.banana} Then dig one floor below for Banandium Gem in the House [82]`,
    `${dkbColors.banana} Exit house and up for Unstuck the Minecart [83]`,
    `${dkbColors.banana} Canyon Skip, up to two Gems (1000g) from the Canyon Growtone [85]`,
    `${dkbColors.banana} Up to big crane platform, in the corner digging is Hanging from the Crane [86]`,
    `${dkbColors.banana} Up on the next side to Slip into the Secret Room [87]`,
    `${dkbColors.header} Grab Checkpoint`,
    `${dkbColors.banana} Top platform of the climb, other side for Concrete crate has The Crane's Precious Cargo [88]`,
    `${dkbColors.banana} Fall down to Above the Moving Walls [89]`,
    `${dkbColors.banana} Go left to Behind the Moving Walls [90]`,
    `${dkbColors.banana} Fall down to bottom of final pillar, Bust Through the Giraffe's Spot [91], warp back up`,
    `${dkbColors.triple} Finish the climb though the Void Lock, Dropped into the Refinery's Depths [94]`,
    `${dkbColors.header} *Divide`,
    `${dkbColors.quintuple} 5 pack Stomped Stompenclomper! [99] Cranky on the way to Forest for a quick backup.`,
    `${dkbColors.header} *Forest`,
    `${dkbColors.triple} Triple, Branched into the Forest Layer! [102]`,
    `${dkbColors.banana} Left side tree, up a level to the hidden in grass Perched Where the Branches Cross [103]`,
    `${dkbColors.banana} Continue up to the higher platform with the hanging banana Shifting above the Forest [104]`,
    `${dkbColors.banana} Banana right underneath, fall to View from Featherfall Isle [105]`,
    `${dkbColors.banana} Down left to Featherfall Isle, below the grass in the sand Under Featherfall Isle [106]`,
    `${dkbColors.banana} Surf Surf straight through the poison, down the waterfall edge to The Ostritch's Back Snack [107]`,
    `${dkbColors.header} Climb the tree, break the concrete and unlock the Void Terrain.`,
    `${dkbColors.banana} Fall to the base of the tree, go down and left side over the thorns to grab Tucked in Thorn Hollow [108]`,
    `${dkbColors.banana} Climb out. Straight ahead is A Pain in the Neck [109]`,
    `${dkbColors.banana} Continue forward (towards the Hotel) and behind the tree with purple thorns is Behind the Big Tree [110]`,
    `${dkbColors.header} Climb this tree 2 floors up.`,
    `${dkbColors.banana} Break the wall where the Ostrich is clapping for Sleeping in the Big Tree [111]`,
    `${dkbColors.banana} Very top of this tree, on top of the ostrich head is Glimmering Overhead [112]`,
    `${dkbColors.banana} Fly Down to offshoot from the hotel is Present by the Pool [113]`,
    `${dkbColors.header} In the hotel, go right and then down a floor to juggle discs`,
    `${dkbColors.banana} Turn around after getting ostrich for Checked in at the Eggshell Hotel [114]`,
    `${dkbColors.banana} Outside and down a floor, grab a nut on the left side to make a pathway to grab Hangin in the Lounge [115]`,
    `${dkbColors.banana} Down and ahead for Lounge Lost and Found [116]`,
    `${dkbColors.header} *SL 601`,
    `${dkbColors.triple} Triple, Plummeted to Mossplume Marsh [119]`,
    `${dkbColors.header} Continue forward past the broken Egg House to the Shifty Smash. Complete it, but go break the Poison Bulb first.`,
    `${dkbColors.banana} Return to the Shifty Smash platform, underneath for Beneath the Moving Platforms [120]`,
    `${dkbColors.banana} Up to the reward for Shifty Smash: Thwarting the Thorns [121]`,
    `${dkbColors.banana} Left to the blue egg down a level for the ostrich Challenge Room Ostrich Bananza: Flighty Feast [124]`,
    `${dkbColors.banana} Straight ahead from challenge room, Bounced into Rubbery Roost [125]`,
    `${dkbColors.banana} To the left, higher platforms up to Bouncing to the Top [126]`,
    `${dkbColors.header} Continue to the second Poison Bulb with a Dive Punch bounce and flutter stall glide.`,
    `${dkbColors.banana} Left area of the houses, hanging is Hangin in the Annex [127]`,
    `${dkbColors.banana} Forward, just past and under the first rubbery platform is Under the Rubber Pillar [128]`,
    `${dkbColors.banana} Forward again at the next solid ground area is Beyond Rubbery Roost [129]`,
    `${dkbColors.header} Get 3rd bulb`,
    `${dkbColors.banana} Go back to starting big stump for Stuck in the Stump [130]`,
    `${dkbColors.banana} Dig down for Secret in the Marsh [131]`,
    `${dkbColors.header} *SL602`,
    `${dkbColors.triple} Triple, Waded into Bramblenest Bog [134]`,
    `${dkbColors.banana} Turn right for two (1500g) from Forest Growtone [136]`,
    `${dkbColors.banana} The one you can see from the Growtone, fly to Dazzling Ostrich Headwear [137]`,
    `${dkbColors.header} Left two whole islands to the Tree with the Ostrich head.`,
    `${dkbColors.banana} Inside the front of the tree for Nestled Inside the Roots [138]`,
    `${dkbColors.header} Go to stump and defeat Abracajabya`,
    `${dkbColors.banana} After the boss, fall to the left side for Roosted in a Thorny Nest [139]`,
    `${dkbColors.header} *Junction`,
    `${dkbColors.banana} Balloon strat with terravoider. Head back up to the top for Forest Path's Birdbrain [140]`,
    `${dkbColors.quintuple} Go forward for the 5 pack Uprooted Abracajabya [145]`,
    `${dkbColors.banana} Go forward and fall over the edge at the checkpoint for underneath Forest Path's Hidden Snack [146]`,
    `${dkbColors.header} Open Clash Point Checkpoint, Trigger the Void fights.`,
    `${dkbColors.banana} After, get check point, Reset Terrain, warp back to Clash Point. Left is Cleared the Way to Clash Point [147]`,
    `${dkbColors.banana} Back side of the wall, in alcove for Clash Point's Hidden Snack [148]`,
    `${dkbColors.banana} Freezer Path, down path first, secret at the bottom of the slope Freezer Path's Hidden Snack [149]`,
    `${dkbColors.quintuple} Go up to the main Freezer path, 5 Pack Cooled Off Inflammonite [154]`,
    `${dkbColors.banana} Top of Freezer path in the snow Freezer Path's Special Scoop [155]`,
    `${dkbColors.header} *Resort`,
    `${dkbColors.quintuple} 5 Pack Drove Off Void Kong [160]`,
    `${dkbColors.banana} Walk up and left to the hilltop, dig down for Buried in the Beach [161]`,
    `${dkbColors.banana} Head to the right, floating island with the strawberry. Dig in for Strawberry and Banana [162]`,
    `${dkbColors.banana} Go towards the town open banana and checkpoint, Checking into the Tropical Retreat [163]`,
    `${dkbColors.banana} Enter orange fruit and the cave for both bananas [165]. Warp to gong/checkpoint`,
    `${dkbColors.banana} Smash straight through the cliffside, just to the right of the Collectone for Secret Beachside Grotto [166]`,
    `${dkbColors.banana} Go straight outside, and climb to the top of the cliff. Break the strawberry across from the Fragmentone for Resort Fragmentone Recovery [167]`,
    `${dkbColors.banana} Grab Liftoff Ore to Growtone for two bananas (2000g) Resort Growtone [169]`,
    `${dkbColors.banana} Ostrich fly to the right of Growtone to small island with Floating Freebie [170]`,
    `${dkbColors.banana} Fall down towards center pillar, but grab Shifty Smash: Liftoff to the Sky [171]`,
    `${dkbColors.banana} Center Pillar for Challenge Room Switch-Lane Skyway [174]`,
    `${dkbColors.banana} Take Liftoff Ore Fish up to the Banana-Shaped island above for Down from Skydive Isle [175]`,
    `${dkbColors.header} *Tempest 1`,
    `${dkbColors.triple} Triple Stormed in the Tempest [178]`,
    `${dkbColors.triple} Blusterwing 1, then down for 3 pack Beat Sinister Blusterwing [181]`,
    `${dkbColors.banana} Jump up or take the Rising/Weighted Platform for Safe from the Scalding Showers [182]`,
    `${dkbColors.banana} Juggle discs. Surf back to hole, right side inhale lava for Lava Bath in the Hot Shower [183]`,
    `${dkbColors.header} Right side, down the rail to get the key from the tornado.`,
    `${dkbColors.banana} Go past it for the Challenge Room Elephant Bananza: Heating Up [186]`,
    `${dkbColors.header} Open the Void Lock and beat Blusterwing 2.`,
    `${dkbColors.header} *SL902`,
    `${dkbColors.triple} Get Triple Beat Sinister Blusterwing Again [189]`,
    `${dkbColors.banana} Destroy left seekertone first, then get to hanging banana Taunting Behind the Tap [190]`,
    `${dkbColors.banana} Find other 3 seeker tones for Hide and Seek Banana [191]`,
    `${dkbColors.banana} Left higher ledge for Sitting above the Sauna [192]`,
    `${dkbColors.banana} Fall and back to the front of the room, right exitway to find Cranky's Tempest Rant [193]`,
    `${dkbColors.banana} Up the ladder and straight ahead to the Shifty Smash: Scorching Sauna [194]`,
    `${dkbColors.banana} Exit towards outside on the right, up to the top of the steps for Taking in the Stormy Scenery [195]`,
    `${dkbColors.banana} Hop down to the elephant nose Stuck in the Elephant Snout [196]`,
    `${dkbColors.banana} Down to right Lava island, suck up lava off the only small platform to reveal Inhaling Hot Lava [197]`,
    `${dkbColors.banana} Suck lava ahead and climb the wall, up to Shifty Smash: Stairs in the Storm [198]`,
    `${dkbColors.banana} Fly directly across, the Challenge Room on the ledge Hot-Lava Hotfoot [201]`,
    `${dkbColors.banana} Next small pathway with Lava, suck it up for Scorching, Shocking Scaffolds [202]`,
    `${dkbColors.header} Jump up to the top of the next Island`,
    `${dkbColors.banana} Very top under the first Umbrella on the right, dig down for Among the Rocky Elephants [203]`,
    `${dkbColors.banana} Dig out and fall to the Big-Roof Shelter Checkpoint. Banana stuck in the wall Safe Under Shelter [204]`,
    `${dkbColors.banana} Right in front of the little pool, Elephant Suck underground for Banana in the Mud Bath [205]`,
    `${dkbColors.banana} Cross the small gap on the other side of the checkpoint, Dig into the wall for Secret by the Shelter [206]`,
    `${dkbColors.banana} Climb and Elephant Liftoff Ore for Halfway to the Station [207]`,
    `${dkbColors.banana} Fly across to the small island for Concealed in the Sky [208]`,
    `${dkbColors.banana} Fly to next island, in the water near the start is Sunk in the Pool [209]`,
    `${dkbColors.banana} Continue forward to the land, make a right for, Suck up some Liftoff Ore during Shifty Smash: Stormy Skies [210]`,
    `${dkbColors.banana} Cross to final Island with the rail and left higher up ledge for a banana In a Floating Puddle [211]`,
    `${dkbColors.banana} Liftoff Orb to the very top of the orb for Atop Stormy Station [212]. Blusterwing 3.`,
    `${dkbColors.header} *Landfill`,
    `${dkbColors.quintuple} 5 Pack Freed the Blusterwing [217]`,
    `${dkbColors.banana} Make a map pin underground on the small broken banana structure. Climb the walls to get Top of the Heap [218]`,
    `${dkbColors.banana} Out of Bounds, follow the pin and dig back inbounds to Buried in Rubble [219]`,
    `${dkbColors.banana} Right around the corner of the pipe, Elephant to suck up dirt for Up and Down, Underground [220]`,
    `${dkbColors.banana} Away from the pipe for the Shifty Smash: Dig Deep [221]`,
    `${dkbColors.banana} Jump back down to where the barrel was, go left and down to find Caged by a Hungry Guard [222]`,
    `${dkbColors.banana} Dig on the guard's right and suck dirt up to find both Landfill Fragmentones [224]`,
    `${dkbColors.banana} Forward and down, and right slghtly from Fragmentone platform to Nestled within the Debris [225]`,
    `${dkbColors.banana} Straight down to the town, dig in the wall beside the Teeleport Eel, straight to A Rare Treasure [226]`,
    `${dkbColors.banana} Back to town and jump up above Shops for Landill Smashin Stats [227]`,
    `${dkbColors.banana} Suck below shop Follow the Crystal Vein [228]`,
    `${dkbColors.header} Defeat Peekabruiser.`,
    `${dkbColors.header} *Racing`,
    `${dkbColors.quintuple} 5 Pack Bruised Peekabruiser Again [233]`,
    `${dkbColors.banana} Jump and Fly to the left island for the freestanding Viewing the Track from the Back [234]`,
    `${dkbColors.header} Fly back to the track, Liftoff Orb to fly to the end of the layer.`,
    `${dkbColors.header} *Radiance`,
    `${dkbColors.banana} Dig straight down at the start for Beneath the White-Sand Landing [235]`,
    `${dkbColors.triple} Roll Punch up to the triple Alighted in the Radiance Layer [238]`,
    `${dkbColors.header} Go to the Void Lock, and kill the enemy for the key.`,
    `${dkbColors.banana} Detour to the forward pathway for Deep Down in Shedlight Cave [239]`,
    `${dkbColors.header} *SL1201`,
    `${dkbColors.triple} Unlock the key, dive down for the Triple Ssslithered Past Shedlight Cave [242]`,
    `${dkbColors.banana} Throw a Light Chunk and open the door to the right Revealed by the Light [243]`,
    `${dkbColors.banana} Jump down below to enter the Challenge Room Dim Lights in the Darkness [246]`,
    `${dkbColors.banana} To the right, in the snow pile between two scorpions Adrift in Glowboa Grotto [247]`,
    `${dkbColors.header} Fly to the key to the next sublayer.`,
    `${dkbColors.header} *SL1202`,
    `${dkbColors.banana} Turn around and smash crystal for Perfectly Preserved In Crystal [248]`,
    `${dkbColors.banana} Continue forward down the hole in the next crystal. Snake and Ostrich in the hidden room to find Ceiling Swingin Snack [249]`,
    `${dkbColors.triple} Back up and grab the Triple Unveiled in the Sculptors' Studio [252]`,
    `${dkbColors.banana} Head into the tower, Elephant suck the lava in the left corner for Soaking in the Essence of the Sun [253]`,
    `${dkbColors.banana} Climb to get Warmed by the Flaming Barrels [254]`,
    `${dkbColors.banana} Go around the tower climb, behind the four flaming barrels, Glare and find Safe in the Barrel-Free Zone [255]`,
    `${dkbColors.banana} Finish the tower and turn on the layer's lights.`,
    `${dkbColors.banana} As you exit the tower, grab Summited the Solar Control Tower [256]`,
    `${dkbColors.banana} Challenge Room to the right Arcade Country [259]`,
    `${dkbColors.header} Elephant absorb some Light Rock.`,
    `${dkbColors.banana} High bounce to the top of this tower roof for Wishing on a Synthetic Sun [260]`,
    `${dkbColors.header} Jump down the newly unlocked door at the bottom for the Poppy fight.`,
    `${dkbColors.header} *SL1203`,
    `${dkbColors.triple} Triple Settled upon Serpent Sands [263]`,
    `${dkbColors.banana} Dig down the snow and glide over to the high up ledge for Obssscured in a Dune Cave Nook [264]`,
    `${dkbColors.banana} Ledge to the right, Elephant through and get to the end of the hall for Deep in a Dune Cave Hallway [265]`,
    `${dkbColors.banana} Return to the surface with the barrel cannon. To the right is concrete to destroy for Bloomed in the Radiance Layer [266]`,
    `${dkbColors.banana} Right of Void Head sculpture for Shifty Smash: TIming is Everything [267]`,
    `${dkbColors.banana} Back to the middle of the layer, enter the inside and Snake up to Hanging Out beneath the Oasis [268]`,
    `${dkbColors.header} Head up to the oasis, on top of the Ice Snake, break the Void Terrain inside the head.`,
    `${dkbColors.banana} Then the tip of the nose for Tip o the Stone Snake's Tongue [269]`,
    `${dkbColors.banana} Jump back down, and on the other side of the underneath is the banana stuck in the ceiling Grown beneath the Growtone [270]`,
    `${dkbColors.banana} Snake Jump straight up through for two (2000g) Radiance Growtones [272]`,
    `${dkbColors.header} Continue towards light bridge (Backup Cranky on the archway)`,
    `${dkbColors.banana} Get under the First higher ledge Under the Viper's Chinny-Chin-Chin [273]`,
    `${dkbColors.banana} Fly to highest pillar of next area for Pillaged from a Shade-Cloud Pillar [274]`,
    `${dkbColors.banana} Go back for lower pillar for Head in the Shade Clouds [275]`,
    `${dkbColors.banana} Fly to breakable pillar and break it. Fly to get the hanging banana on the right Walkin on Shade Clouds [276]`,
    `${dkbColors.triple} Progress and break the Void Lock. Triple Crashed the Crystal-Cobra Den [279]`,
    `${dkbColors.banana} Challenge room to the left Strong, Shady Clouds [282]`,
    `${dkbColors.banana} Opposite side of the room, break the crystal for Swallowed by the Snake [283]`,
    `${dkbColors.header} Fight Grumpy and finish Radiance.`,
    `${dkbColors.header} *Groove`,
    `${dkbColors.banana} Groove Clip and take Deep under Detention [284]`,
    `${dkbColors.banana} 2nd groove clip, take the fifth right, break the Wallpaloid and above is Lofty Melody [285]`,
    `${dkbColors.header} Continue forward to unlock the Void Terrain, open the Melody`,
    `${dkbColors.banana} In the Tunnel, to the left of the Harp underground A Gift from a Fan [286]`,
    `${dkbColors.banana} Continue through for The Catchy Melody is Back [287] and finish the layer.`,
    `${dkbColors.header} *Feast`,
    `${dkbColors.banana} Fly to Up through the Layer of Muck [288]`,
    `${dkbColors.banana} Immediately fly up and across to the Banana beside the Warp Gong, A Slime-Slathered Treat [289]`,
    `${dkbColors.banana} Bottom floor of the storeroom house right in front of you Snacking from the Stockroom [290]`,
    `${dkbColors.banana} Exit right and go through the wall past the slime (just break the wall around it) for A Banana among Friends [291]`,
    `${dkbColors.banana} Fly back to mainland and into the blue water pool A Soda-infused Banana [292]`,
    `${dkbColors.banana} Hop down to the Growtone, buy a single Banana (500g) The Feast Growtone [293]`,
    `${dkbColors.banana} Enter the Challenge Room left of the growtone, Steady Flow of Salt [296]`,
    `${dkbColors.header} Go down to the right side pathway till nearly the bottom, but still on the green path`,
    `${dkbColors.banana} Break the Wallopoid, break Void Terrain for Danger Doubling Back [297]`,
    `${dkbColors.banana} Break out straight through the right wall to Shifty Smash: Huge Monument [298]`,
    `${dkbColors.banana} Snake Jump to the Lion's Mouth right behind the monument Eating the Lion's Share [299]`,
    `${dkbColors.banana} Grab salt and head into oil cruise, but snake jump and fly to the vents for The Duct Inspector's Reward [300]`,
    `${dkbColors.banana} Fly Straight to back corner and use the elephant Salt to open the way to Fried on the Side [301]`,
    `${dkbColors.banana} Cross the Fryer all the way to the red lump terrain to break, inside for The Salt's Last Stop [302]`,
    `${dkbColors.triple} Up from here to Burger Switch and Triple Floating on a Royal Oil Cruise [305]`,
    `${dkbColors.triple} Forward and Up Left to the Mixer fight, Triple Frying at Ferocious Fryhouse [308]`,
    `${dkbColors.triple} Get the house on lion then fly to the burger switch and Triple Swingin through Kingly Swings [311]`,
    `${dkbColors.banana} Fly to the Swings right side, go through the ceiling for Up High in a Sky Container [312]`,
    `${dkbColors.banana} Fly to top of the UFO, up top first At a Grate Height [313]`,
    `${dkbColors.banana} Down for Burger Switch and the Triple Round the Grater-Go-Round [316]`,
    `${dkbColors.header} Turn around and follow the outer wall towards the start of the layer`,
    `${dkbColors.banana} Small salt pile on the outside Steamed-and-Salted Banana [317], Go hit final burger switch.`,
    `${dkbColors.banana} Warp up to behind the lion head for Crowning the Monarch [318], grab the key`,
    `${dkbColors.banana} On burger, Order Up at the Banana Burger [319]`,
    `${dkbColors.banana} BREAK the terravoider, turn around and go Under the Lion's Mane [320]`,
    `${dkbColors.banana} Down to the very first meat patty and dig in for Folded into the Parry [321]`,
    `${dkbColors.header} *SL1401`,
    `${dkbColors.triple} Triple Muckin Up Cat-Scratch Kitchen [324]`,
    `${dkbColors.banana} Through the first grating and thought the left side waterfall for As Seen through the Grate [325]`,
    `${dkbColors.banana} Get some sand in the elephant and at the wall of muck, kill the farthest right side enemy for The Muck's Private Stash [326]`,
    `${dkbColors.banana} Metal Bridge section, fly from underneath to grab Melt through the Metal Bridge [327]`,
    `${dkbColors.banana} Very top right above, Stuck in the Muck [328] Defeat the Boss now.`,
    `${dkbColors.header} *Forbidden`,
    `${dkbColors.quintuple} 5-Pack Scrubbed Muckety-Muck [333]`,
    `${dkbColors.banana} In the shaft, Snake straight up for Secret in the Shaft [334]`,
    `${dkbColors.banana} Exit the shaft and go to Challenge Room ahead Slippery, Soaking, Shuffle [337]`,
    `${dkbColors.banana} Snake up and up to the highest floating island for Pitching for Passage [338]`,
    `${dkbColors.banana} On that island, find the dig spot for underneath Past the Shuffling Ceiling [339]`,
    `${dkbColors.banana} Far left island for Passage to the Lonely Island [340]`,
    `${dkbColors.banana} Barrel Cannon back and cross the gap to Perilous Passage [341]`,
    `${dkbColors.banana} Straight ahead to final island Unwelcome at Go-No-Further Gate [342]`,
    `${dkbColors.banana} Far right hole to underground, through the lava to Passage through Lava [343]`,
    `${dkbColors.header} Collect some gold on the way to Void Fight.`,
    `${dkbColors.header} *Planet Core`,
    `${dkbColors.quintuple} Five Pack, Victory over Void Kong [348]`,
    `${dkbColors.banana} Straight forward to In the Belly of K. Rool [349]`,
    `${dkbColors.banana} Minecart into town. Upper Left ledge for Shifty Smash: Inhale and Destroy [350]`,
    `${dkbColors.banana} Bounce up and fly to middle barrel in the sky for Floating over Fractone Fort [351]`,
    `${dkbColors.banana} Minecart, at the end of Necky Skyway is Survived the Gravel Gauntlet [352]`,
    `${dkbColors.banana} Minecart, behind the first switcheroo wall is Klaptrapped behind the Goo [353]`,
    `${dkbColors.banana} Top of the platforms for The Switcheroo Chase [354]`,
    `${dkbColors.banana} Minecart, Fly around the structure for hidden Korner of the Krevasse [355]`,
    `${dkbColors.banana} End of the path for Cracking Open the Way [356]`,
    `${dkbColors.banana} Minecart, head straight to Stomped Stompenclomper Again [357]`,
    `${dkbColors.banana} Minecart to second Fractone Town. Very top of the highest ledge for Fractone Cradle Climb [358]`,
    `${dkbColors.banana} Minecart, near the end of big Turf Surf section, Turf Surf Pit Stop [359]`,
    `${dkbColors.banana} On the way out grab Turf Surf Finish Line [360]`,
    `${dkbColors.banana} Minecart, Koliseum, Minecart, Cranky at the top left on Climactic Cliff Cranky's Planet Core Rant [361]`,
    `${dkbColors.quintuple} Defeat K. Rool for Five Pack Rocked King K. Rool [366] New Donk City and defeat K Rool 2.`,
    `${dkbColors.header} *Ingot Isle 2`,
    `${dkbColors.triple} First Banana straight ahead for Triple Gold Rush [369]`,
    `${dkbColors.header} Back to where you first met Oddrock to get Pauline back. Warp up to Baboom entrance.`,
    `${dkbColors.banana} Turn around, Jump and fly to the spiky floating platform and Egg Bomb it for Thwarting the Thorns [370]`,
    `${dkbColors.banana} Fall down and around the right side of the Isle, smash the wall around back for Snack on the Outskirts of Town [371]`,
    `${dkbColors.banana} Snake jump straight up to Shifty Smash: Quick and Nimble [372]`,
    `${dkbColors.quintuple} Head forward to Grumpy Kong's Challenges (15000g) Five Pack Finished Four Fights [377] (Charge Punch 1, Fast Charge 1 and 2)`,
    `${dkbColors.quintuple} Next four fights for Five Pack Beat Eight Bouts [382]`,
    `${dkbColors.quintuple} Next four fights for Five Packs Won Thirteen Throwdowns and Battle Rush Cleared [392] (Charge Punch 2)`,
    `${dkbColors.header} Exit and enter Boss Re-Fights for Five Packs:`,
    `${dkbColors.quintuple} Kong-quered Inflammonite [397]`,
    `${dkbColors.quintuple} Kong-quered Abracajabya [402]`,
    `${dkbColors.quintuple} Kong-quered Sinister Blusterwing [407]`,
    `${dkbColors.quintuple} Kong-quered Muckety-Muck [412] (Fast Charge 3)`,
    `${dkbColors.quintuple} Kong-quered Stompenclomper and Kong-quered the Boss Rush [422]`,
    `${dkbColors.banana} Behind the Grumpy Challenges, break concrete in the water for Snack in a Sunken Lab [423]`,
    `${dkbColors.banana} Snake jump up above to Post-Sprint Treat [424]`,
    `${dkbColors.banana} Jump up over the ledges for one banana (1000g) with Ingot Isle Growtone [425]`,
    `${dkbColors.header} Fall down to warp gong.`,
    `${dkbColors.header} *Lagoon 2`,
    `${dkbColors.banana} Turn Around and fly to the Island for Up, Over and Across [426]`,
    `${dkbColors.banana} Underneath the island, Zebra across the water for Within the Fast-Growing Grass [427]`,
    `${dkbColors.banana} Run across the water and jump to the platform with Shifty Smash: A Wall Hanging in the Air [428]`,
    `${dkbColors.banana} Snake bounce and fly to the next floating island for Outskirts of Fishing Village [429]`,
    `${dkbColors.triple} Fall back for where you'd land from Sublayer 1 at the reservoir for Triple Landed in Salvager's Landing [432]`,
    `${dkbColors.banana} Across the water under the main island for On the Ceiling of the Floor [433]`,
    `${dkbColors.banana} Up on the main island for Challenge Room Thorn-Choked Conveyor [436]`,
    `${dkbColors.banana} Back to main island, underneath the hut is The Salvager's Stash [437]`,
    `${dkbColors.banana} Head towards rehearsal Crossed to the Kong Elder's Court [438]`,
    `${dkbColors.banana} 1st side room, and Past the First Scrappin Ground [440]`,
    `${dkbColors.banana} Past the Second Scrappin Ground [441]`,
    `${dkbColors.banana} Past the Third Scrappin Ground [442]`,
    `${dkbColors.banana} 4th side room, and Past the Fourth Scrappin Ground [444]`,
    `${dkbColors.banana} 5th side room [445]`,
    `${dkbColors.triple} Triple Past the Fifth Scrappin Ground [448]`,
    `${dkbColors.banana} Back outside, go around the shipping containers for The Ship Stern's Snack [449]. This one is potentially skippable if you're ahead. Warp Gong.`,
    `${dkbColors.header} *Canyon 2`,
    `${dkbColors.banana} Go forward and off the cliff to break the Void Lock. Hanging Hallway over the Refinery [450]`,
    `${dkbColors.banana} Forward and up the cannon, straight ahead in the wall is Foreman's Secret Stash [451]`,
    `${dkbColors.banana} Opposite cliffside, climb for Shifty Smash: Cliff's Edge [452]`,
    `${dkbColors.banana} Enter the cave beside, go down into the shaft for Peak's Peek at the Refinery [453]`,
    `${dkbColors.banana} Two Barrel Cannons up, talk to Canyon's Smashin Stats [454]`,
    `${dkbColors.banana} Dig down below the ladder to the right for Sleeping by the Smokestack [455]`,
    `${dkbColors.banana} Challenge Room on the outer cliff to the left Big-Wheel Balloon Hunt [458]`,
    `${dkbColors.banana} Up from the challenge room, on the Nose of the cliffside Banana Up the Nose [459]`,
    `${dkbColors.banana} Up in the middle of the concrete spinning pillar Circling in the Concrete Pillar [460]`,
    `${dkbColors.banana} Go around the other side and fall for the earring banana in the wall An Edible Earring [461]`,
    `${dkbColors.banana} Straight ahead and dig down, dig to the right of the pillar underground for Hidden beneath Scoundrels [462]`,
    `${dkbColors.triple} Dig straight down for the Void Key. Head down for the Mixer fight. Triple Beat Grumpy Kong [465]`,
    `${dkbColors.triple} Snake jump and fly to the opposite side of the arena for the minecart, get the Triple Beat the Mad Mixer [468]`,
    `${dkbColors.banana} Fall below this platform and dig in the ground for Mad Mixer's Parting Gift [469]`,
    `${dkbColors.banana} Snake Jump and fly to the platforms to the right, lower platform in the rubble is Asleep in the Dormitory [470]`,
    `${dkbColors.header} Snake jump to the upper platforms and break the terravoider inside the building.`,
    `${dkbColors.banana} Exit straight ahead towards the minecart and grab De-Voiding the Dorms [471]`,
    `${dkbColors.banana} Go left into the corner building for Tucked away in a Dormitory [472]`,
    `${dkbColors.banana} Challenge Room behind you, right side wall Spinning Laser Zone [475]`,
    `${dkbColors.banana} Run out behind the challenge room to the platforms below towards Shifty Smash: Moving Targets [476]`,
    `${dkbColors.banana} Dig inside the big mound right ahead for Treasure by the Triceratops [477]. Warp back to the Gong.`,
    `${dkbColors.header} *Divide 2`,
    `${dkbColors.banana} Challenge Room right ahead and underneath Great Switcheroo Hall [480]`,
    `${dkbColors.banana} Continue around the outside of the lower area to find Switcheroo through the Wall [481]`,
    `${dkbColors.banana} Ostrich fly to the underside of the Divide into the nook for Safe Landing Switcheroo [482]`,
    `${dkbColors.header} Barrel Cannon and up the Freezer path, break the Void Lock.`,
    `${dkbColors.header} *Freezer`,
    `${dkbColors.banana} Turn right, jump down the ledge and take the next ledge down to Enshrined atop the Pillar [483]`,
    `${dkbColors.banana} Turn around and dig through the wall for Under the Cliff-Edge Scoop Hut [484]`,
    `${dkbColors.banana} To the left of the barrel cannon, smash the wall and continue into the snowy cave and under the first mound for Slumbering in the Snow [485]`,
    `${dkbColors.banana} Turn around and smash the wall a short way through to Turned Up under Turnips [486]`,
    `${dkbColors.triple} Two barrel cannons up to Triple Chillin in the Freezer Layer [489]`,
    `${dkbColors.banana} To the right of the triple, right in front of the 3 crates, dig straight down for a while for A Snowy-Cliffside Secret [490]`,
    `${dkbColors.banana} Leave out the right wall, fall down one story below to A View from Crumbly Bridge [491]`,
    `${dkbColors.banana} Jump down to the left side of where the main Crumbly Bridge is, through the water fall and through the snow for Hidden Behind a Waterfall [492]`,
    `${dkbColors.banana} Surf back out across the water to the small floating platform for Over the Freezing River [493]`,
    `${dkbColors.banana} Snake Jump up to just to the right of the end of Crumbly Bridge for Challenge Room Red-Hot Rotations [496]`,
    `${dkbColors.banana} Snake jump up for Across Crumbly Bridge [497]`,
    `${dkbColors.banana} To the right and up to the 3 (3000g) Freezer Growtones [500]`,
    `${dkbColors.banana} Go left for Freezer Hide-and-Seek [501]`,
    `${dkbColors.banana} Go down and into hut to break terravoider for Heavily Protected Produce [502]`,
    `${dkbColors.banana} The round hut beside the Gong to break the terravoider. Forward through to the new banana Un-Voiding the Scoop Hut [503]`,
    `${dkbColors.banana} Snake jump up ahead to the pathway on the right for Sitting on the Snow [504]`,
    `${dkbColors.banana} Snake jump up to the floating yellow hut behind for Scoop Hut in the Sky [505]`,
    `${dkbColors.banana} Run straight down to the Dive Punch Switch to open Cracking Open Coolstripe Cavern [506]`,
    `${dkbColors.banana} Run forward and at the left turn, take a right for Edge of a Cool Pool [507]`,
    `${dkbColors.banana} Keep following the path to an open room to find Beware Falling Icicles [508]`,
    `${dkbColors.banana} Jump across the small gap for the banana in the gold pile Deep in the Cavern [509]`,
    `${dkbColors.banana} Keep going, but out the first left ledge of the cavern for Gazing at the Cooling Tower [510]`,
    `${dkbColors.banana} Back in the cavern, right off the ledge underneath it is Kept in a Coolstripe Cubby [511]`,
    `${dkbColors.banana} Run past the Void Lock and smash the wall for Coolstripe Cavern's Lost Treasure [512]`,
    `${dkbColors.header} Break the Void Lock to go down.`,
    `${dkbColors.banana} Right for Molten-Hot Choco Banana [513]`,
    `${dkbColors.triple} Triple Through Coolstripe Cavern [516]`,
    `${dkbColors.banana} Surf on the lava to get to the next banana on the path, stuck in the gold Coolin Down in Canter Creamery [517]`,
    `${dkbColors.banana} Snake Jump up to the spinning fans, get the top for Found above the Fan [518]`,
    `${dkbColors.header} Zebra Rehearsal.`,
    `${dkbColors.banana} Amuse-Boost Finish Line, Abuse Boost Fast Finish [520]`,
    `${dkbColors.banana} Hurl d'Oeuvres Finish Line, Hurl d'Oeuvres Fast Finish [522]`,
    `${dkbColors.banana} Shocking Cioppino Finish Line, Shocking Cioppino Fast Finish [524]`,
    `${dkbColors.banana} Switcheroo Entree Finish Line, Switcheroo Entree Fast Finish [526]`,
    `${dkbColors.banana} Dangerous Dessert Finish Line, Dangerous Dessert Fast Finish [528]`,
    `${dkbColors.banana} To the right pathway, dig down at the little gold roots popping up for Beneath the Zig-Zag Paths [529]`,
    `${dkbColors.banana} Elephant to suck up a challenge room just above and right behind you after the barrel cannon Precarious, Powdery Path [532]`,
    `${dkbColors.banana} Banana in the lava to the right of the exit. Kept Warm in the Field [533]`,
    `${dkbColors.banana} Dig straight down just in front of that last banana underground to Through a Too-Hot Tunnel [534]`,
    `${dkbColors.header} Warp back to the Gong. Right, run up the stairs and into the tower. Fall down the shaft`,
    `${dkbColors.banana} Elephant suck on Right side of the front wall for Buried in the Cooling Tower [535]`,
    `${dkbColors.triple} Suck the middle Lava to get into the lower sub layer. Break the Void Lock, and collect the Triple Hoofin it to Hot-Hoof Heater [538]`,
    `${dkbColors.banana} Fly to the right small island for Treat on a Tiny Island [539]`,
    `${dkbColors.banana} Snake jump and Fly to the Ice Maker banana Tricky Trot to the Ice Maker [540] Back to Warp Gong.`,
    `${dkbColors.header} *Forest 2`,
    `${dkbColors.banana} Chip Exchange for 7 Bananas with 280 Chips. Forest Chip Exchange [547]`,
    `${dkbColors.banana} Big Tree beside the Gong, Up to the middle and inside for Found in the Ostrich Flock [548]`,
    `${dkbColors.banana} Fall down for Smashin Stats Forest Smashin Stats [549]`,
    `${dkbColors.banana} Directly to the left, surf to the island for the Bird's-Eye View on the Bellhop Burb [550]`,
    `${dkbColors.banana} Snake Jump and fly up left of the town, high up platform, under the grass for Branching over the Plains [551]`,
    `${dkbColors.banana} Back down to the town, on top of the tree stump Hopped into Bellhop Burb [552]`,
    `${dkbColors.banana} Go into town, follow the pathway across, and right outside the Style Shop, dig for Beneath Bellhop Burb [553]`,
    `${dkbColors.banana} Tree just ahead requires a Snake Jump or Fly from the barrel cannon, on the tree branch is Shifty Smash: Crossing the Branch [554]`,
    `${dkbColors.banana} Base of the tree, a Turnip sticking out of the mud, dig for Mired in Mud [555]`,
    `${dkbColors.banana} Left to the small island with a Klaptrap for Tiny Isle in the Wetlands Warp to Eggshell Hotel [556]`,
    `${dkbColors.banana} Snake Jump up atop the building to Atop the Eggshell Hotel [557]`,
    `${dkbColors.header} Ostrich Rehearsal.`,
    `${dkbColors.banana} Off to a Flying Start [558]`,
    `${dkbColors.banana} Right Path, under the platform before the first bounce, Taking the Low Road [559]`,
    `${dkbColors.header} Up to the ledge opposite the Bouncy Crockoid, Glide to final platform to skip the rest of the rehearsal`,
    `${dkbColors.triple} Get the Triple Topped the Tower of Turbulence [562]`,
    `${dkbColors.banana} Jump down behind the Elder and open the Challenge Room All-You-Can-Eat Tower [565]`,
    `${dkbColors.banana} Fall down to the very bottom of the egg, smash the wall to the right for Egg Bottom Basement [566]`,
    `${dkbColors.banana} Break Bramble to the right for Egg-Bottom Break-In [567]. Back to Warp Gong.`,
    `${dkbColors.header} *Tempest 2`,
    `${dkbColors.header} Elephant Rehearsal`,
    `${dkbColors.banana} Salty Forecast Cleared, 1st Right side for the bonus Smart Suction to Skip the Slip [569]`,
    `${dkbColors.banana} Glowing Forecast Cleared [570]`,
    `${dkbColors.banana} Golden Forecast Cleared, 3rd Right side bonus for Smart Suction to Build a Bridge [572]`,
    `${dkbColors.triple} Triple and talk to elder Elephant Elder's Forecast Cleared [575]`,
    `${dkbColors.banana} Behind the Elephant Elder, Elephant Elder's Secret Snack [576]`,
    `${dkbColors.banana} Snake Jump up to the roof, and find Three (4000g) Tempest Growstone [579], SAVE 500 GOLD`,
    `${dkbColors.banana} Go left and down for Hiding up High [580]`,
    `${dkbColors.banana} Go across and Snake Jump up the platforms for Lifted to the Skies [581]`,
    `${dkbColors.banana} Jump down into alcove by tornado Tucked by the Tornado [582]`,
    `${dkbColors.banana} Dig down next to grate for Tour Through the Tunnels [583]`,
    `${dkbColors.banana} Dig towards 2D challenge course and down slightly for Cavernous Corridors [584]. Warp to Gong`,
    `${dkbColors.header} *Groove 2`,
    `${dkbColors.header} Forward and drop down to lower room behind, to Jail. Constructone (500g) and flip the Harp to Gold.`,
    `${dkbColors.banana} Go forward through concrete to find The Secret in Solitary [585]`,
    `${dkbColors.banana} Back to Jail, Snake jump and punch concrete bars for Banana Behind Bars [586]`,
    `${dkbColors.banana} Punch forward through wall for A Square-Shaped Secret [587]`,
    `${dkbColors.banana} To Left Jail Cell for another secret behind the wall Smash and Receive [588]`,
    `${dkbColors.banana} Leave Jail to main area for Gettin Down in the Groove Layer [589]`,
    `${dkbColors.banana} First Door upper left, Snake jump up for Bouncy Brainteaser [590]`,
    `${dkbColors.banana} Leave and get on Disco ball for Over the Disco [591]`,
    `${dkbColors.banana} Right across, kill the fractone to enter and get Cranky's Groove Rant [592]`,
    `${dkbColors.banana} Snake Jump in this room for Banana Chandelier [593]`,
    `${dkbColors.banana} In the main room, Snake Jump up to the disco ball for Disco Ball Destruction [594]`,
    `${dkbColors.banana} Smash the wall to the left of the first Music recovery for Behind the Disco's Wall [595]`,
    `${dkbColors.banana} Main Area grab the Banana's sitting in the open The Funky Beat is Back [596]`,
    `${dkbColors.banana} The Groovy Bass is Back [597]`,
    `${dkbColors.banana} Enter that doorway, in the middle of the corridor, go up to the ceiling for Rising Bass Line [598] (Better Glare 3)`,
    `${dkbColors.header} *Radiance 2`,
    `${dkbColors.header} AT THIS POINT: Pay attention to your banana count. You only need 600 to enter Snake Rehearsal.`,
    `${dkbColors.banana} Snake jump above for Challenge Room Snake Bananza: Charge Climb [601]`,
    `${dkbColors.banana} Go left to Sitting on a Snake's Head [602]`,
    `${dkbColors.banana} Elephant suck the lava in left disc room and drop in for Bathing in the Essence of the Sun [603]`,
    `${dkbColors.banana} Snake Jump Over the Elder's Head [604]`,
    `${dkbColors.header} Snake Rehearsal (don't get bananas!)`,
    `${dkbColors.header} *Planet Core 2`,
    `${dkbColors.header} Final Rehearsal. (juice boost on 4th row of enemies)`
  ]
};
