import type { Route } from "../../classes/Route";
import { dk64Colors, titleColors } from "../../utils/colors";
export const dk64Glitchless101: Route = {
  title: "Glitchless 101%",
  headerColor: titleColors.dk64,
  doc: "https://docs.google.com/document/d/1rheoGwmR9_PbBVcT7OGHuZvm45quH8pZ_repNgXB7Dc",
  steps: [
    `${dk64Colors.dk} Training Barrels, Simian Slam from Cranky`,
    `${dk64Colors.dk} Avoid warps to get the cutscene skip in Japes, visit K. Lumsy`,
    `${dk64Colors.dk} Enter Japes [1]`,
    `${dk64Colors.header} *Japes 1`,
    `${dk64Colors.dk} Swing on Vines to switch (5) 3 Coins {3} W1 Cutscene overlap, Tag left W3 (10)`,
    `${dk64Colors.dk} Battle Crown Text, Buy Gun. Cannon to Diddy [2] Fall to T&S bunch (15)`,
    `${dk64Colors.dk} Fall and hit switch, Use W3 (20), Shoot left switch and balloon (30)`,
    `${dk64Colors.dk} Climb vine, Climb Tree (35) Battle Crown cutscene skip, cannon to GB [3]`,
    `${dk64Colors.dk} 1 Banana on slope, Fall to hit W4 and go to Balloon (55)`,
    `${dk64Colors.dk} Rambi {3} to Open Lanky & Tiny Huts, Chunky Door, Diddy & DK huts`,
    `${dk64Colors.dk} Hit DK Switch (65) Buy Baboon Blast {0}`,
    `${dk64Colors.diddy} Hit Switch (5) W4, River Bunches (15) & 3 Coins, Caged GB [4] Buy Gun`,
    `${dk64Colors.diddy} Enter Mountain (18) Bridge Clip {1} Out to top GB [5](28)`,
    `${dk64Colors.diddy} Hit W2. Re-enter (32) Minecart GB (57)[6] Shoot Switch for Lanky`,
    `${dk64Colors.diddy} Blueprint & 3 coins {4}(60) Climb 1 Tree (65)`,
    `${dk64Colors.dk} Blueprint, & 2 Coins {2} Baboon Blast with 3 coins [7](75){5} Caged GB [8]`,
    `${dk64Colors.diddy} Tunnel GB [9] & 2 coins, Enter T&S {6}`,
    `${dk64Colors.dk} Feed Bananas, Key 1, RESET OR PAUSE ON KEY 1`,
    `${dk64Colors.header} *Isles to Aztec`,
    `${dk64Colors.dk} Tag W5 & W1 in ring, Turn in Key 1, W1 back, Tag W2 & W3, Climb to Aztec`,
    `${dk64Colors.header} *Aztec 1`,
    `${dk64Colors.dk} Blueprint & 3 Coins {8} Buy Bongos {5}`,
    `${dk64Colors.diddy} Hit W1, Buy Guitar {3} Balloon (10) W2 Bunch/Coins {8}(15)`,
    `${dk64Colors.diddy} Open Tunnel, Walk to Cranky (20) Buy Rocketbarrel {0}`,
    `${dk64Colors.dk} Balloons (20) Hit far warp (2 maybe?) & 3, Baboon Blast, Balloon (34) Enter Llama Temple`,
    `${dk64Colors.dk} Bongo Pad (37){8} Stealthy Snoop Switch (40) Hit Top Warp 1 (42) Free Lanky [10] Hit W2`,
    `${dk64Colors.dk} Leave Llama Temple, Hit W4, Stealthy Snoop [11](62) Exit/Enter`,
    `${dk64Colors.dk} W1, 2 Trees (72), Llama GB with 1 coin [12]{9}(75)`,
    `${dk64Colors.diddy} Blueprint, Enter Tiny Temple, Thaw Ice {1}(38)`,
    `${dk64Colors.diddy} GKONG, Free Tiny (45){6}[13] Exit/Enter W1`,
    `${dk64Colors.tiny} 4 Coins, 3 Coins by Hunky Chunky {7} Blueprint, Buy Mini Monkey {4}`,
    `${dk64Colors.lanky} 4 Coins, Buy Orangstand {1}(6) W3, W4, 5 Coins, Buy Gun {3}`,
    `${dk64Colors.tiny} Buy Gun {1} W5 Coins {6}(5) Enter T&S`,
    `${dk64Colors.dk} Feed Bananas`,
    `${dk64Colors.diddy} Feed Bananas, Key 2`,
    `${dk64Colors.diddy} Ram Gongs & GB (48)[14] No Tree Bunch`,
    `${dk64Colors.diddy} Enter Rocketbarrel with 3 bananas on steps (51) Through Star (56) 5DT Switch (60)`,
    `${dk64Colors.diddy} Vulture GB (65)[15] Feed totem, Fly to 5DT, balloon (75) and GB [16] EXIT`,
    `${dk64Colors.header} *Isles to Factory`,
    `${dk64Colors.diddy} W2 AS DIDDY`,
    `${dk64Colors.tiny} Swim to Fairy Island, Get Camera, Caged GB [17] Use W5`,
    `${dk64Colors.dk} [Right] W1, Rainbow Coin behind Klumsy, Turn in Key 2, Climb to Factory`,
    `${dk64Colors.header} *Factory`,
    `${dk64Colors.dk} Activate Warp 1, Walk of shame to Chunky room (15) BBlast with 3 Bundles (30)`,
    `${dk64Colors.lanky} [Right] Free Chunky (5)`,
    `${dk64Colors.chunky} [Right] Use W1, Get 4 coins by hatch (10){14} Drop down hatch (20) Exit to Lobby`,
    `${dk64Colors.lanky} [Left] Enter Factory, W2 bunch (10) W1, Chunky GB [18] Pound Blue Switch`,
    `${dk64Colors.lanky} Climb boxes & get 2 Coins {10} Buy Baboon Balloon & Trombone (10){2}`,
    `${dk64Colors.diddy} [Left] Buy Simian Spring {4}`,
    `${dk64Colors.dk} [Left] Buy Gorilla Grab {2} Balloon (40)`,
    `${dk64Colors.chunky} [Right] Buy Primate Punch & Triangle {3}`,
    `${dk64Colors.tiny} [Left] Buy Ponytail Twirl & Saxophone {3} Exit/Enter`,
    `${dk64Colors.tiny} to Spinning Wheel (25)[19] Balloon & Fairy (35) Buy Ammo Belt 1 {0}`,
    `${dk64Colors.chunky} Buy Gun {0} Blueprint`,
    `${dk64Colors.dk} [Right] Number Game [20] Balloon, Fairy (55)`,
    `${dk64Colors.diddy} [Right] Tower (20)[21] Jump left`,
    `${dk64Colors.lanky} [Right] Bonus GB [22] go to R&D {3} Piano GB (22)[23] Blueprint (40)`,
    `${dk64Colors.dk} [Right] Pull lever, Battle Crown, No Balloon, drop to Power Shed (60) Exit to Lobby GB, W2`,
    `${dk64Colors.diddy} [Right] R&D room (50) {3124, 4231, 1342}`,
    `${dk64Colors.diddy} 1 coin dropping to Beaver bother {5}`,
    `${dk64Colors.diddy} pound switch, blueprint (60), tag high W4, spring to GB (75)`,
    `${dk64Colors.lanky} [Right] Balloon (50) Up pipe to GB (75), fall to W4`,
    `${dk64Colors.chunky} [Right] Jump for 5 (60) Pound Switch for GB, Get (75)`,
    `${dk64Colors.tiny} [Left] Balloon (55), Bonus GB (75)`,
    `${dk64Colors.dk} Blueprint, Crusher Room (75) Exit/Enter`,
    `${dk64Colors.chunky} [Right] Toy Monster w/ Balloon & Singles (55) Exit to lobby, Break Box`,
    `${dk64Colors.tiny} Blueprint, Fairy, W2, Car race (45) Exit/Enter W1`,
    `${dk64Colors.chunky} Dark room (75) Climb to Bonus Barrel, Feed Bananas`,
    `${dk64Colors.dk} Feed Bananas, Arcade`,
    `${dk64Colors.tiny} Feed Bananas, Key 3, grab bananas (5) and GB, BP, EXIT`,
    `${dk64Colors.header} *Isles to Galleon`,
    `${dk64Colors.diddy} [Left] Drop to Snides Bonus GB`,
    `${dk64Colors.chunky} [Left] Battle Crown, Go to Galleon Lobby`,
    `${dk64Colors.dk} Enter Galleon`,
    `${dk64Colors.header} *Galleon`,
    `${dk64Colors.dk} Open Gate, Back to Tag`,
    `${dk64Colors.chunky} Hit W2 (15) Hit W3, Punch gate, Treasure GB & Fairy (25) Exit/Enter`,
    `${dk64Colors.chunky} Cannon Game (10){3}`,
    `${dk64Colors.diddy} Open Gate, Hit W5, Balloon by Music Pad (10) 5DS with 1 bunch (19)`,
    `${dk64Colors.chunky} Blueprint (35)`,
    `${dk64Colors.lanky} [Right] Music Pad (5) Balloon (10) 5DS (35){6} Exit/Enter`,
    `${dk64Colors.lanky} Blueprint, singles (25) Through right tunnel`,
    `${dk64Colors.lanky} Enguarde, Break GB Chest`,
    `${dk64Colors.chunky} Music Pad, Raise Water, Hit W1, Use W5, Tunnel (75) 5DS`,
    `${dk64Colors.lanky} Enguarde to open treasure room (28) Swim to Cactus`,
    `${dk64Colors.dk} Music Pad, Tunnel (70) 5DS (75) W5, BBlast with all Bundles (15)`,
    `${dk64Colors.dk} Lighthouse GB, balloon on 2nd banana platform (45) Balloon Outside (55) Hit W3`,
    `${dk64Colors.diddy} Ship Switch, Blueprint, Rocket to balloon and top (39) W5 to Mech Fish (59)`,
    `${dk64Colors.diddy} Get (65) in tunnel, Gold Tower (75)`,
    `${dk64Colors.lanky} [Right] Gold Tower (33)`,
    `${dk64Colors.tiny} [Right] Pearls (15) Exit/Enter`,
    `${dk64Colors.chunky} W1, Seasick GB (60) Leave, W5, Dive to Tag`,
    `${dk64Colors.dk} W4 for Blueprint, Seal Race, Swim to Cactus`,
    `${dk64Colors.tiny} Submarine GB, 5DS & Fairy (54) Exit/Enter W1, Mermaid GB Exit/Enter`,
    `${dk64Colors.tiny} Cannon Room Bunches (30) Hit Switch (34) 2DS with 1 bunch (39) W2`,
    `${dk64Colors.tiny} Blueprint (60) W3 for Balloon (75)`,
    `${dk64Colors.tiny} Turn in 4 BPs, W3 & Enter T&S, Feed Bananas`,
    `${dk64Colors.dk} [Right] Feed Bananas`,
    `${dk64Colors.diddy} [Right] Feed Bananas`,
    `${dk64Colors.lanky} [Right] Feed Bananas, Key 4, Balloons (63) Battle Crown, 2 singles (65) Hit Switch, 2DS (75)`,
    `${dk64Colors.header} *Isles to Japes 2`,
    `${dk64Colors.lanky} Swim to Klumsy, Turn in Key 4, W1, tag at warps`,
    `${dk64Colors.chunky} Move Rock`,
    `${dk64Colors.lanky} Music Pad, Enter Japes`,
    `${dk64Colors.header} *Japes 2`,
    `${dk64Colors.lanky} Use W1, Cave Bonus GB (5) Enter T&S`,
    `${dk64Colors.tiny} Bonus GB (7)`,
    `${dk64Colors.chunky} [Right] Pound X to underground, Blueprint (10) deathwarp exit, Boulder GB, Fairy`,
    `${dk64Colors.chunky} 3 Balloons & 5 in rock (45) Pound switch go to caged GB (55)`,
    `${dk64Colors.lanky} [Left] W4, Balloon (15) Hit Switch (20) W4, W2, Fall to GB`,
    `${dk64Colors.lanky} Fairy Room (53){8} to blueprint and bonus GB (75)`,
    `${dk64Colors.tiny} [Right] Balloon & Hit Switch (22) Use w4 for caged GB`,
    `${dk64Colors.tiny} blueprint, lower gate`,
    `${dk64Colors.chunky} [Right] Hunky Chunky & Bonus GB (75)`,
    `${dk64Colors.tiny} [Left] Logs (52) stump GB, Shell GB (75) EXIT`,
    `${dk64Colors.header} *Isles to Fungi`,
    `${dk64Colors.dk} Leave Japes Lobby, Cannon to Fungi`,
    `${dk64Colors.header} *Fungi`,
    `${dk64Colors.dk} Pink tunnel to mushroom tag (5)`,
    `${dk64Colors.diddy} Buy SSS {0} Rocket up to Bonus Barrel (10) Hit W5, 3 Singles to tag (13)`,
    `${dk64Colors.lanky} Climb to top (5), light room (10) dark room with both bunches (20)`,
    `${dk64Colors.chunky} Face room (15), Blueprint (25)`,
    `${dk64Colors.dk} BBlast (15) jump down ladder, roll around left to (25) Tag at W5 (30)`,
    `${dk64Colors.chunky} W5, Enter Mushroom (30)`,
    `${dk64Colors.lanky} Balloon (30)`,
    `${dk64Colors.diddy} Drop to Blueprint, 2 bananas (15) Drop and Shoot Switch`,
    `${dk64Colors.lanky} Shoot switch & Balloon (40)`,
    `${dk64Colors.tiny} [Right] Shoot switch, pound switch (5) get Bonus GB`,
    `${dk64Colors.chunky} [Left] Shoot switch, climb for (46), jump down`,
    `${dk64Colors.dk} Pound switch, cannon up (45) Leave to Tag by T&S (50)`,
    `${dk64Colors.tiny} Battle Crown, Blueprint & balloon (15)`,
    `${dk64Colors.lanky} 2 Singles (42) get to {9} coins, To W4 Area (52)`,
    `${dk64Colors.tiny} [Right] Hit W4, Enter stump (28) Get bean, GB, Deathwarp`,
    `${dk64Colors.tiny} (Fairy here if low on crystals/ammo?) Enter and shoot green tunnel`,
    `${dk64Colors.chunky} [Right] W2 Bananas (51) Hit W1, enter well (56)`,
    `${dk64Colors.chunky} Enter Shed Backdoor, Break Both Boxes, Music Pad (61)`,
    `${dk64Colors.chunky} Carry steel keg, Steel Keg GB`,
    `${dk64Colors.dk} [Right] Break box (55) Lever Puzzle (65) 21132`,
    `${dk64Colors.chunky} [Left] W1, Through Green Tunnel to tag`,
    `${dk64Colors.tiny} [Left] Beanstalk GB`,
    `${dk64Colors.chunky} [Right] Buy Homing Ammo, Hit W2 (66) Apple GB (75)`,
    `${dk64Colors.diddy} [Right] Jetpack to Night switch (25), Use W4 (35) Clockwise to (43), owl GB (48) W4, W1`,
    `${dk64Colors.diddy} Climb rope to barn roof (58) Dark Attic GB & Fairy (76) Leave`,
    `${dk64Colors.lanky} [Right] Enter Attic (62) GB & Bunch (67) on roof (69)`,
    `${dk64Colors.dk} [Left] Collect GB, Hit Switch (75) Enter Shed for GB & Fairy (80)`,
    `${dk64Colors.header} Switch 3, Stay 2`,
    `${dk64Colors.header} Switch, Stay`,
    `${dk64Colors.header} Switch 4, Stay 2`,
    `${dk64Colors.header} Switch 3, Stay 5`,
    `${dk64Colors.header} Switch/Brake`,
    `${dk64Colors.dk} Leave, Get Blueprint, Enter T&S, Feed Bananas`,
    `${dk64Colors.diddy} [Right] Feed Bananas`,
    `${dk64Colors.lanky} Feed Bananas`,
    `${dk64Colors.chunky} Feed Bananas, Key 5`,
    `${dk64Colors.tiny} [Left] Balloon (38)`,
    `${dk64Colors.diddy} [Left] Music Pad, Get GB, Meme Rainbow Coin {5}`,
    `${dk64Colors.tiny} [Right] All river Bananas (55) Mini Monkey to Spider GB (75) EXIT`,
    `${dk64Colors.header} *Isles to Caves`,
    `${dk64Colors.tiny} (Put Fairy here)`,
    `${dk64Colors.header} Ceiling Mushroom`,
    `${dk64Colors.chunky} Fall to Caged GB W3, W1, Turn in Key 5, W1`,
    `${dk64Colors.chunky} W2, Move Both Rocks, Music Pad GB`,
    `${dk64Colors.lanky} Music Pad, Meme Jump`,
    `${dk64Colors.chunky} Punch both walls`,
    `${dk64Colors.lanky} Blueprint`,
    `${dk64Colors.diddy} Music Pad GB`,
    `${dk64Colors.header} *Caves`,
    `${dk64Colors.diddy} Hit W2, Bananas by Funky (5) and fly to Bonus GB (10), Fly to waterfall tag`,
    `${dk64Colors.dk} Rotating room, Battle Crown (5) W2, Climb to Blueprint`,
    `${dk64Colors.chunky} Move boulder to Switch (13) Giant Boulder Room (44)`,
    `${dk64Colors.dk} Balloon (25) Leave Cave (28) Baboon Blast (53)`,
    `${dk64Colors.chunky} Rareware Coin, Buy Gorilla Gone`,
    `${dk64Colors.tiny} Buy Monkeyport`,
    `${dk64Colors.lanky} Buy Orangstand Sprint {7} Hit W4`,
    `${dk64Colors.lanky} Climb to Ice Castle Ice Cube GB (15){9} Beetle Race (20) Float to BP, hit W5 (40)`,
    `${dk64Colors.lanky} Use W2, Waterfall Balloon Cabin`,
    `${dk64Colors.tiny} [Right] Blueprint (10), to 5DCabin`,
    `${dk64Colors.diddy} [Left] Upper Balloon (20), Upper room (35), Lower Room with 2 coins (40){7}`,
    `${dk64Colors.dk} [Left] DK's room (15) (Try not to have extra homing ammo)`,
    `${dk64Colors.chunky} [Left] Chunky's Room (33)`,
    `${dk64Colors.tiny} [Left] Tiny's room (30) Use W5 & mini monkey to Monkeyport GB (45) W4`,
    `${dk64Colors.tiny} Cave Bonus GB (50) Leave To 5 River Bananas, Climb to Cranky`,
    `${dk64Colors.diddy} Rocketbarrel to Star (45) W4, Blueprint W4, Balloon (65) 5DI (75)`,
    `${dk64Colors.dk} 5DIgloo (75)`,
    `${dk64Colors.tiny} 5DI, W3 Bananas`,
    `${dk64Colors.chunky} Blueprint, 5DI (54) Igloo GB (59)`,
    `${dk64Colors.lanky} [Right] 5DIgloo, Balloon (75) Exit/Enter`,
    `${dk64Colors.chunky} (64) Gorilla Gone GB (72)`,
    `${dk64Colors.chunky} to Snide's T&S (75) Feed Bananas`,
    `${dk64Colors.tiny} Feed`,
    `${dk64Colors.lanky} Feed`,
    `${dk64Colors.diddy} Feed`,
    `${dk64Colors.dk} Feed, Key 6 EXIT`,
    `${dk64Colors.header} *Isles to Castle`,
    `${dk64Colors.dk} Lava GB, Enter Castle`,
    `${dk64Colors.header} *Castle`,
    `${dk64Colors.dk} BABOON BLAST (5) Activate W4, climb to W2 (25)`,
    `${dk64Colors.diddy} [Right] Use W2, Rocket to cloud (5) Bonus GB`,
    `${dk64Colors.diddy} [Left] Activate W5, Fall to Cranky, Buy SDSS, Fall left, Balloon (15) Fall to Crypt`,
    `${dk64Colors.diddy} Blueprint, Balloon (25), enter room, hit W1, Balloon (40) leave`,
    `${dk64Colors.lanky} Get (30), enter room, GB and balloon (40){12} deathwarp BUY SNIPER`,
    `${dk64Colors.tiny} Enter room, GB (5) deathwarp. Balloon by Funky (15)`,
    `${dk64Colors.chunky} Enter room for GB, walk out`,
    `${dk64Colors.dk} Enter room, hit W2, balloon (40) Minecart GB Exit/Enter`,
    `${dk64Colors.dk} Tree Blueprint & Fairy & GB (75) W5`,
    `${dk64Colors.dk} Fall to library (60) Go to Ballroom tag`,
    `${dk64Colors.diddy} Ballroom (65)`,
    `${dk64Colors.header} Switch 6, Stay`,
    `${dk64Colors.header} Switch 2, Stay`,
    `${dk64Colors.header} Switch 5, Stay 5`,
    `${dk64Colors.header} Switch, Stay 2`,
    `${dk64Colors.header} Switch 2, Stay, Brake`,
    `${dk64Colors.tiny} [Right] Ballroom car race (25) Fairy & Monkeyport (45) Exit/Enter`,
    `${dk64Colors.tiny} Blueprint, climb to use W5. Down ramp to (66) go to trash can (70)`,
    `${dk64Colors.tiny} Trash GB (75) W4, W5`,
    `${dk64Colors.lanky} Tower GB, Drop to greenhouse GB (70) and Battle Crown.`,
    `${dk64Colors.lanky} Leave, drop to Blueprint, drop to back hall.`,
    `${dk64Colors.tiny} [Right] Bonus Barrel`,
    `${dk64Colors.chunky} [Right] Enter dungeon (13) Smash 2 gates for balloons (33)`,
    `${dk64Colors.dk} [Right] Face puzzle (45)`,
    `${dk64Colors.diddy} [Right] chain room, balloon (75)`,
    `${dk64Colors.lanky} [Right] Float to GB, 2 balloons (90) deathwarp`,
    `${dk64Colors.chunky} [Right] Exit to hallway, Blueprint, 17 BANANAS INCLUDING 1 ON SLOPE (45)`,
    `${dk64Colors.chunky} Leave to Chunky Tree (60) walk out`,
    `${dk64Colors.chunky} W4 to Shed, 20 Homing Ammo, GB, Balloon (70) Museum (85) Exit to Lobby`,
    `${dk64Colors.chunky} Move Rock`,
    `${dk64Colors.lanky} Bonus GB`,
    `${dk64Colors.dk} [Left] Shoot switch`,
    `${dk64Colors.diddy} [Right] Blueprint, Enter Castle, W2`,
    `${dk64Colors.lanky} Key 7`,
    `${dk64Colors.header} *Isles to Aztec 2`,
    `${dk64Colors.lanky} Caged GB on Klumsy, Orangstand GB, Turn in Keys 6, 7`,
    `${dk64Colors.lanky} W1, W2, enter aztec 2`,
    `${dk64Colors.header} *Aztec 2`,
    `${dk64Colors.lanky} Enter Tiny Temple, Vulture GB (17) Crown Exit/Enter W1`,
    `${dk64Colors.tiny} Klaptrap GB (10) Balloons (30) Leave`,
    `${dk64Colors.chunky} Hunky Chunky GB, to snide's tag with singles (75)`,
    `${dk64Colors.tiny} Beetle Race (35)`,
    `${dk64Colors.dk} Enter Llama Temple, Use W1`,
    `${dk64Colors.tiny} Fairy, 1 bunch in Lava room with GB (45) W2, Balloon (55) W1`,
    `${dk64Colors.lanky} [Right] Matching Game with Bunch (22) Music Pad for GB 2 Balloons (42)`,
    `${dk64Colors.lanky} W2 for Blueprint W2 back, get (50), leave temple, 3 trees (65) 5DT (75)`,
    `${dk64Colors.tiny} Path and 3 Trees (75) 5DT with Fairy and GB`,
    `${dk64Colors.dk} 5DT`,
    `${dk64Colors.chunky} 5DT (20) Exit/Enter Vase Room (40) Use W1`,
    `${dk64Colors.chunky} enter Tiny Temple, Bunches (70) GB, EXIT`,
    `${dk64Colors.header} *Isles to Helm`,
    `${dk64Colors.diddy} Gongs`,
    `${dk64Colors.tiny} Aztec Lobby Bonus Barrel`,
    `${dk64Colors.tiny} W2, Monkeyport up to Helm, Music Pad, Fairy`,
    `${dk64Colors.chunky} Helm Lobby GB 20 Homing Ammo`,
    `${dk64Colors.header} *Helm`,
    `${dk64Colors.header} 5 Medals`,
    `${dk64Colors.diddy} Battle Crown`,
    `${dk64Colors.dk} Key, Fairies`,
    `${dk64Colors.header} *Isles to Fungi 2`,
    `${dk64Colors.dk} Blueprint, Fall to Caged GB, Enter Galleon Lobby`,
    `${dk64Colors.chunky} Hit Switch and Blueprint`,
    `${dk64Colors.tiny} Galleon Lobby GB, Turn in Keys 8 & 3, Reset Cutscene`,
    `${dk64Colors.chunky} W5, Fairy, Pound X, Rock GB, To front warps`,
    `${dk64Colors.tiny} W5 to Rareware GB, W5, W3, Enter Fungi Lobby`,
    `${dk64Colors.chunky} Battle Crown`,
    `${dk64Colors.lanky} Enter Fungi`,
    `${dk64Colors.header} *Fungi 2`,
    `${dk64Colors.lanky} Turn Day, Rabbit Race with Blueprint`,
    `${dk64Colors.lanky} Oh Banana`,
    `${dk64Colors.tiny} Oh Banana`,
    `${dk64Colors.chunky} Oh Banana`,
    `${dk64Colors.dk} Oh Banana`,
    `${dk64Colors.diddy} Oh Banana EXIT`,
    `${dk64Colors.diddy} Both GB's`,
    `${dk64Colors.header} *K. Rool`
  ]
};
