import type { Route } from "../../classes/Route";
import { dk64Colors, titleColors } from "../../utils/colors";

export const dk64GlitchlessAny: Route = {
  title: "Glitchless Any%",
  headerColor: titleColors.dk64,
  doc: "https://docs.google.com/spreadsheets/d/e/2PACX-1vRzSfCuMvYruNml5sIQm-Z6pPJr3D5TF_KjdvpJVbOlhGBCctCNb-9LVEJ96vnDeA/pubhtml#gid=1194333991",
  steps: [
    `${dk64Colors.header} *Pre-Japes`,
    `${dk64Colors.dk} Spawn & complete training barrels. Get Simian Slam`,
    `${dk64Colors.dk} Exit training area. Open Japes.`,
    `${dk64Colors.dk} Japes lobby entrance GB [1]. Enter Japes`,
    `${dk64Colors.header} *Japes 1`,
    `${dk64Colors.dk} Open cave cage. 3 coins {3}, W1 CS skip tag left W3 (5).`,
    `${dk64Colors.dk} Touch BC to trigger Squawks text, but wait to get BC.`,
    `${dk64Colors.dk} Buy gun {0}, Cannon to GB [2]`,
    `${dk64Colors.dk} Jump in front of T&S to get bunch (10). Fall and hit right switch, use W3 (15).`,
    `${dk64Colors.dk} Shoot left balloon (25) & left switch.`,
    `${dk64Colors.dk} Climb tree by Funky to shoot middle switch (30).`,
    `${dk64Colors.dk} Drop down to BC to skip Free Diddy CS`,
    `${dk64Colors.dk} Cannon to GB [3]. Go towards Snide, collecting 5 bananas & balloon (45)`,
    `${dk64Colors.diddy} Fall to tag W4, get BP <1> & 3 coins {3}, go to Cranky area`,
    `${dk64Colors.dk} Shoot balloon (55). Rambi (get bunch & coins) {3} (60) to open Tiny, Diddy & DK huts`,
    `${dk64Colors.dk} Hit DK switch (65). Buy Baboon Blast {0}`,
    `${dk64Colors.diddy} Buy Chimpy Charge. Hit switch, W4, 3 coins in river {3}, caged GB [4].`,
    `${dk64Colors.diddy} Buy gun {0}. Mountain GB {1}[5]. Tag W5`,
    `${dk64Colors.dk} BP <1>, Baboon Blast [6] (75) (have at least 2 coins). Caged GB [7]`,
    `${dk64Colors.diddy} Tunnel GB [8] and 2 coins {3} Enter T&S`,
    `${dk64Colors.dk} Feed 60 bananas, Key 1, Exit Japes`,
    `${dk64Colors.header} *Japes to Aztec`,
    `${dk64Colors.dk} Tag W5 & W1. Turn in Key 1.`,
    `${dk64Colors.dk} Take W1, tag W2 & W3. Enter Aztec.`,
    `${dk64Colors.header} *Aztec`,
    `${dk64Colors.dk} 3 coins by Kasplat, BP <2>, & banana bunches in quicksand (10). Buy bongos`,
    `${dk64Colors.diddy} Hit W1, buy guitar. Outside temple balloon (10).`,
    `${dk64Colors.diddy} Enter temple, thaw ice (28) {1}, swim to Tiny's area, getting 6 bananas (34)`,
    `${dk64Colors.diddy} Free Tiny & get 4 coins by cage {5} & GB [9].`,
    `${dk64Colors.diddy} Exit/enter. W1, open hallway`,
    `${dk64Colors.tiny} Coins by tag {4}, BP <1>, buy Mini Monkey {1}`,
    `${dk64Colors.diddy} Buy Rocketbarrel {1}`,
    `${dk64Colors.dk} Balloons by Cranky (30), tag far W2, Baboon Blast`,
    `${dk64Colors.dk} Balloon behind Llama Temple (43), enter temple`,
    `${dk64Colors.dk} Bongos pad (47) (have at least 7 coins)`,
    `${dk64Colors.dk} Go up to the right and get 3 bananas on the ramp and 1 banana on the stairs (51)`,
    `${dk64Colors.dk} Free Lanky [10]. Climb left stairs (57), tag W1`,
    `${dk64Colors.tiny} 1 coin by tag {2}. Tag W2 by Kasplat, lava GB [11]. Exit/Enter, W1`,
    `${dk64Colors.dk} 3 tree bunches (72), llama GB [12] (75)`,
    `${dk64Colors.diddy} BP <2>. 2 coins around W2 {7}. Take W2 (39).`,
    `${dk64Colors.diddy} Go left to get tower GB [13], getting 6 banana along the way (45)`,
    `${dk64Colors.tiny} W5 coins {7}, buy gun {4}. Enter T&S`,
    `${dk64Colors.header} Feed with DK/Diddy`,
    `${dk64Colors.diddy} Key 2`,
    `${dk64Colors.lanky} W4 coins {5}, buy gun {2}, enter llama temple.`,
    `${dk64Colors.lanky} W2, BP <1>, W2, W1, matching game [14].`,
    `${dk64Colors.lanky} 1 coin over lava {3}. Exit Aztec`,
    `${dk64Colors.header} *Aztec to Factory`,
    `${dk64Colors.lanky} Take W2 down.`,
    `${dk64Colors.tiny} Swim to BFI, get camera & caged GB [15], W5`,
    `${dk64Colors.dk} Tag W4. Rainbow coin by K. Lumsy & turn in Key 2. Enter Factory`,
    `${dk64Colors.header} *Factory`,
    `${dk64Colors.dk} Slam blue switch, go to storage room (15), slam storage room blue switch`,
    `${dk64Colors.lanky} Free Chunky (wait to get GB) (5)`,
    `${dk64Colors.chunky} Take W1, with coins {10} & bunches (10).`,
    `${dk64Colors.chunky} BP <1>, get 1 coin in the Block Tower room near R&D walkway {11}. Go to R&D`,
    `${dk64Colors.lanky} Banana trail around R&D (15) & BP <2>. W2 (25), W1.`,
    `${dk64Colors.lanky} Get free Chunky GB [16], Climb boxes & get 3 coins {11} to Buy Cranky & Candy moves (30)`,
    `${dk64Colors.tiny} Cranky & Candy moves {1}`,
    `${dk64Colors.chunky} Cranky & Candy moves {0}`,
    `${dk64Colors.diddy} Cranky moves`,
    `${dk64Colors.dk} Cranky moves. Balloon (25). Baboon Blast, getting 4 bunches (45).`,
    `${dk64Colors.dk} Climb pipe & kick-jump to power shed. Activate production room [17]. Power shed bunches (60).`,
    `${dk64Colors.chunky} Dark room bunches (25), GB [18], & rainbow coin.`,
    `${dk64Colors.chunky} Slam prod room switch, climb PR, collecting 1 coin along the way.`,
    `${dk64Colors.chunky} Crusher GB [19] & 2 arm bunches (35)`,
    `${dk64Colors.lanky} Balloon (40), PR GB [20] (65)`,
    `${dk64Colors.diddy} Tag high W4, BP <3> & slam PR switch.`,
    `${dk64Colors.diddy} Take W4, getting 10 bananas along the way (10). PR GB [21] (25)`,
    `${dk64Colors.dk} BP <3>. Crusher room bunches & GB [22](75). Exit`,
    `${dk64Colors.dk} Factory lobby music pad GB [23]. Re-enter Factory`,
    `${dk64Colors.dk} DK Arcade GB [24] & Nintendo Coin. Enter T&S`,
    `${dk64Colors.header} Feed with DK/Diddy/Lanky/Chunky`,
    `${dk64Colors.tiny} Key 3. Caged GB [25]. BP <2> Exit Factory`,
    `${dk64Colors.header} *Factory to Japes`,
    `${dk64Colors.chunky} Primate punch box`,
    `${dk64Colors.tiny} BP <3>. W4`,
    `${dk64Colors.chunky} Enter Japes lobby. Move rock.`,
    `${dk64Colors.lanky} Music Pad GB [26]. Enter Japes`,
    `${dk64Colors.header} *Japes 2`,
    `${dk64Colors.lanky} BP <3> & Speedy Swing [27]`,
    `${dk64Colors.tiny} Caged GB [28]. BP <4> & have at least 7 coins. Stump GB [29]`,
    `${dk64Colors.chunky} W5. Buy gun & Ammo Belt {0}. Rock GB [30]`,
    `${dk64Colors.chunky} Underground BP <2> & GB [31]. Exit Japes`,
    `${dk64Colors.header} *Japes to Galleon`,
    `${dk64Colors.chunky} W4. BC by Snide`,
    `${dk64Colors.diddy} Batty Barrel Bandit [32]`,
    `${dk64Colors.dk} Caged GB [33]`,
    `${dk64Colors.chunky} BP <3>. Enter Galleon`,
    `${dk64Colors.header} *Galleon`,
    `${dk64Colors.chunky} Open gate. 3 coins {3} & Cannon game GB & balloon [34](10).`,
    `${dk64Colors.chunky} Cannon to tag W3 & get bananas leadint to T&S (13).`,
    `${dk64Colors.chunky} Punch BC gate & get BC, chest GB [35] (20). W2 bananas (25)`,
    `${dk64Colors.diddy} Open gate`,
    `${dk64Colors.dk} Tunnel bunches (15)`,
    `${dk64Colors.chunky} Tunnel bunches (40), BP <4>, & balloon (50). Make sure you have 5 coins`,
    `${dk64Colors.lanky} Activate 5DS music pad (5), bunch under Enguarde (10), balloon over 5DS (20)`,
    `${dk64Colors.lanky} 5DS GB [36] & bananas (35). Exit/enter (40). BP <4>. BC balloons (60)`,
    `${dk64Colors.dk} Open gate. Raise water level.`,
    `${dk64Colors.dk} Lighthouse bunches, balloon, & GB (45)[37]. Shoot balloon outside lighthouse (55)`,
    `${dk64Colors.diddy} Turn in BP's [40]. Slam ship switch, use rocketbarrel to shoot balloon (10)`,
    `${dk64Colors.diddy} Top of LH GB & bunches [41] (20), BP <1>`,
    `${dk64Colors.lanky} Transform into Enguarde, break 3 chests with bunches, chest GB [42]`,
    `${dk64Colors.lanky} Bunches from broken chests & 2 bananas under Enguarde (77). Turn in BP's [46]`,
    `${dk64Colors.chunky} Turn in BP's [50]. Ship GB (75)[51]. Make sure you have 7 coins`,
    `${dk64Colors.tiny} Balloon (10). Turn in BP's [55]. Take W3 (20). BP & bananas <1> (23). Enter T&S`,
    `${dk64Colors.header} Feed with all Kongs`,
    `${dk64Colors.lanky} Key 4. Exit Galleon`,
    `${dk64Colors.header} *Galleon to Fungi`,
    `${dk64Colors.lanky} Caged GB [56], Turn in Key 4. W1`,
    `${dk64Colors.chunky} Caged GB [57]. Enter Fungi`,
    `${dk64Colors.header} *Fungi`,
    `${dk64Colors.chunky} W2 bunch (5)`,
    `${dk64Colors.dk} Cannon to turn to nighttime. Tag W4`,
    `${dk64Colors.dk} Pink tunnel (5) Tag Diddy on Bouncy Mushroom Tag`,
    `${dk64Colors.diddy} Buy SSS. Rocketbarrel (10) to top of mushroom, get 1 banana (11) & tag W5.`,
    `${dk64Colors.diddy} Enter middle mushroom. BP <2> & get 7 bananas (18). Exit mushroom by Kasplat`,
    `${dk64Colors.dk} Get 11 bananas going down the ladder from baboon blast & around the mushroom (16).`,
    `${dk64Colors.dk} Jump down & take W5 to the top (26). Enter mushroom.`,
    `${dk64Colors.chunky} Get all bananas going down the mushroom until you get to the night door. Exit door & get BP <1> & balloon.`,
    `${dk64Colors.dk} Re-enter mushroom and continue getting all but 1 bananas down to the bottom (60). Shoot switch at bottom of mushroom.`,
    `${dk64Colors.tiny} Shoot switch`,
    `${dk64Colors.lanky} Shoot switch & balloon (10)`,
    `${dk64Colors.diddy} Shoot switch`,
    `${dk64Colors.dk} Shoot switch & slam switch to spawn GB & overlap cannon spawn CS. Cannons to GB (41)[58]`,
    `${dk64Colors.lanky} Shoot balloon inside top of mushroom (20). Exit mushroom from top.`,
    `${dk64Colors.dk} Slam switch on top of mushroom (25). Dark room GB & bunches (35)[59]`,
    `${dk64Colors.chunky} Face puzzle room bunch, balloon, & GB (75)[60].`,
    `${dk64Colors.tiny} Drop down to get BC. Twirl to BP <2> & balloon (10).`,
    `${dk64Colors.tiny} Make sure you have at least 9 coins. Drop down to tag behind bottom of mushroom`,
    `${dk64Colors.lanky} Walk clockwise around the mushroom, getting 7 singles & W3 bunch (47).`,
    `${dk64Colors.lanky} Shoot switch & take yellow tunnel (57). BP <1>`,
    `${dk64Colors.diddy} Bananas around the tree & take W4 (38). Rocketbarrel bunches (48)`,
    `${dk64Colors.diddy} Climb mushroom near Snide & shoot balloon behind Snide's hedge (58)`,
    `${dk64Colors.diddy} 2 bananas climbing to attic (60). Attic bunches & GB (70)[62]. Bunch exiting attic (75)`,
    `${dk64Colors.dk} Balloon by Diddy attic (51), Tag Lanky behind attic`,
    `${dk64Colors.lanky} Baboon balloon (62). Attic bunches & GB (72)[61], 3 roof bananas (75). Tag DK`,
    `${dk64Colors.dk} 4 bananas on path to hedge (55). BP <4>`,
    `${dk64Colors.tiny} Balloon (20). Enter T&S`,
    `${dk64Colors.header} Feed with all Kongs`,
    `${dk64Colors.chunky} Key 5. Exit`,
    `${dk64Colors.header} *Fungi to Caves`,
    `${dk64Colors.diddy} Caged GB [63]. Jump down to W3`,
    `${dk64Colors.chunky} Turn in Key 5. W2. Music pad GB [64]. Enter Caves lobby. Break ice walls on both sides`,
    `${dk64Colors.lanky} BP <2>`,
    `${dk64Colors.diddy} Music pad GB [65]. Enter Caves`,
    `${dk64Colors.header} *Caves`,
    `${dk64Colors.diddy} Climb up to Funky & cross bridge (5). Enter rocketbarrel and tag W5.`,
    `${dk64Colors.diddy} Re-enter rocketbarrel. Waterfall bunch (10). Fly into tag by back waterfall`,
    `${dk64Colors.lanky} Shoot waterfall balloon (10)`,
    `${dk64Colors.tiny} Balloon over Kasplat (10). BP <3>. Play instrument to open 5DC door & delay Giant Kosha cutscene.`,
    `${dk64Colors.tiny} 5DC bunches, balloon, & GB (30)[66]`,
    `${dk64Colors.diddy} Top 5DC bunches & GB (25)[67]. Outside cabin balloon (35). (First if Kosha CS hasn't played yet, second if it has)`,
    `${dk64Colors.dk} Bongos pad bunch (5) (First if Kosha CS has already played, second if it hasn't)`,
    `${dk64Colors.lanky} Take W5 (cancel Kosha CS if not yet). BP <3> & bunches (30). Ice Castle balloon (40)`,
    `${dk64Colors.dk} BP <5>`,
    `${dk64Colors.chunky} Place rock on switch to access cave rock (13). Place cave rock on switch (24).`,
    `${dk64Colors.dk} Cave balloon & bananas (18). Bananas around baboon blast (23).`,
    `${dk64Colors.chunky} Buy Gorilla Gone`,
    `${dk64Colors.tiny} Buy Monkeyport`,
    `${dk64Colors.lanky} Baboon balloon bunches (55)`,
    `${dk64Colors.diddy} Rocketbarrel to W4 balloon & bunch (don't land) (50).`,
    `${dk64Colors.diddy} Fly through the switch above 5DI & get the bunches around it (70). 5DI balloon & GB (80)[68]`,
    `${dk64Colors.tiny} W3 bunch (35), Tag W1. Kill Giant Kosha, bunches, & rainbow coin (55).`,
    `${dk64Colors.tiny} 5DI balloon & GB (70)[69]. Banana trail in water (80)`,
    `${dk64Colors.dk} Take W1 (33). 4 Outside 5DI bananas (37). 5DI balloon, bananas, & GB (59)[70]`,
    `${dk64Colors.dk} 1 Banana leftover in igloo circle, kick to Tag`,
    `${dk64Colors.chunky} BP <2>. Ice barrier GB (29) [71]`,
    `${dk64Colors.chunky} W2 bunch (34). Invisible GB (42)[73]. Snide's cave balloon & bananas (55)`,
    `${dk64Colors.tiny} Turn in BP's [76]. Enter T&S`,
    `${dk64Colors.header} Feed with all Kongs`,
    `${dk64Colors.dk} Key 6. Turn in BP's [81]. Exit Caves.`,
    `${dk64Colors.header} *Caves to Castle`,
    `${dk64Colors.dk} Lava GB [82]. Enter Castle lobby. Open caged Kasplat`,
    `${dk64Colors.diddy} BP <3>. Deathwarp`,
    `${dk64Colors.dk} Enter Castle`,
    `${dk64Colors.header} *Castle`,
    `${dk64Colors.dk} Follow trail of bananas around to W1 and up to tag W2 (50). Jump down to tag`,
    `${dk64Colors.tiny} Tag W1. take W2 & follow banana trail to Cranky's (10). Buy SDSS`,
    `${dk64Colors.tiny} Banana trail to trash can (18). Trash can bunch & GB (23)[83]. Continue up to tag by ballroom (26).`,
    `${dk64Colors.diddy} Ballroom bunches & balloon (25)`,
    `${dk64Colors.tiny} Ballroom bunches (56). Continue up to top of castle (85)`,
    `${dk64Colors.chunky} Drop down from top of castle to shed (10)[84]. Museum balloon, bunch, & GB (25)[85]. Exit/Enter.`,
    `${dk64Colors.chunky} Enter tunnel from the water. All tunnel bananas leading to dungeon (43) & BP <3>.`,
    `${dk64Colors.chunky} Enter dungeon & punch down the 4 gates with Diddy's bunches`,
    `${dk64Colors.dk} Face puzzle (55)[86]`,
    `${dk64Colors.diddy} Dungeon bunches (45)`,
    `${dk64Colors.lanky} Dungeon balloons (20)`,
    `${dk64Colors.chunky} Dungeon balloons. Exit dungeon. Continue through tunnel & exit tunnel (75). W1`,
    `${dk64Colors.lanky} Tag W3, take W4. Greenhouse bunches & GB [87](50)`,
    `${dk64Colors.lanky} Drop down to BP <4>. Drop down to Crypt. Crypt bananas (80)`,
    `${dk64Colors.tiny} Crypt balloon (95)`,
    `${dk64Colors.diddy} BP <4>. Crypt balloon (55). Casket GB & balloon [88](70). Exit/enter`,
    `${dk64Colors.diddy} Use an orange lag assisted jump from the small tree near the level entrance to jump to the ledge and get to the Rocketbarrel near the water.`,
    `${dk64Colors.diddy} Top of post bunch (near Cranky) & balloon over tunnel entrance (85). Turn in BP's [92]`,
    `${dk64Colors.lanky} Tower balloon (90). Turn in BP's [96]`,
    `${dk64Colors.chunky} Turn in BP's [99]. Drop down to Cranky. Rareware coin. W3, W2. Enter T&S`,
    `${dk64Colors.header} Feed with all Kongs`,
    `${dk64Colors.lanky} Key 7. Exit Castle`,
    `${dk64Colors.header} *Post-Castle`,
    `${dk64Colors.lanky} Deathwarp`,
    `${dk64Colors.tiny} Exit Castle lobby. Turn in Keys 6 & 7. Monkeyport to music pad GB [100]`,
    `${dk64Colors.chunky} Enter Helm`,
    `${dk64Colors.header} Shut down Blast-o-Matic`,
    `${dk64Colors.dk} Key 8, exit Helm. Turn in Keys 8 & 3. Reset`,
    `${dk64Colors.header} *Beat K. Rool`
  ]
};
