import type { Route } from "../../classes/Route";
import { dk64Colors, titleColors } from "../../utils/colors";

export const dk64100GBMoveless: Route = {
  title: "100 GBs Moveless",
  headerColor: titleColors.dk64,
  doc: "https://docs.google.com/document/d/1bLiox0EkLVOEqQBI1x6snObW9ixUPpe4pGbW1XPBCwQ",
  steps: [
    `${dk64Colors.dk} Training Grounds, Tag W2, Aztec Early, {BP 1}, Llama cutscene skip, Tag W1, Key 5`,
    `${dk64Colors.header} RESET, Turn on Story Skip and Infinite Oranges, Enter file.`,
    `${dk64Colors.dk} Tag Isles W4 and W5, Turn in Key 5, Enter Castle`,
    `${dk64Colors.header} *Castle`,
    `${dk64Colors.dk} Enter Tree, {BP 2}, Castle Tree GB [1], W2 kick, Trashcan moonkick to Library, Library GB [2], Exit Library, Drop to W4 TnS, Enter KutOut, `,
    `${dk64Colors.header} FREE KONGS`,
    `${dk64Colors.lanky} Exit TnS with Lanky, Greenhouse GB [3], Drop to BP, {BP 1}, Enter Crypt, Lanky Crypt GB [4], Tag Diddy`,
    `${dk64Colors.diddy} {BP 1}, Exit, Phasewalk to {BP 2}, DEATHWARP, Tag Tiny`,
    `${dk64Colors.tiny} Phasewalk to Enter, STVW to BP, {BP 1}, Climb pole and swim under bridge to Candy Tunnel, Damage Chunky's Kasplat, Tag Chunky`,
    `${dk64Colors.chunky} {BP 1}, EXIT`,
    `${dk64Colors.header} *Castle Done`,
    `${dk64Colors.chunky} NO DEATHWARP Tag Lanky`,
    `${dk64Colors.lanky} Exit Castle Lobby, Isles Cage GB [5], Enter K. Lumsy, K. Lumsy Cage GB [6], Swim to Isles Tag, Tag DK`,
    `${dk64Colors.dk} TBS to Helm Lobby {BP 3}, Fall to Enter Factory Lobby, Tag Lanky`,
    `${dk64Colors.header} Enter Factory`,
    `${dk64Colors.lanky} Factory Early, Open Gate, Production Room GB [7], Jump to console at the end of the pipe, Tag DK`,
    `${dk64Colors.dk} {BP 4}, kick to W4 Tag Barrel, Tag Diddy`,
    `${dk64Colors.diddy} Drop for blueprint {BP 3}, head to Storage Room, Tag Lanky`,
    `${dk64Colors.lanky} Free Chunky GB [8], Tag Chunky`,
    `${dk64Colors.chunky} Tag W1, Dark Room GB [9], Tag Tiny`,
    `${dk64Colors.tiny} Get blueprint {BP 2}, Tiny Vent GB [10], Tag Chunky in TnS`,
    `${dk64Colors.chunky} Phasewalk to Stash Snatch GB [11], Phasewalk to Block Tower, {BP 2}, Tag DK`,
    `${dk64Colors.dk} Number Game Spawn Snag [1 2], Tag Lanky at R&D`,
    `${dk64Colors.lanky} {BP 2), Piano Game Spawn Snag [13], Drop Down Chute to Tag DK`,
    `${dk64Colors.dk} Crusher Room GB [14], Exit`,
    `${dk64Colors.header} *Exit Factory`,
    `${dk64Colors.dk} Exit Factory Lobby, Oclip to DK Cage GB [15], Phasewalk Cage Escape or deathwarp, Enter Galleon lobby, Tag Chunky`,
    `${dk64Colors.chunky} Chunky Galleon Lobby BP {BP 3}, Tag Lanky`,
    `${dk64Colors.lanky} Enter Galleon`,
    `${dk64Colors.header} *Enter Galleon`,
    `${dk64Colors.lanky} Phasewalk on the Right Pineapple Switch Wall to Cannon Game Room, STVW to Lighthouse area, Engaurde GB [16], Tag Diddy`,
    `${dk64Colors.diddy} Swim up for Blueprint {BP 4}, Orange Dive to Raise Water, Tag Chunky `,
    `${dk64Colors.chunky} Exit/Enter, Cannon Game Spawn Snag [17], VOID, Tag Tiny in Main area`,
    `${dk64Colors.tiny} Take Cannon to BP {BP 3}, Phasewalk to Cactus, Tag Chunky`,
    `${dk64Colors.chunky} {BP 4}, Tag Tiny`,
    `${dk64Colors.tiny} Exit/Enter, Phasewalk to Lagswim into Tiny 2DS [18], Tiny 5DS [19], Swim to Treasure room, Tag DK`,
    `${dk64Colors.dk} Moonkick for BP {BP 5}, Tag Lanky`,
    `${dk64Colors.lanky} Lanky Gold Tower GB [20], Exit/Enter, PhaseSwim to Cannon Game Room, Lanky BP {BP 3} STVW to 2DS, Lanky 2DS [21], Lanky 5DS [22], Swim to Candy Tag, Tag Tiny`,
    `${dk64Colors.tiny} Seal Race GB [23], EXIT`,
    `${dk64Colors.header} *Exit Galleon`,
    `${dk64Colors.tiny} Galleon Lobby GB [24], Exit Lobby, Swim to BFI, Tiny Isles Cage GB [25], W5, Tag DK`,
    `${dk64Colors.dk} Open Japes GB [26], Enter Japes`,
    `${dk64Colors.header} *Enter Japes`,
    `${dk64Colors.dk} Bush Push, DK Cage GB [27],  DK BP {BP 6}, Tag W3, Climb to Diddy Cage, Free Diddy GB [28], Other Free Diddy GB [29], kick to TnS, Tag Diddy`,
    `${dk64Colors.diddy} Exit TnS, Drop to BP {BP 5}, To Cranky Tag, Tag Lanky`,
    `${dk64Colors.lanky} Lanky BP {BP 4}, Speedy Swing Sortie GB [30], Phasewalk to Tag W4, PhaseSwim to Mad Maze Maul GB [31], Torch Push to Main Tag, Tag Chunky`,
    `${dk64Colors.chunky} PhaseSwim to Underground GB [32]  and BP {BP 5}, deathwarp, Leave Underground, Boulder GB [33], Beaver Skew, Tag Tiny at Cranky Tag`,
    `${dk64Colors.tiny} W4, Tiny Cage GB [34], W3, Tunnel to {BP 3}, Stump GB [35], Tag Diddy`,
    `${dk64Colors.diddy} Diddy Cage GB [36], Tag Chunky`,
    `${dk64Colors.chunky} Chunky Cage GB [37], Tag Lanky`,
    `${dk64Colors.lanky} Lanky Cage GB [38], Painting Room GB [39], Tag Tiny at main Tag`,
    `${dk64Colors.tiny} STVW to Splish Splash Salvage GB [40], Enter TnS, Tag Diddy`,
    `${dk64Colors.diddy} Exit TnS, Tunnel Room GB [41], EXIT`,
    `${dk64Colors.header} *Exit Japes`,
    `${dk64Colors.diddy} Tag DK`,
    `${dk64Colors.dk} Exit Japes Lobby, W2, Fungi Early, Enter Fungi Lobby, Enter Fungi`,
    `${dk64Colors.header} *Enter Fungi`,
    `${dk64Colors.dk} Go to Mill, Mill GB [42], Tag Diddy`,
    `${dk64Colors.diddy} Exit Mill, Diddy Cage GB [43], PhaseSwim and skew near Barn, Tag DK`,
    `${dk64Colors.dk} DK Blueprint {BP 7} Skew to Owl Race area, Tag Lanky`,
    `${dk64Colors.lanky} Get Lanky's BP {BP 5}, Back to Tag Tiny`,
    `${dk64Colors.tiny} Skew to Anthill GB [44], deathwarp, Go to Giant Mushroom Area, Go to far bouncy mushroom, Lag jump to Ladder under BBlast, Head to BP {BP 4}, Climb ladder to Tag, Tag Diddy`,
    `${dk64Colors.diddy} Enter Giant Mushroom, Get BP {BP 6}, climb inside of Giant Mushroom and exit at top, Clockwise to Tag, Tag Lanky`,
    `${dk64Colors.lanky} Lag Into Dark Room, Dark Room GB [45], Tag Chunky`,
    `${dk64Colors.chunky} Chunky BP {BP 6}, Pause Exit`,
    `${dk64Colors.header} *Exit Fungi`,
    `${dk64Colors.chunky} Tag Lanky`,
    `${dk64Colors.lanky} Phasewalk to BP {BP 6}, Tag DK`,
    `${dk64Colors.dk} Phasewalk to Lobby GB [46], Enter Caves`,
    `${dk64Colors.header} *Enter Caves`,
    `${dk64Colors.dk} Tag W2, Cross river, to DK BP {BP 8}, kick down to tag W4, To Igloo, STVW to DK 5DI [47], Tag Lanky`,
    `${dk64Colors.lanky} STVW to Lanky 5DI [48], Pause exit/enter on GB, To Tag, Tag DK`,
    `${dk64Colors.dk} Cross River, Ledgekick to W5, kick to top of Funky's, kick to Rotating Room, Rotating Room GB [49], Tag Tiny`,
    `${dk64Colors.tiny} To BP {BP 5}, Down to 5DC, Tiny 5DC [50], Tag Chunky`,
    `${dk64Colors.chunky} Olag through wall, Chunky 5DC [51], Tag Lanky`,
    `${dk64Colors.lanky} W5 to BP {BP 7}, W5 back, Tag Diddy`,
    `${dk64Colors.diddy} Olag through wall, Diddy 5DC [52], W5, phasewalk/tunnel push to BP {BP 7}, W4, Diddy 5DI [53], Tag Chunky`,
    `${dk64Colors.chunky} Chunky 5DI [54], Chunky BP {BP 7}, Ice Shield GB [55], EXIT`,
    `${dk64Colors.header} *Exit Caves`,
    `${dk64Colors.chunky} Exit Caves Lobby, STS to Chunky Cage GB [56], W3, Tag DK`,
    `${dk64Colors.dk} W2, Aztec Early, Enter Aztec`,
    `${dk64Colors.header} *Enter Aztec 2`,
    `${dk64Colors.dk} W1, Tag Diddy`,
    `${dk64Colors.diddy} BP{8}, Free Tiny GB [57]`,
    `${dk64Colors.tiny} Enter Tiny Temple, Klaptrap GB [58], Guitar Skip to BP {BP 6}, Enter Llama Temple through back, Tag W2, Tag W1, Ledgeclip on stairs to Far W2 area, Tiny Llama Temple GB [59], W2, climb up left stair to Tag , Tag Lanky`,
    `${dk64Colors.lanky} W1, W2, Lanky BP {BP 8}, W2, W1, Tag DK`,
    `${dk64Colors.dk} W1, Phasewalk to Free Lanky GB [60] from out of bounds, Leave Llama Temple, DK 5DT [61], Stealth Snoop GB [62], Head to Snide's and use sand tree, Enter Snide's [70], Tag Chunky`,
    `${dk64Colors.chunky} Turn in BP's [77], Tag Tiny`,
    `${dk64Colors.tiny} Turn in BP's [84], Tag Lanky`,
    `${dk64Colors.lanky} Turn in BP's [92], Tag Diddy`,
    `${dk64Colors.diddy} Turn in BPs [100]`,
    `${dk64Colors.header} *Done`
  ]
};
