import type { Route } from "../../classes/Route";
import { titleColors, yrColors } from "../../utils/colors";

export const yr100: Route = {
  title: "100%",
  headerColor: titleColors.yr,
  doc: "https://docs.google.com/document/d/1n2svxoKTQSJgf4RKa9tzPlnNCj5iVphVuSVyC2T8tDw",
  steps: [
    `${yrColors.header} *Hivory to Glitterglaze`,
    `${yrColors.header} Save One Book, Telescope for 1st Pagie [1]`,
    `${yrColors.hivory} Upper Cave Skip to Windy Bridge`,
    `${yrColors.hivory} Climb for Windy Bridge Pagie [2], Activate Mark by Glitterglaze, Pagie above Tome [3], drop to enter Glitterglaze`,
    `${yrColors.header} *Glitterglaze Glacier (400 coins before entering Tribalstack)`,
    `${yrColors.glitter} Activate Mark at start, Quills by start (3)`,
    `${yrColors.glitter} Across ramp to Quills on platform (6), Quills below bridge (9)`,
    `${yrColors.glitter} Climb to Normy [4], enter Cold Room`,
    `${yrColors.glitter} Fire Pits, Underwater Quills (13), Ann-Gree then Pagie [6], exit`,
    `${yrColors.glitter} River for Quills + Evie [7] (20), Surface for Left Stalagmite Quills (24)`,
    `${yrColors.glitter} Igloos Clockwise for pants and Clara [8], Panthony [9]`,
    `${yrColors.glitter} Right Stalagmite Quills (28), drop to Vent Quills (32), drop to Heidi + Quills [10] (36)`,
    `${yrColors.glitter} Surface for Top Hat, Lord Snowmon [11], Bully the Rocks [1/4]`,
    `${yrColors.glitter} Cross lake for Vent Pagie [12], drop to Kartos + Quills [15] (40)`,
    `${yrColors.glitter} Cross lake for Red Q.U.I.D.S [16], across for Quills on main land (44)`,
    `${yrColors.glitter} Grab fire, melt grenades, Quills on arch (47), Climb rocks to grenades for Statue [17]`,
    `${yrColors.glitter} Climb for grenade Pagie [18], Quills (51) to fire for Fee-Dee [19] (54)`,
    `${yrColors.glitter} Fly for Vent Pagie nearby [20], Regain flight for Cowboy Hat + Quills (58)`,
    `${yrColors.glitter} Climb for Quills behind tree (62), Far ledge Pagie Piece [2/4]`,
    `${yrColors.glitter} Activate Mark by Icymetric Palace, drop to Quills + Pagie Piece [3/4] (66) Warp to Start`,
    `${yrColors.glitter} Purchase Quill Magnet + Energy Upgrade from Trowzer, Equip Quill Magnet from Vendi`,
    `${yrColors.glitter} Near ramp to magnet Quills, enter Crystalline Cave (69)`,
    `${yrColors.glitter} Down ramp w/ Quills (73), Pagies + Quills in Crystalline Cave [24] (79), exit`,
    `${yrColors.glitter} Slam Switch for Cagie [25], Dive for Witch Hat, Gloomy Gem Grotto [26]`,
    `${yrColors.glitter} Surface to Hailey w/ Underwater Quills [27] (82)`,
    `${yrColors.glitter} Quills on rocks (86), Snowball Pagie Piece [28]`,
    `${yrColors.glitter} Grenade Pagie [29], Blow up Mollycool Rock, Battle for Pagie Piece [1/4]`,
    `${yrColors.glitter} Grab Mollycool + Quills (90), Magnet Quills from behind crates (94), Transform`,
    `${yrColors.glitter} Shiver E. Timbers [30], Plough Roy + Tree Pagie Piece [31] [2/4]`,
    `${yrColors.glitter} Climb for 3-Lap Q.U.I.D.S + Pagie Piece [32] [3/4]`,
    `${yrColors.glitter} Magnet Quills before dropping + on the way + nearby Sonar Pagie [33] (108) Warp by Palace`,
    `${yrColors.glitter} Fly to hit Cagie Switch, Pirate Treasure during race [1/5] [34], enter Icymetric Palace`,
    `${yrColors.glitter} First room Pagie Piece + Quills [35] (111), East -> West -> North (115) to Race Room [36]`,
    `${yrColors.glitter} Through Gate, Quills before Brrreeze Blok (118), Brrreeze Blok [39]`,
    `${yrColors.glitter} East to Switches Cagie [40] Warp to Palace Entrance`,
    `${yrColors.glitter} East for Quills (122), West for Play Coin + Rextro + Quills [43] (126)`,
    `${yrColors.glitter} Back to other entrance for Walls Pagie [44] Warp to Entrance`,
    `${yrColors.glitter} West -> West to Ice Puzzle [45] Gauntlet Pagie [46] (129)`,
    `${yrColors.glitter} Red Q.U.I.D.S [47], Lost Woods Room (E-E-N-W) to Storage [48] (133) Warp to Entrance`,
    `${yrColors.glitter} North -> North to Targets [49], Quiz Show [50] Warp to Entrance`,
    `${yrColors.glitter} Dive for Underwater Entrance (137), Jellyfish Pagie [51] (140), Vent to grenade room (143)`,
    `${yrColors.glitter} Grenade Room Quills to Hot Tub Pagie + Quills [53] (150) Exit to Hivory`,
    `${yrColors.header} *Hivory to Tribalstack`,
    `${yrColors.hivory} Pagie up Slide [54] Warp to Mark, Pipe Pagie [55], Bomb Rock Pagie [56], Cross Windy Bridge to Hub 1`,
    `${yrColors.hivory} Pipe Pagie above Tribalstack [57], drop to enter Tribalstack`,
    `${yrColors.header} *Tribalstack Tropics`,
    `${yrColors.tribal} Trowzer to purchase Extra Tonic from Glitterglaze`,
    `${yrColors.tribal} Vendi to purchase & equip Charged Up + One Hit Wonder, Normy by start [58] (3), Activate Mark, Red Q.U.I.D.S [59], Land on platform above Quills to Ramp Pagie Piece [1/4] (6)`,
    `${yrColors.tribal} Climb for Fire Pagie [60], Pagie behind wall [61], Quills + Pagie in front of Rampo [62] (9), Rampo Pagies and Quills [65] (12), Drop for Quills + Pirate Treasure [2/5] (16)`,
    `${yrColors.tribal} Climb rock to the left (19) to talk to Torn Pagie, Clockwise for Pieces, Heidi, Quills, & Scoffsalot (talk to Torn Pagie later) [66] (22)`,
    `${yrColors.tribal} Up ramp for nearby Quills (26), Climb to flight Pagie + Quills [67] (30)`,
    `${yrColors.tribal} Fly to Quills above Shovel Knight's gems (34), grab Gem`,
    `${yrColors.tribal} Down for Red Q.U.I.D.S [68], drop for Quills on corner and Pagie Piece below [2/4] (37)`,
    `${yrColors.tribal} Shovel Knight Pagie [69], drop to bomb rock for Evie + nearby Quills [70] (40)`,
    `${yrColors.tribal} Arch Pagie Piece w/ Fee-Dee Dance Skip [71] [3/4], nearby Quills (44)`,
    `${yrColors.tribal} Talk to Lootsalot (47), climb to Clara Pagie, Pagie Piece, & Quills [73] (51)`,
    `${yrColors.tribal} Race Nimble w/ 23 Quills + Play Coin [74] (74), Grab Ice, Duke's Pagie [75]`,
    `${yrColors.tribal} Talk to Torn Pagie [76], drop for Quills + Green Q.U.I.D.S challenge [77] (77)`,
    `${yrColors.tribal} Activate Mark by Monument Ramp Timer Cagie [78]`,
    `${yrColors.tribal} Green Q.U.I.D.S w/ Quills nearby [79] (84), Drop Mollycool (collect later), Matching Pagie w/ Quills [80] (88)`,
    `${yrColors.tribal} Hit switch for Sonar Pagie, Spawn Green Q.U.I.D.S Pagie, collect Sonar Pagie [81], Magnet Quills to Green Q.U.I.D.S Pagie [82] (92)`,
    `${yrColors.tribal} Rextro w/ Quills from behind [85] (95), climb for Pagie Piece [1/4], talk to Shootsalot`,
    `${yrColors.tribal} Cross to collect Mollycool, Quills to Dr. Puzz (99), TRANSFORM`,
    `${yrColors.tribal} Flower Pagie + Quills [86] (103), De-Transform, enter Underwater Tunnel (106), 2 Pagies inside [88] Warp to Mark by Monument`,
    `${yrColors.tribal} Climb without Lashes to Quills (110), up to caged Green Q.U.I.D.S [89], Quills before loading zone (113)`,
    `${yrColors.tribal} Kartos [92] (121), Cannonball, Climb to Pagie Piece on vent [2/4], switch for vents Pagie [93]`,
    `${yrColors.tribal} Climb sonar platforms to loading zone (124)`,
    `${yrColors.tribal} Blastooie [94], climb for Quills & Pagie [95] (128), Drop to clip for Camo Pagie [96], Leave`,
    `${yrColors.tribal} (132) Mr. Blowy Pagie + Pagie Piece [97] [3/4]`,
    `${yrColors.tribal} Red Q.U.I.D.S [98], Up ramp to Quills by loading zone (136)`,
    `${yrColors.tribal} Climb for Pagie Piece [99], drop to Quills and Ice Pagie [100] (140)`,
    `${yrColors.tribal} Down to Ann-Gree [101], Quills by Nimbo (143), Water then Ice Nimbo, Warp to Start`,
    `${yrColors.tribal} Race Nimble 2 [102], enter Treasure Chamber for Quills + Leapalot's Pagie [103] (146)`,
    `${yrColors.tribal} Leave for Ghost Writer's Pagies + Quills [107] (150), Pause Exit to Hivory`,
    `${yrColors.header} *Hivory to Moodymaze`,
    `${yrColors.hivory} Down ramp to P.A.G.I.E [108], Activate Mark, Firefighter Pagie [109], Statue Pagie [110]`,
    `${yrColors.hivory} Leave to Shipwreck, Green Q.U.I.D.S [111], Up for Blasto [112]`,
    `${yrColors.hivory} Down to Lizard Lash Pagie in the sand [113], Climb for Mast Pagie [114] Warp to Hivory`,
    `${yrColors.hivory} Climb for Underwater Painting Pagie [115], Climb to loading zone`,
    `${yrColors.hivory} Across bridge to Underwater Chest Pagie [116], Hidden Painting [117], Barrel Pagie [118]`,
    `${yrColors.hivory} Climb for Plumbing Pagie [119], All Rextro Pagies [129], enter Archive `,
    `${yrColors.hivory} Archive Pagie [130], enter Waterworks`,
    `${yrColors.hivory} Camo Pagie [131], Hit Switch for Kirkhope Pagie [132], Underwater Timer Cagie [133]`,
    `${yrColors.hivory} Crate Pagie [134], climb to enter Moodymaze`,
    `${yrColors.header} *Moodymaze Marsh`,
    `${yrColors.moody} Climb for Pagie Piece behind start [1/4] Skip water tunnel, grab Quills before hitting switch for Jack-O-Lantern Cagie [135] (4)`,
    `${yrColors.moody} Across to Lash for Marsh Match Pagie and Quills [136] (11)`,
    `${yrColors.moody} Quills on pipe and behind mushrooms (18), Mushrooms Pagie [137]`,
    `${yrColors.moody} Across bridge to Quills and switch Pagie [138] (21), CCW around Maze to Quills (25)`,
    `${yrColors.moody} Leap on maze roof, do Red Q.U.I.D.S, grab Pagie Piece -> Pagie -> Pipe Quills [139] [2/4] (28), drop to Ollie, Maze Pagie [140]`,
    `${yrColors.moody} Leave for Quills under Tree (31), Across mushrooms for Quills + Pagie Piece [3/4] (35)`,
    `${yrColors.moody} Slam bouncy mushroom for Pagie Piece [141]`,
    `${yrColors.moody} Behind tree for Quills (39), Leap to Ann-Gree [142]`,
    `${yrColors.moody} Quills behind mushroom (43), Quills by pool (46), Underwater Pagie [143]`,
    `${yrColors.moody} Enter Pumping Plant for 2 Pagies [145], Climb for Quills + Pirate Treasure [3/5] (50)`,
    `${yrColors.moody} Quills on Pipe (54), Activate Mark, Quills behind Lash Box (56), Lash to Pagie [146]`,
    `${yrColors.moody} Quills on Container (59), Drop to Slam Pagie Piece by blue mushrooms [1/4]`,
    `${yrColors.moody} Heidi + Quills [147] (62), Head across swamp (65)`,
    `${yrColors.moody} Burn Ropes Pagie [148], Quills by Jolly (68), Jolly Pagie [149]`,
    `${yrColors.moody} Lash for Quills and Lantern Pagie [150] (71), Quills under tree (75)`,
    `${yrColors.moody} Grab Mollycool, Murky Passage [151], Swampy Station Pagies with Evie [154] (79)`,
    `${yrColors.moody} Play Coin underwater, Climb to Rextro [157] (83)`,
    `${yrColors.moody} Red Q.U.I.D.S w/ nearby Quills [158] (87)`,
    `${yrColors.moody} Climb for Quills by Trev (91), fight Trev [161]`,
    `${yrColors.moody} Hit plant for green Q.U.I.D.S [162], Kartos [165] (95), Climb to top for Pagie [166]`,
    `${yrColors.moody} Drop to cross bridge for Timer Challenge + Quills [167] (103)`,
    `${yrColors.moody} Quills behind rock (106), Clara's Pagie [168] (110)`,
    `${yrColors.moody} Across pipe for Quills by vents (114), Fee-Dee [169]`,
    `${yrColors.moody} Underwater Quills to switch (120) Underwater Pagie [170]`,
    `${yrColors.moody} Behind area for Quills by loading zone (124), “Platforming Course” Pagies [172]`,
    `${yrColors.moody} Lilypad Quills (128), Lizard Lash Pagie [173]`,
    `${yrColors.moody} Quills under tree (131), nearby Pagie Piece [2/4]`,
    `${yrColors.moody} Jack-O-Lantern Pagies + Quills [175] (134), Warp to Mark`,
    `${yrColors.moody} Normy + Quills [176] (138)`,
    `${yrColors.moody} Log Quills to GW Pagies [179] (142), kick mushroom for Pagie Piece [3/4]`,
    `${yrColors.moody} Climb for Quills to Pagie Piece on bush [180] (146), Quills to top of rocks Pagie [182] (150)`,
    `${yrColors.moody} Drop to Dr. Puzz to TRANSFORM`,
    `${yrColors.moody} Thorns Pagie [183], Dusky Duct [184], Pause Exit to Hivory`,
    `${yrColors.header} *Hivory to Cashino`,
    `${yrColors.hivory} Go through 55 Pagie Door, Activate Mark`,
    `${yrColors.hivory} Buddy Slam Pagie by rock [185], Golf Pagie [186]`,
    `${yrColors.hivory} Activate Tome, Painting by Cashino [187], enter Cashino`,
    `${yrColors.header} *Capital Cashino {150 Tokens}`,
    `${yrColors.header} (*It's very easy to pick up extra quills in random places in this level, so take quill counts with a grain of salt here)`,
    `${yrColors.cash} Talk to Handle Barr, Handle Barr's Tokens {5}`,
    `${yrColors.cash} Up to fountain, magnet Quills by statue and underwater during green Q.U.I.D.S {10} (7)`,
    `${yrColors.cash} Quills by Mark (11), Slots for Mollycool, TRANSFORM`,
    `${yrColors.cash} Machine nearby + Quills {11} (15), talk to Scoffsalot (18)`,
    `${yrColors.cash} Front of House of Cards Quills + Quills behind boxes on Gallery Roof during race (25)`,
    `${yrColors.cash} Tokens + Quills in destination {17} (28)`,
    `${yrColors.cash} Fly up to Activate Mark by Kartos, nearby machine + Quills {18} (32)`,
    `${yrColors.cash} Machine + Quills on red dice below {19} (36), Talk to Lootsalot`,
    `${yrColors.cash} Quills on Pipe + Fountain Tokens + Shoot machine by Roll Jupp during race {24} (39)`,
    `${yrColors.cash} Lootsalot tokens {29}, Detransform for Vault Tokens {34}`,
    `${yrColors.cash} Quills behind boxes (42), Pagie Piece inside Poker Chips [1/4], Climb and talk to Roll Jupp`,
    `${yrColors.cash} Roll Jupp's Tokens {39}, Across for machine Token {40}, drop to Quills (45)`,
    `${yrColors.cash} Quills by Ice Berry Puzzle room (49)`,
    `${yrColors.cash} Ice Puzzle w/ Fee-Dee [188] {45} (53), Pachinko Tokens + Quills {50} (56), TRANSFORM`,
    `${yrColors.cash} Pagie Piece by Shootsalot [2/4], Shoot Machine by fountain, Shootsalot Tokens {55}`,
    `${yrColors.cash} Quills on flag (59), Quills behind post on golf course (63) fly to shoot Machine by Heidi, drop to Leapalot {60}`,
    `${yrColors.cash} Quills on ledge below (67), Cornelius Pagie Piece w/ Machine Token [3/4] {61}`,
    `${yrColors.cash} Machine Token by Leapalot {62}`,
    `${yrColors.cash} Quills nearby (70) and on nearby red dice (74)`,
    `${yrColors.cash} Shoot Machine by Power Grid before detransforming on ledge w/ Quills (77)`,
    `${yrColors.cash} Across for vent Quills (81), back across for Normy [189]`,
    `${yrColors.cash} Drop for Token and Quills {63} (84), Power Grid Tokens {68}, Warp to Mark`,
    `${yrColors.cash} Slots by Kartos {73}, Slam Poker Chip for Pagie Piece [190], Climb for Heidi [191]`,
    `${yrColors.cash} Along path for Machine Token + Quills {74} (88), Across for Golf Tokens + Quills {84} (92)`,
    `${yrColors.cash} Drop to talk to Max Bet, Matching Game Tokens {89}, Quills behind plant nearby (96)`,
    `${yrColors.cash} Nearby Slots {94} and Roulette [1/4]`,
    `${yrColors.cash} Quills on dice (99) up to Red Q.U.I.D.S {99}, Drop for Quills by stairs and under table (107)`,
    `${yrColors.cash} Nearby Roulette {104}, Quills under ramp (110)`,
    `${yrColors.cash} Take ramp for Disco Tokens + Ann-Gree [192] {109}, Quills behind Roulette (114)`,
    `${yrColors.cash} Wind Game, Glass Quills before grabbing Tokens {119} (117), Slots {124}`,
    `${yrColors.cash} Release Pachinko game, Quills behind Slots during while waiting for Tokens {129} (120)`,
    `${yrColors.cash} Slots {134}, Security Pagie Piece [2/4], Warp to Mark`,
    `${yrColors.cash} Gallery Roof for Quills (124), Pirate Treasure [4/5]`,
    `${yrColors.cash} Rest of Roof Quills + Pagie Piece [3/4] (128), Drop to Enemy Room Tokens {139}`,
    `${yrColors.cash} Evie [193], Drop for Machine Token + Quills {140} (132), Painting Pagie Piece [194]`,
    `${yrColors.cash} Ghost Writer Pagies [197], Quills to Mustache Painting Tokens {145} (139)`,
    `${yrColors.cash} Quills behind crates in corner (143), Slots for Play Coin`,
    `${yrColors.cash} Quills behind Rextro (147), Rextro [200], Glass Tokens {150}, Quills behind boxes [201] (150)`,
    `${yrColors.cash} Talk to Cashital Zee, Warp to Mark, start Kartos while Pagies are cashing in`,
    `${yrColors.cash} Kartos + I.N.E.P.T. [237], Pause Exit to Hivory`,
    `${yrColors.header} *Hivory to Galaxy`,
    `${yrColors.hivory} Warp to Mark by entrance, Containers [238], Poison Pipe [239], fly to Red Q.U.I.D.S challenge, grab Pagie in flight [240]`,
    `${yrColors.hivory} Activate Mark by Galaxy, backtrack to gate switch, top of climb Pagie [241], Lash Book [242], Book Puzzle [243]`,
    `${yrColors.hivory} Drop to Statue Pagie [244], Dominos [245], Warp to Mark by Galaxy, enter Galaxy`,
    `${yrColors.header} *Galleon Galaxy`,
    `${yrColors.galleon} Magnet Quills by Vendi while climbing to Normy [246] (3)`,
    `${yrColors.galleon} Gain flight, Dip for Quills below (6), Sonar Chest, grab Pagie Piece [1/4]`,
    `${yrColors.galleon} Slam for Pagie nearby [247], Quills (10) on the way to Sonar Chest by Lighthouse [248], Quills before entering Cave for Pagies [250] (14)`,
    `${yrColors.galleon} Magnet Quills from under bridge (18), continue CCW to Activate Mark by Lighthouse (25)`,
    `${yrColors.galleon} Climb for Green Q.U.I.D.S [251], Leap for Pagie Piece [2/4], Lighthouse Quills + Mollycool Warp to Mark (35)`,
    `${yrColors.galleon} Talk to Dr. Puzz to Transform, Blast Rock, hit Ice Gate, around to melt Torn Pagie `,
    `${yrColors.galleon} Detransform for Torn Pagie Pieces in flight, top of Lighthouse Pagie [252], drop to hit wheel for Pagie [253], talk to Torn Pagie [254], Transform`,
    `${yrColors.galleon} Quills behind boxes (39), Lower Gate to Shooting Game [255] (43)`,
    `${yrColors.galleon} Take ship to melt dome for Fee-Dee [256], Detransform, flight to Sonar Chest to grab Play Coin`,
    `${yrColors.galleon} Shootsalot Key w/ Quills nearby (46), Rextro [259] (50)`,
    `${yrColors.galleon} Scoffsalot Key, Magnet underwater Quills + peninsula Quills to Lootalot Key (60), grab water, climb to Leapalot Key (63), Treasure Quills + Pagie [260] (67) Warp to Mark`,
    `${yrColors.galleon} Behind lighthouse to fly for Mast Pagie [261], drop for Quills to front of ship to Lash rocks (74)`,
    `${yrColors.galleon} Activate Mark by Dome (78), hit wheel to grab grenades, Grenade main entrance, Lash up to grenade and enter top entrance w/ nearby Quills (85)`,
    `${yrColors.galleon} Portal to Aquarium Pagie + Pagie Piece [262] [3/4], Portal then Warp to Mark to main entrance`,
    `${yrColors.galleon} Dome Pagie [263], Warp to Mark by Dome`,
    `${yrColors.galleon} Take ramp to battle for Pagie Piece + Quills [264] (89), Velocity Terminal [266] Warp to Mark by Dome`,
    `${yrColors.galleon} Lash Rocks to enter Captain's Cabin for Pagie Piece + Pagie + Quills [267] [1/4] (93)`,
    `${yrColors.galleon} Leave, Lash Rocks from back of ship (97) Activate Mark by Rusto`,
    `${yrColors.galleon} Climb to power shoulder, Heidi before entering Rusto [268] (101), Rusto Pagie [269], drop for electricity to power foot for Pagie Piece [2/4]`,
    `${yrColors.galleon} Talk to Schell w/ Quills on Rusto's knee + behind rocks (107), Quills before entering portal [270] (111), Through gates to blow up planet [271], Warp to Mark by Rusto`,
    `${yrColors.galleon} Transform, Fight Planette [274], Near ship for green Q.U.I.D.S + Pagie Piece + Evie [276] [3/4]`,
    `${yrColors.galleon} Sail to Ice Gate for Nimble Race + Quills [277] (115)`,
    `${yrColors.galleon} Detransform by Strength Island for Quills + Strength Pagie [278] (119)`,
    `${yrColors.galleon} Red Q.U.I.D.S w/ Quills + Chest Pagie [280] (123), enter Black Hole In One (127)`,
    `${yrColors.galleon} Golf Pagies + Ann-Gree [283], Warp to Mark by Rusto`,
    `${yrColors.galleon} Behind island for Kartos w/ Quills by Mark [286] (137), Climb for Fishing Pagies [288]`,
    `${yrColors.galleon} Climb for Ghost Writer Pagies [291], nearby Quills + center Pagie + Pagie Piece [293] (140)`,
    `${yrColors.galleon} Open plumbing room, Break door for flight, do plumbing room and leave, take flight to grab all Quills +Pagie in flight to Pirate Treasure [295] [5/5] (150)`,
    `${yrColors.header} *Hivory to END`,
    `${yrColors.hivory} Climb to enter Slide Ride [296], Wind Tunnel [297], fight Capital B [300]`
  ]
};
