import type { Route } from "../../classes/Route";
import { titleColors, yrColors } from "../../utils/colors";

export const yrNED: Route = {
  title: "No Early Doors (120 Pagies)",
  headerColor: titleColors.yr,
  doc: "https://docs.google.com/spreadsheets/d/1PH2CqKKFc4VNgTAo9cVIYLqi2r7e7esLn97NiIlNXwM",
  steps: [
    `${yrColors.header} Navigate OOB to Wind Pipe`,
    `${yrColors.hivory} Telescope Pagie`,
    `${yrColors.hivory} Wind Pipe`,
    `${yrColors.hivory} Water Painting`,
    `${yrColors.header} *Enter Tribalstack`,
    `${yrColors.tribal} Normy`,
    `${yrColors.tribal} Evie`,
    `${yrColors.tribal} Arch Pagie Piece`,
    `${yrColors.tribal} Fee-Dee`,
    `${yrColors.tribal} Sonar Reds`,
    `${yrColors.tribal} Rampo Pagie Piece - Jump off the switch to get up the temple after`,
    `${yrColors.tribal} Rampo Soaring`,
    `${yrColors.tribal} Rampo Nook`,
    `${yrColors.tribal} Heidi`,
    `${yrColors.tribal} Green Coin middle temple`,
    `${yrColors.tribal} Slam Puzzle - Hit the button for sonar plats right after but dont get the pagie immediately`,
    `${yrColors.tribal} Green Coin Rextro`,
    `${yrColors.tribal} Sonar Plats`,
    `${yrColors.tribal} Planker`,
    `${yrColors.tribal} Summit`,
    `${yrColors.tribal} Blastooie`,
    `${yrColors.tribal} Cannonball Wind`,
    `${yrColors.tribal} Wind Pagie Piece`,
    `${yrColors.tribal} Targets by anngree`,
    `${yrColors.tribal} Ann Gree`,
    `${yrColors.tribal} Green Coins side of monument - After this pagie you can climb up a pillar to water blowie`,
    `${yrColors.tribal} Blowie Pagie Piece - Grab with a jump twirl, buffer glide afterwards to get back`,
    `${yrColors.tribal} Water Bush Blowie`,
    `${yrColors.tribal} Red Coins Blowie`,
    `${yrColors.tribal} Ghosts Pedestal 1`,
    `${yrColors.tribal} Ghosts Pedestal 2`,
    `${yrColors.tribal} Ghosts Pedestal 3`,
    `${yrColors.tribal} Green Coins Beside Ghosts`,
    `${yrColors.header} *Return to Hivory`,
    `${yrColors.hivory} Torches`,
    `${yrColors.header} Firefighter`,
    `${yrColors.hivory} Statue`,
    `${yrColors.hivory} Hallway Painting`,
    `${yrColors.hivory} Yellow Barrel - Grab Mark beside Arcade after`,
    `${yrColors.hivory} Jellyfish Chest`,
    `${yrColors.hivory} Bush above windy bridge`,
    `${yrColors.hivory} Bomb Block`,
    `${yrColors.hivory} Inside the Pipe`,
    `${yrColors.hivory} Above Glitter Tome`,
    `${yrColors.header} *Enter Glitterglaze`,
    `${yrColors.glitter} Normy`,
    `${yrColors.glitter} Ann Gree`,
    `${yrColors.glitter} Heat Up Room`,
    `${yrColors.glitter} Evie`,
    `${yrColors.glitter} Clara`,
    `${yrColors.glitter} Pants Snowman`,
    `${yrColors.glitter} Heidi`,
    `${yrColors.glitter} Top Hat - Grab Witch Hat After`,
    `${yrColors.glitter} Cowboy Hat - Can slope climb up the wall behind him to get to the bomb`,
    `${yrColors.glitter} Bomb Statue - Go aim mode and shoot from bomb bush, grab pagie after bomb tower`,
    `${yrColors.glitter} Flight Cliff`,
    `${yrColors.glitter} Fee Dee`,
    `${yrColors.glitter} Bomb Blocks Tower`,
    `${yrColors.glitter} Blast Shooter`,
    `${yrColors.glitter} Witch Hat`,
    `${yrColors.glitter} Ghosts Pedestal 1`,
    `${yrColors.glitter} Ghosts Pedestal 2`,
    `${yrColors.glitter} Ghosts Pedestal 3`,
    `${yrColors.glitter} Music Crystals`,
    `${yrColors.header} *Return to Hivory`,
    `${yrColors.hivory} NonSticky Slide - Warp to Arcade after`,
    `${yrColors.hivory} Arcade`,
    `${yrColors.hivory} Manhole`,
    `${yrColors.hivory} Archive`,
    `${yrColors.hivory} Camo`,
    `${yrColors.hivory} Crazy Kirkhope`,
    `${yrColors.hivory} Water Race`,
    `${yrColors.hivory} Water Box`,
    `${yrColors.header} *Enter Moodymaze`,
    `${yrColors.moody} Mushroom Pagie Piece - Flat bouncy mushroom right beside red ghost`,
    `${yrColors.moody} Ann Gree`,
    `${yrColors.moody} Dont Touch Water`,
    `${yrColors.moody} Water race with spiky balls - Activate Mark after`,
    `${yrColors.moody} In the trees`,
    `${yrColors.moody} Blue Mushroom Pagie Piece`,
    `${yrColors.moody} Heidi - Activate Mark after (near rope burn)`,
    `${yrColors.moody} Burn the rope`,
    `${yrColors.moody} Target Practice`,
    `${yrColors.moody} Pumpkin Lash Course 1`,
    `${yrColors.moody} Fire Lash Course - Warp to Mark after (rope burn)`,
    `${yrColors.moody} Underwater Vent`,
    `${yrColors.moody} Fee Dee - You can warp while he's eating`,
    `${yrColors.moody} Lake Wind Pipe`,
    `${yrColors.moody} Hanging Lantern`,
    `${yrColors.moody} Stone above Puzz`,
    `${yrColors.moody} Under Tree by Puzz Pagie Piece`,
    `${yrColors.moody} Thorns Pagie OOB`,
    `${yrColors.moody} Secret Stash`,
    `${yrColors.moody} Rep Rush Course`,
    `${yrColors.moody} Evie - Warp to Mark after (water race with spiky balls)`,
    `${yrColors.moody} Normy`,
    `${yrColors.moody} Ghosts Pedestal 1`,
    `${yrColors.moody} Ghosts Pedestal 2`,
    `${yrColors.moody} Ghosts Pedestal 3`,
    `${yrColors.moody} Mini Mush Pagie Piece`,
    `${yrColors.header} *Return to Hivory`,
    `${yrColors.hivory} Spiky Ball Slam`,
    `${yrColors.hivory} Toxic Pipe - it is technically fastest to get minigolf right before cashino entry if youre good at it instead of this pagie`,
    `${yrColors.hivory} Shipping Container Tower`,
    `${yrColors.hivory} Red Coins in flight tunnel - Grab Mark beside Galleon after`,
    `${yrColors.hivory} Beside Novel Hovel Gate`,
    `${yrColors.hivory} Book Lash`,
    `${yrColors.hivory} Statue`,
    `${yrColors.header} *Enter Cashino`,
    `${yrColors.cash} Display Cases - Grab Mark on world entry`,
    `${yrColors.cash} 5 Slam Slot - Drop Pachinko Balls before this machine`,
    `${yrColors.cash} Pachinko Near Slots`,
    `${yrColors.cash} 3 Slam Slot`,
    `${yrColors.cash} Paint Bucket Painting - Movement here is weird but you climb straight up to evie on the dice`,
    `${yrColors.cash} Evie`,
    `${yrColors.cash} Roulette Fight Room`,
    `${yrColors.cash} Kartos Slot`,
    `${yrColors.cash} Chip Pagie Piece`,
    `${yrColors.cash} Heidi`,
    `${yrColors.cash} Roulette Wheel - You can head to Ann Gree while you wait for the ball to land`,
    `${yrColors.cash} Ann Gree - Can Grab roulette wheel tokens after this one`,
    `${yrColors.cash} Disco`,
    `${yrColors.cash} Broken Slots - Start roulette pagie piece right before`,
    `${yrColors.cash} Roulette Pagie Piece - If you don't get this first try you can opt for the chip camo towers piece instead`,
    `${yrColors.cash} Red Coins on Roulettes`,
    `${yrColors.cash} Green Coin on fountain`,
    `${yrColors.cash} Top of Fountain`,
    `${yrColors.cash} Pachinko Near house of cards - Input first password while you wait for tokens`,
    `${yrColors.cash} Fee Dee`,
    `${yrColors.cash} Ice Shoot Puzzle - Warp to Mark and hand in tokens (Get backup Pagie Piece if needed before you warp)`,
    `${yrColors.cash} Normy`,
    `${yrColors.cash} Chip Tower Pagie Piece`,
    `${yrColors.cash} Painting Pagie Piece`,
    `${yrColors.cash} Ghosts Pedestal 1`,
    `${yrColors.cash} Ghosts Pedestal 2`,
    `${yrColors.cash} Ghosts Pedestal 3`,
    `${yrColors.header} *Return to Hivory`,
    `${yrColors.hivory} Cashino Lobby Painting`,
    `${yrColors.header} *Capital B Fight`,
    `${yrColors.header} GG!`,
    `${yrColors.header} *BACKUPS IF MISSING ANY AT THE END`,
    `${yrColors.hivory} Windy Pipe (25 Seconds)`,
    `${yrColors.hivory} Hub Golf (20-35 Seconds Depending on "Luck")`,
    `${yrColors.hivory} Slide (30 Seconds)`,
    `${yrColors.hivory} Dominos (25+ Seconds)`
  ]
};
